// This file is auto-generated by @hey-api/openapi-ts

export const APIListResponse_UserDetailsResponse_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total',
            description: 'The total number of items in the list'
        },
        data: {
            items: {
                '$ref': '#/components/schemas/UserDetailsResponse'
            },
            type: 'array',
            title: 'Data',
            description: 'The list of items returned by the API'
        },
        empty: {
            type: 'boolean',
            title: 'Empty',
            description: 'Whether the list is empty'
        }
    },
    type: 'object',
    required: ['total', 'data', 'empty'],
    title: 'APIListResponse[UserDetailsResponse]'
} as const;

export const APIListResponse_UserResponse_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total',
            description: 'The total number of items in the list'
        },
        data: {
            items: {
                '$ref': '#/components/schemas/UserResponse'
            },
            type: 'array',
            title: 'Data',
            description: 'The list of items returned by the API'
        },
        empty: {
            type: 'boolean',
            title: 'Empty',
            description: 'Whether the list is empty'
        }
    },
    type: 'object',
    required: ['total', 'data', 'empty'],
    title: 'APIListResponse[UserResponse]'
} as const;

export const APIQueryResultSchema = {
    properties: {
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total',
            description: 'The total number of records from the returned query'
        },
        nextSkip: {
            type: 'integer',
            minimum: 0,
            title: 'Nextskip',
            description: "The number of records to skip for the next 'page' of the query"
        },
        totalPages: {
            type: 'integer',
            minimum: 1,
            title: 'Totalpages',
            description: 'The number of pages of results from the query'
        },
        totalItems: {
            type: 'integer',
            minimum: 0,
            title: 'Totalitems',
            description: 'The total number of items returned in the query'
        }
    },
    type: 'object',
    required: ['total', 'nextSkip', 'totalPages', 'totalItems'],
    title: 'APIQueryResult',
    description: `reprents the pagination metadata for a query
to help the frontend`
} as const;

export const AuthFormSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username',
            description: 'The username of the user'
        },
        password: {
            type: 'string',
            title: 'Password',
            description: 'The password of the user'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password'],
    title: 'AuthForm',
    description: 'The base model for all app authentication forms'
} as const;

export const CreateUserFormSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username',
            description: 'The username of the user'
        },
        password: {
            type: 'string',
            title: 'Password',
            description: 'The password of the user'
        },
        role: {
            '$ref': '#/components/schemas/Role',
            description: 'The role of the user'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password', 'role'],
    title: 'CreateUserForm',
    description: 'form to create a user'
} as const;

export const EventLogReadSchema = {
    properties: {
        logLevel: {
            '$ref': '#/components/schemas/LogLevel'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['logLevel', 'message', 'timestamp'],
    title: 'EventLogRead',
    description: 'represents a event log returned from the API'
} as const;

export const GenericAPIResponseSchema = {
    properties: {
        data: {
            type: 'object',
            title: 'Data'
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'The message returned by the API'
        }
    },
    type: 'object',
    required: ['data', 'message'],
    title: 'GenericAPIResponse',
    description: 'Generic API response model'
} as const;

export const GuacamoleCreateFormSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Username',
            description: 'The username for the datasource'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password',
            description: 'The password for the datasource'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            description: 'Whether the datasource is enabled by default'
        },
        datasource: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Datasource',
            description: 'The name of the Guacamole datasource'
        },
        endpoint: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Endpoint',
            description: 'The URL for the Guacamole datasource'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password', 'enabled', 'datasource', 'endpoint'],
    title: 'GuacamoleCreateForm',
    description: 'The form for creating a new Guacamole datasource'
} as const;

export const GuacamoleReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        datasource: {
            type: 'string',
            title: 'Datasource',
            description: 'The name of the Guacamole datasource'
        },
        endpoint: {
            type: 'string',
            title: 'Endpoint',
            description: 'The URL for the Guacamole datasource'
        }
    },
    type: 'object',
    required: ['id', 'username', 'enabled', 'datasource', 'endpoint'],
    title: 'GuacamoleRead',
    description: 'A guacamole datasource schema from the DB'
} as const;

export const GuacamoleUpdateFormSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username',
            description: 'The username for the datasource'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password',
            description: 'The password for the Guacamole datasource'
        },
        datasource: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Datasource',
            description: 'The name of the Guacamole datasource'
        },
        endpoint: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endpoint',
            description: 'The URL for the Guacamole datasource'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username'],
    title: 'GuacamoleUpdateForm',
    description: 'The form for updating a Guacamole datasource'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LastLogsSchema = {
    properties: {
        lastCritical: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventLogRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        lastError: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventLogRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['lastCritical', 'lastError'],
    title: 'LastLogs',
    description: 'represents the most recent logs for the critical and error log levels'
} as const;

export const LogLevelSchema = {
    type: 'string',
    enum: ['INFO', 'WARNING', 'ERROR', 'CRITICAL'],
    title: 'LogLevel'
} as const;

export const LogLevelTotalsSchema = {
    properties: {
        info: {
            type: 'integer',
            title: 'Info'
        },
        warning: {
            type: 'integer',
            title: 'Warning'
        },
        error: {
            type: 'integer',
            title: 'Error'
        },
        critical: {
            type: 'integer',
            title: 'Critical'
        }
    },
    type: 'object',
    required: ['info', 'warning', 'error', 'critical'],
    title: 'LogLevelTotals',
    description: 'represents the total number of logs for each log level'
} as const;

export const LogMetaDataSchema = {
    properties: {
        totals: {
            '$ref': '#/components/schemas/LogLevelTotals',
            description: 'The total count of each log level'
        },
        previousLogs: {
            '$ref': '#/components/schemas/LastLogs',
            description: 'The last error and critical log metadata'
        }
    },
    type: 'object',
    required: ['totals', 'previousLogs'],
    title: 'LogMetaData',
    description: 'the event log meta data to display in a dashboard'
} as const;

export const LogQueryResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/EventLogRead'
            },
            type: 'array',
            title: 'Results',
            description: 'The results of the query of type SchemaT'
        },
        pageContext: {
            '$ref': '#/components/schemas/APIQueryResult',
            description: 'Metadata for the query results for the frontend to handle'
        }
    },
    type: 'object',
    required: ['results', 'pageContext'],
    title: 'LogQueryResponse',
    description: 'the logs returned from a query'
} as const;

export const OpenstackCreateFormSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Username',
            description: 'The username for the datasource'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password',
            description: 'The password for the datasource'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            description: 'Whether the datasource is enabled by default'
        },
        authUrl: {
            type: 'string',
            title: 'Authurl',
            description: 'The URL for the Openstack authentication'
        },
        projectId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectid',
            description: 'The project ID for the Openstack authentication'
        },
        projectName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectname',
            description: 'The project name for the Openstack authentication'
        },
        projectDomainName: {
            type: 'string',
            title: 'Projectdomainname',
            description: 'The project domain name for the Openstack authentication'
        },
        userDomainName: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Userdomainname',
            description: 'The user domain name for the Openstack authentication'
        },
        regionName: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Regionname',
            description: 'The region name for the Openstack authentication'
        },
        identityApiVersion: {
            type: 'string',
            maxLength: 3,
            minLength: 1,
            pattern: '^(2.0|3)$',
            title: 'Identityapiversion',
            description: 'The identity API version for the Openstack authentication'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password', 'enabled', 'authUrl', 'projectDomainName', 'userDomainName', 'regionName', 'identityApiVersion'],
    title: 'OpenstackCreateForm',
    description: 'The form for creating a new Openstack datasource'
} as const;

export const OpenstackReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        authUrl: {
            type: 'string',
            title: 'Authurl',
            description: 'The URL for the Openstack authentication'
        },
        projectId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectid',
            description: 'The project ID for the Openstack authentication'
        },
        projectName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectname',
            description: 'The project name for the Openstack authentication'
        },
        projectDomainName: {
            type: 'string',
            title: 'Projectdomainname',
            description: 'The project domain name for the Openstack authentication'
        },
        userDomainName: {
            type: 'string',
            title: 'Userdomainname',
            description: 'The user domain name for the Openstack authentication'
        },
        regionName: {
            type: 'string',
            title: 'Regionname',
            description: 'The region name for the Openstack authentication'
        },
        identityApiVersion: {
            type: 'string',
            title: 'Identityapiversion',
            description: 'The identity API version for the Openstack authentication'
        }
    },
    type: 'object',
    required: ['id', 'username', 'enabled', 'authUrl', 'projectDomainName', 'userDomainName', 'regionName', 'identityApiVersion'],
    title: 'OpenstackRead',
    description: 'A Openstack datasource schema from the DB'
} as const;

export const OpenstackUpdateFormSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username',
            description: 'The username for the datasource'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password',
            description: 'The password for the datasource'
        },
        authUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Authurl',
            description: 'The URL for the Openstack authentication'
        },
        projectId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectid',
            description: 'The project ID for the Openstack authentication'
        },
        projectName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectname',
            description: 'The project name for the Openstack authentication'
        },
        projectDomainName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectdomainname',
            description: 'The project domain name for the Openstack authentication'
        },
        userDomainName: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Userdomainname',
            description: 'The user domain name for the Openstack authentication'
        },
        regionName: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Regionname',
            description: 'The region name for the Openstack authentication'
        },
        identityApiVersion: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3,
                    minLength: 1,
                    pattern: '^(2.0|3)$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Identityapiversion',
            description: 'The identity API version for the Openstack authentication'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password', 'authUrl', 'projectDomainName', 'userDomainName', 'regionName', 'identityApiVersion'],
    title: 'OpenstackUpdateForm',
    description: 'The form for updating a Openstack datasource'
} as const;

export const RoleSchema = {
    type: 'string',
    enum: ['admin', 'user', 'read_only'],
    title: 'Role'
} as const;

export const SaltstackCreateFormSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Username',
            description: 'The username for the datasource'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password',
            description: 'The password for the datasource'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            description: 'Whether the datasource is enabled by default'
        },
        endpoint: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Endpoint',
            description: 'The endpoint for the Saltstack datasource'
        },
        hostname: {
            type: 'string',
            maxLength: 253,
            minLength: 1,
            title: 'Hostname',
            description: 'The hostname for the Saltstack datasource'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password', 'enabled', 'endpoint', 'hostname'],
    title: 'SaltstackCreateForm',
    description: 'The form for creating a new Saltstack datasource'
} as const;

export const SaltstackReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        endpoint: {
            type: 'string',
            title: 'Endpoint',
            description: 'The endpoint for the Saltstack datasource'
        },
        hostname: {
            type: 'string',
            title: 'Hostname',
            description: 'The hostname for the Saltstack datasource'
        }
    },
    type: 'object',
    required: ['id', 'username', 'enabled', 'endpoint', 'hostname'],
    title: 'SaltstackRead',
    description: 'A Saltstack datasource schema from the DB'
} as const;

export const SaltstackUpdateFormSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username',
            description: 'The username for the datasource'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password',
            description: 'The password for the datasource'
        },
        endpoint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endpoint',
            description: 'The endpoint for the Saltstack datasource'
        },
        hostname: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 253,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hostname',
            description: 'The endpoint for the Saltstack datasource'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['username', 'password'],
    title: 'SaltstackUpdateForm',
    description: 'The form for updating a Saltstack datasource'
} as const;

export const UpdateUserFormSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Role'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'UpdateUserForm',
    description: 'form to update a user'
} as const;

export const UserDetailsResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'ID',
            description: 'The ID of the user'
        },
        username: {
            type: 'string',
            title: 'Username',
            description: 'The username of the user'
        },
        role: {
            '$ref': '#/components/schemas/Role',
            description: 'The role of the user'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat',
            description: 'The date the user was created'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat',
            description: 'The date the user was last updated'
        }
    },
    type: 'object',
    required: ['id', 'username', 'role', 'createdAt', 'updatedAt'],
    title: 'UserDetailsResponse',
    description: 'The response model for the user; provides all the information'
} as const;

export const UserResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'ID',
            description: 'The ID of the user'
        },
        username: {
            type: 'string',
            title: 'Username',
            description: 'The username of the user'
        },
        role: {
            '$ref': '#/components/schemas/Role',
            description: 'The role of the user'
        }
    },
    type: 'object',
    required: ['id', 'username', 'role'],
    title: 'UserResponse',
    description: 'The response model for the user; only provides the essential information'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__datasources__router_setup__datasource_router___locals___ProtectedRead__1Schema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        datasource: {
            type: 'string',
            title: 'Datasource',
            description: 'The name of the Guacamole datasource'
        },
        endpoint: {
            type: 'string',
            title: 'Endpoint',
            description: 'The URL for the Guacamole datasource'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['id', 'username', 'enabled', 'datasource', 'endpoint', 'password'],
    title: 'GuacamoleProtectedRead'
} as const;

export const app__datasources__router_setup__datasource_router___locals___ProtectedRead__2Schema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        authUrl: {
            type: 'string',
            title: 'Authurl',
            description: 'The URL for the Openstack authentication'
        },
        projectId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectid',
            description: 'The project ID for the Openstack authentication'
        },
        projectName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectname',
            description: 'The project name for the Openstack authentication'
        },
        projectDomainName: {
            type: 'string',
            title: 'Projectdomainname',
            description: 'The project domain name for the Openstack authentication'
        },
        userDomainName: {
            type: 'string',
            title: 'Userdomainname',
            description: 'The user domain name for the Openstack authentication'
        },
        regionName: {
            type: 'string',
            title: 'Regionname',
            description: 'The region name for the Openstack authentication'
        },
        identityApiVersion: {
            type: 'string',
            title: 'Identityapiversion',
            description: 'The identity API version for the Openstack authentication'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['id', 'username', 'enabled', 'authUrl', 'projectDomainName', 'userDomainName', 'regionName', 'identityApiVersion', 'password'],
    title: 'OpenstackProtectedRead'
} as const;

export const app__datasources__router_setup__datasource_router___locals___ProtectedRead__3Schema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        endpoint: {
            type: 'string',
            title: 'Endpoint',
            description: 'The endpoint for the Saltstack datasource'
        },
        hostname: {
            type: 'string',
            title: 'Hostname',
            description: 'The hostname for the Saltstack datasource'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['id', 'username', 'enabled', 'endpoint', 'hostname', 'password'],
    title: 'SaltstackProtectedRead'
} as const;