// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-axios';
import type { LoginData, LoginError, LogoutData, CurrentUserData, CurrentUserResponse, GetAllUsersData, GetAllUsersResponse, CreateUserData, CreateUserResponse, CreateUserError, AllUserDetailsData, AllUserDetailsResponse, UserDetailsData, UserDetailsResponse2, UserDetailsError, DeleteUserData, DeleteUserResponse, DeleteUserError, ReadUserData, ReadUserResponse, ReadUserError, UpdateUserData, UpdateUserResponse, UpdateUserError, SummaryData, SummaryResponse, SearchData, SearchResponse, SearchError, LogsFromTodayData, LogsFromTodayResponse, LogsFromTodayError, GetAllDatasourcesData, GetAllDatasourcesResponse, CreateDatasourceData, CreateDatasourceResponse, CreateDatasourceError, ProtectedReadData, ProtectedReadResponse, ProtectedReadError, DeleteDatasourceData, DeleteDatasourceError, ReadDatasourceData, ReadDatasourceResponse, ReadDatasourceError, UpdateDatasourceData, UpdateDatasourceResponse, UpdateDatasourceError, ToggleDatasourceData, ToggleDatasourceResponse, ToggleDatasourceError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 * Checks the credentials provided by the 'AuthForm'
 * and in the response sets a cookie with the session id when given
 * valid login credentials.
 *
 * Arguments:
 * auth_form {AuthForm} -- Has types to enforce constraints on the request body
 * client {RequireClientIdentity} -- The client identity
 * user_service {UserController} -- The user controller
 * Raises:
 * HTTPUnauthorized: 401 - If the user is not authenticated
 * Returns:
 * Response
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, LoginError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/auth/login/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Logout
 * Logs out the user using the _"api_key" dependency_
 *
 * - Load the clients signed api key from the clients cookies
 * - Decrypts the api key in the Redis store,
 *
 * - if the key hasn't been tampered with by the user and is valid the
 * session is revoked by deleting the key in the Redis store mapped to the api key
 * and the cookie is removed from the client
 *
 *
 * Arguments:
 * request {Request}  - the request to get the existing session ID from
 * Raises:
 * If the api_key is not found or was tampered with
 * by the client
 * Returns:
 * JSONResponse -- a message indicating the logout was successful
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
        url: '/auth/logout',
        ...options
    });
};

/**
 * Current User
 * Reads the current user
 *
 * Arguments:
 * reader {CurrentUser} -- the reader
 *
 * Returns:
 * UserResponse -- the current user
 */
export const currentUser = <ThrowOnError extends boolean = false>(options?: Options<CurrentUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CurrentUserResponse, unknown, ThrowOnError>({
        url: '/users/me/',
        ...options
    });
};

/**
 * Get All Users
 * reads all users based on the role of the reader (no read up)
 * Arguments:
 * user_service {UserController} -- _the user controller_
 * reader {CurrentUser} -- _the reader_
 *
 * Returns:
 * list[UserResponse] -- _description_
 */
export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllUsersResponse, unknown, ThrowOnError>({
        url: '/users/',
        ...options
    });
};

/**
 * Create User
 * **[ADMIN]**
 * Creates a user given valid form data and inserts
 * the created user into the database and returns the
 * created user
 *
 * _Arguments_:
 * - create_schema {CreateUserForm} -- the form data
 * - db {AsyncSession} - the database session
 * _Raises_:
 * HTTPException: 400 - Username is already taken
 * _Returns_:
 * UserResponse -- the created user
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateUserResponse, CreateUserError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/users/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * All User Details
 * Admin protected route to read all of the user details, including
 * the creation date and last updated timestamps
 *
 * Arguments:
 * db {requires_db}
 *
 * Returns:
 * list[UserDetailsResponse]
 */
export const allUserDetails = <ThrowOnError extends boolean = false>(options?: Options<AllUserDetailsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AllUserDetailsResponse, unknown, ThrowOnError>({
        url: '/users/details',
        ...options
    });
};

/**
 * User Details
 * reads the details of an individual user
 *
 * Arguments:
 * user_id {int} -- the id of the user to read
 * db {DatabaseRequired} -- the database session
 *
 * Raises:
 * HTTPNotFound: the user does not exist
 *
 * Returns:
 * UserDetailsResponse -- the details of the individual user
 */
export const userDetails = <ThrowOnError extends boolean = false>(options: Options<UserDetailsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UserDetailsResponse2, UserDetailsError, ThrowOnError>({
        url: '/users/details/{user_id}/',
        ...options
    });
};

/**
 * Delete User
 * Deletes a user given an existing user ID
 *
 * Arguments:
 * user_id {int} -- the ID of the user to be deleted
 * db {requires_db} -- a database session
 * admin {admin_required} -- an admin user, ensures the Admin isn't deleting
 * themselves
 * Returns:
 * ResponseMessage -- A message indicating the deletion was successful
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteUserResponse, DeleteUserError, ThrowOnError>({
        url: '/users/{user_id}/',
        ...options
    });
};

/**
 * Read User
 * Reads a user with 'no read up' i.e a user cannot read a user with a
 * higher role / permission
 *
 * Arguments:
 * user_id {int} -- the id of the user to read
 * db {requires_db} -- the database session
 * reader {role_required} -- the "reader" or user making the request
 *
 * Raises:
 * HTTPNotFound: The user does not exist
 * HTTPForbidden: The user does not have permission to read the user
 *
 * Returns:
 * UserResponse -- The user attempting to be read
 */
export const readUser = <ThrowOnError extends boolean = false>(options: Options<ReadUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadUserResponse, ReadUserError, ThrowOnError>({
        url: '/users/{user_id}/',
        ...options
    });
};

/**
 * Update User
 * updates the user given an id and uses the schema to update the user's data
 *
 * Arguments:
 * user_id {int} -- user id of the user to update
 * update_schema {UpdateUser} -- the request body schema
 * db {AsyncSession} -- the database session
 * Returns:
 * UserResponse -- the updated user
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateUserResponse, UpdateUserError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/users/{user_id}/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Summary
 * returns a summary of recent event logs
 * Arguments:
 * log_service {LogController}
 * Returns:
 * LogMetaData
 */
export const summary = <ThrowOnError extends boolean = false>(options?: Options<SummaryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<SummaryResponse, unknown, ThrowOnError>({
        url: '/logs/summary/',
        ...options
    });
};

/**
 * Search
 * Searches the logs based on the query parameters
 * Arguments:
 * query_params {Annotated[LogQueryParams, Query} -- the query params
 * log_service {LogController} -- the log service dep
 * Raises:
 * HTTPNotFound: if no logs are found matching the query parameters
 * Returns:
 * LogQueryResponse -- the logs that match the query parameters
 */
export const search = <ThrowOnError extends boolean = false>(options?: Options<SearchData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<SearchResponse, SearchError, ThrowOnError>({
        url: '/logs/search/',
        ...options
    });
};

/**
 * Logs From Today
 * Given a query filter, returns the logs from today that match the filter
 *
 * Arguments:
 * query_filter {Annotated[LogQueryParams, Query} the query params
 * log_service {LogController} -- the log service dep
 *
 * Raises:
 * HTTPNotFound: if no logs are found matching the query parameters
 *
 * Returns:
 * LogQueryResponse -- the logs that match the query parameters
 */
export const logsFromToday = <ThrowOnError extends boolean = false>(options?: Options<LogsFromTodayData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<LogsFromTodayResponse, LogsFromTodayError, ThrowOnError>({
        url: '/logs/today/',
        ...options
    });
};

/**
 * Get All Datasources
 * gets all of the given datasource in the database
 *
 * Arguments:
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if no datasources are found
 *
 * Returns:
 * List[read_schema] -- a list of the datasources from the database
 */
export const getAllDatasources = <ThrowOnError extends boolean = false>(options?: Options<GetAllDatasourcesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllDatasourcesResponse, unknown, ThrowOnError>({
        url: '/datasources/guacamole/',
        ...options
    });
};

/**
 * Create Datasource
 */
export const createDatasource = <ThrowOnError extends boolean = false>(options: Options<CreateDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateDatasourceResponse, CreateDatasourceError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/datasources/guacamole/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Protected Read
 */
export const protectedRead = <ThrowOnError extends boolean = false>(options: Options<ProtectedReadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ProtectedReadResponse, ProtectedReadError, ThrowOnError>({
        url: '/datasources/guacamole/protected/{datasource_id}/',
        ...options
    });
};

/**
 * Delete Datasource
 * deletes a datasource given it's ID
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to delete
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if not found
 */
export const deleteDatasource = <ThrowOnError extends boolean = false>(options: Options<DeleteDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, DeleteDatasourceError, ThrowOnError>({
        url: '/datasources/guacamole/{datasource_id}/',
        ...options
    });
};

/**
 * Read Datasource
 */
export const readDatasource = <ThrowOnError extends boolean = false>(options: Options<ReadDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadDatasourceResponse, ReadDatasourceError, ThrowOnError>({
        url: '/datasources/guacamole/{datasource_id}/',
        ...options
    });
};

/**
 * Update Datasource
 * given an updated schema for a data source
 * it updates the datasource in the database
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to updated
 * update_ds_schema {update_schema} -- a given datasources update schema
 *
 * Raises:
 * HTTPNotFound: if the datasource is not found
 *
 * Returns:
 * read_schema -- a pydantic repr of the updated datasource
 */
export const updateDatasource = <ThrowOnError extends boolean = false>(options: Options<UpdateDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateDatasourceResponse, UpdateDatasourceError, ThrowOnError>({
        url: '/datasources/guacamole/{datasource_id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Toggle Datasource
 * toggles a datasource on provided an ID. It toggles the other
 * enabled datasource off
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to enable
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * DataSourceToggleError: if the datasource is already enabled
 * DataSourceNotFound: if the datasource is not found
 * Returns:
 * GenericAPIResponse -- a message indicating the success of the operation
 */
export const toggleDatasource = <ThrowOnError extends boolean = false>(options: Options<ToggleDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ToggleDatasourceResponse, ToggleDatasourceError, ThrowOnError>({
        url: '/datasources/guacamole/{datasource_id}/',
        ...options
    });
};

/**
 * Get All Datasources
 * gets all of the given datasource in the database
 *
 * Arguments:
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if no datasources are found
 *
 * Returns:
 * List[read_schema] -- a list of the datasources from the database
 */
export const getAllDatasources = <ThrowOnError extends boolean = false>(options?: Options<GetAllDatasourcesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllDatasourcesResponse, unknown, ThrowOnError>({
        url: '/datasources/openstack/',
        ...options
    });
};

/**
 * Create Datasource
 */
export const createDatasource = <ThrowOnError extends boolean = false>(options: Options<CreateDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateDatasourceResponse, CreateDatasourceError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/datasources/openstack/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Protected Read
 */
export const protectedRead = <ThrowOnError extends boolean = false>(options: Options<ProtectedReadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ProtectedReadResponse, ProtectedReadError, ThrowOnError>({
        url: '/datasources/openstack/protected/{datasource_id}/',
        ...options
    });
};

/**
 * Delete Datasource
 * deletes a datasource given it's ID
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to delete
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if not found
 */
export const deleteDatasource = <ThrowOnError extends boolean = false>(options: Options<DeleteDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, DeleteDatasourceError, ThrowOnError>({
        url: '/datasources/openstack/{datasource_id}/',
        ...options
    });
};

/**
 * Read Datasource
 */
export const readDatasource = <ThrowOnError extends boolean = false>(options: Options<ReadDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadDatasourceResponse, ReadDatasourceError, ThrowOnError>({
        url: '/datasources/openstack/{datasource_id}/',
        ...options
    });
};

/**
 * Update Datasource
 * given an updated schema for a data source
 * it updates the datasource in the database
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to updated
 * update_ds_schema {update_schema} -- a given datasources update schema
 *
 * Raises:
 * HTTPNotFound: if the datasource is not found
 *
 * Returns:
 * read_schema -- a pydantic repr of the updated datasource
 */
export const updateDatasource = <ThrowOnError extends boolean = false>(options: Options<UpdateDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateDatasourceResponse, UpdateDatasourceError, ThrowOnError>({
        url: '/datasources/openstack/{datasource_id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Toggle Datasource
 * toggles a datasource on provided an ID. It toggles the other
 * enabled datasource off
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to enable
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * DataSourceToggleError: if the datasource is already enabled
 * DataSourceNotFound: if the datasource is not found
 * Returns:
 * GenericAPIResponse -- a message indicating the success of the operation
 */
export const toggleDatasource = <ThrowOnError extends boolean = false>(options: Options<ToggleDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ToggleDatasourceResponse, ToggleDatasourceError, ThrowOnError>({
        url: '/datasources/openstack/{datasource_id}/',
        ...options
    });
};

/**
 * Get All Datasources
 * gets all of the given datasource in the database
 *
 * Arguments:
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if no datasources are found
 *
 * Returns:
 * List[read_schema] -- a list of the datasources from the database
 */
export const getAllDatasources = <ThrowOnError extends boolean = false>(options?: Options<GetAllDatasourcesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllDatasourcesResponse, unknown, ThrowOnError>({
        url: '/datasources/saltstack/',
        ...options
    });
};

/**
 * Create Datasource
 */
export const createDatasource = <ThrowOnError extends boolean = false>(options: Options<CreateDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateDatasourceResponse, CreateDatasourceError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/datasources/saltstack/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Protected Read
 */
export const protectedRead = <ThrowOnError extends boolean = false>(options: Options<ProtectedReadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ProtectedReadResponse, ProtectedReadError, ThrowOnError>({
        url: '/datasources/saltstack/protected/{datasource_id}/',
        ...options
    });
};

/**
 * Delete Datasource
 * deletes a datasource given it's ID
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to delete
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if not found
 */
export const deleteDatasource = <ThrowOnError extends boolean = false>(options: Options<DeleteDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, DeleteDatasourceError, ThrowOnError>({
        url: '/datasources/saltstack/{datasource_id}/',
        ...options
    });
};

/**
 * Read Datasource
 */
export const readDatasource = <ThrowOnError extends boolean = false>(options: Options<ReadDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadDatasourceResponse, ReadDatasourceError, ThrowOnError>({
        url: '/datasources/saltstack/{datasource_id}/',
        ...options
    });
};

/**
 * Update Datasource
 * given an updated schema for a data source
 * it updates the datasource in the database
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to updated
 * update_ds_schema {update_schema} -- a given datasources update schema
 *
 * Raises:
 * HTTPNotFound: if the datasource is not found
 *
 * Returns:
 * read_schema -- a pydantic repr of the updated datasource
 */
export const updateDatasource = <ThrowOnError extends boolean = false>(options: Options<UpdateDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateDatasourceResponse, UpdateDatasourceError, ThrowOnError>({
        url: '/datasources/saltstack/{datasource_id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Toggle Datasource
 * toggles a datasource on provided an ID. It toggles the other
 * enabled datasource off
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to enable
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * DataSourceToggleError: if the datasource is already enabled
 * DataSourceNotFound: if the datasource is not found
 * Returns:
 * GenericAPIResponse -- a message indicating the success of the operation
 */
export const toggleDatasource = <ThrowOnError extends boolean = false>(options: Options<ToggleDatasourceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ToggleDatasourceResponse, ToggleDatasourceError, ThrowOnError>({
        url: '/datasources/saltstack/{datasource_id}/',
        ...options
    });
};