// This file is auto-generated by @hey-api/openapi-ts

import {
	type Options as ClientOptions,
	type TDataShape,
	type Client,
	urlSearchParamsBodySerializer,
} from "@hey-api/client-axios";
import type {
	AuthLoginData,
	AuthLoginError,
	AuthLogoutData,
	UserCurrentUserData,
	UserCurrentUserResponse,
	UserGetAllUsersData,
	UserGetAllUsersResponse,
	UserCreateUserData,
	UserCreateUserResponse,
	UserCreateUserError,
	UserAllUserDetailsData,
	UserAllUserDetailsResponse,
	UserUserDetailsData,
	UserUserDetailsResponse,
	UserUserDetailsError,
	UserDeleteUserData,
	UserDeleteUserResponse,
	UserDeleteUserError,
	UserReadUserData,
	UserReadUserResponse,
	UserReadUserError,
	UserUpdateUserData,
	UserUpdateUserResponse,
	UserUpdateUserError,
	EventLogsSummaryData,
	EventLogsSummaryResponse,
	EventLogsSearchData,
	EventLogsSearchResponse,
	EventLogsSearchError,
	EventLogsLogsFromTodayData,
	EventLogsLogsFromTodayResponse,
	EventLogsLogsFromTodayError,
	GuacGetAllDatasourcesData,
	GuacGetAllDatasourcesResponse,
	GuacCreateDatasourceData,
	GuacCreateDatasourceResponse,
	GuacCreateDatasourceError,
	GuacProtectedReadData,
	GuacProtectedReadResponse,
	GuacProtectedReadError,
	GuacDeleteDatasourceData,
	GuacDeleteDatasourceError,
	GuacReadDatasourceData,
	GuacReadDatasourceResponse,
	GuacReadDatasourceError,
	GuacUpdateDatasourceData,
	GuacUpdateDatasourceResponse,
	GuacUpdateDatasourceError,
	GuacToggleDatasourceData,
	GuacToggleDatasourceResponse,
	GuacToggleDatasourceError,
	OpenstackGetAllDatasourcesData,
	OpenstackGetAllDatasourcesResponse,
	OpenstackCreateDatasourceData,
	OpenstackCreateDatasourceResponse,
	OpenstackCreateDatasourceError,
	OpenstackProtectedReadData,
	OpenstackProtectedReadResponse,
	OpenstackProtectedReadError,
	OpenstackDeleteDatasourceData,
	OpenstackDeleteDatasourceError,
	OpenstackReadDatasourceData,
	OpenstackReadDatasourceResponse,
	OpenstackReadDatasourceError,
	OpenstackUpdateDatasourceData,
	OpenstackUpdateDatasourceResponse,
	OpenstackUpdateDatasourceError,
	OpenstackToggleDatasourceData,
	OpenstackToggleDatasourceResponse,
	OpenstackToggleDatasourceError,
	SaltstackGetAllDatasourcesData,
	SaltstackGetAllDatasourcesResponse,
	SaltstackCreateDatasourceData,
	SaltstackCreateDatasourceResponse,
	SaltstackCreateDatasourceError,
	SaltstackProtectedReadData,
	SaltstackProtectedReadResponse,
	SaltstackProtectedReadError,
	SaltstackDeleteDatasourceData,
	SaltstackDeleteDatasourceError,
	SaltstackReadDatasourceData,
	SaltstackReadDatasourceResponse,
	SaltstackReadDatasourceError,
	SaltstackUpdateDatasourceData,
	SaltstackUpdateDatasourceResponse,
	SaltstackUpdateDatasourceError,
	SaltstackToggleDatasourceData,
	SaltstackToggleDatasourceResponse,
	SaltstackToggleDatasourceError,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Login
 * Checks the credentials provided by the 'AuthForm'
 * and in the response sets a cookie with the session id when given
 * valid login credentials.
 *
 * Arguments:
 * auth_form {AuthForm} -- Has types to enforce constraints on the request body
 * client {RequireClientIdentity} -- The client identity
 * user_service {UserController} -- The user controller
 * Raises:
 * HTTPUnauthorized: 401 - If the user is not authenticated
 * Returns:
 * Response
 */
export const authLogin = <ThrowOnError extends boolean = false>(
	options: Options<AuthLoginData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		unknown,
		AuthLoginError,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/auth/login/",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};

/**
 * Logout
 * Logs out the user using the _"api_key" dependency_
 *
 * - Load the clients signed api key from the clients cookies
 * - Decrypts the api key in the Redis store,
 *
 * - if the key hasn't been tampered with by the user and is valid the
 * session is revoked by deleting the key in the Redis store mapped to the api key
 * and the cookie is removed from the client
 *
 *
 * Arguments:
 * request {Request}  - the request to get the existing session ID from
 * Raises:
 * If the api_key is not found or was tampered with
 * by the client
 * Returns:
 * JSONResponse -- a message indicating the logout was successful
 */
export const authLogout = <ThrowOnError extends boolean = false>(
	options?: Options<AuthLogoutData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).post<
		unknown,
		unknown,
		ThrowOnError
	>({
		url: "/auth/logout",
		...options,
	});
};

/**
 * Current User
 * Reads the current user
 *
 * Arguments:
 * reader {CurrentUser} -- the reader
 *
 * Returns:
 * UserResponse -- the current user
 */
export const userCurrentUser = <ThrowOnError extends boolean = false>(
	options?: Options<UserCurrentUserData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		UserCurrentUserResponse,
		unknown,
		ThrowOnError
	>({
		url: "/users/me/",
		...options,
	});
};

/**
 * Get All Users
 * reads all users based on the role of the reader (no read up)
 * Arguments:
 * user_service {UserController} -- _the user controller_
 * reader {CurrentUser} -- _the reader_
 *
 * Returns:
 * list[UserResponse] -- _description_
 */
export const userGetAllUsers = <ThrowOnError extends boolean = false>(
	options?: Options<UserGetAllUsersData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		UserGetAllUsersResponse,
		unknown,
		ThrowOnError
	>({
		url: "/users/",
		...options,
	});
};

/**
 * Create User
 * **[ADMIN]**
 * Creates a user given valid form data and inserts
 * the created user into the database and returns the
 * created user
 *
 * _Arguments_:
 * - create_schema {CreateUserForm} -- the form data
 * - db {AsyncSession} - the database session
 * _Raises_:
 * HTTPException: 400 - Username is already taken
 * _Returns_:
 * UserResponse -- the created user
 */
export const userCreateUser = <ThrowOnError extends boolean = false>(
	options: Options<UserCreateUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		UserCreateUserResponse,
		UserCreateUserError,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/users/",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};

/**
 * All User Details
 * Admin protected route to read all of the user details, including
 * the creation date and last updated timestamps
 *
 * Arguments:
 * db {requires_db}
 *
 * Returns:
 * list[UserDetailsResponse]
 */
export const userAllUserDetails = <ThrowOnError extends boolean = false>(
	options?: Options<UserAllUserDetailsData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		UserAllUserDetailsResponse,
		unknown,
		ThrowOnError
	>({
		url: "/users/details",
		...options,
	});
};

/**
 * User Details
 * reads the details of an individual user
 *
 * Arguments:
 * user_id {int} -- the id of the user to read
 * db {DatabaseRequired} -- the database session
 *
 * Raises:
 * HTTPNotFound: the user does not exist
 *
 * Returns:
 * UserDetailsResponse -- the details of the individual user
 */
export const userUserDetails = <ThrowOnError extends boolean = false>(
	options: Options<UserUserDetailsData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		UserUserDetailsResponse,
		UserUserDetailsError,
		ThrowOnError
	>({
		url: "/users/details/{user_id}/",
		...options,
	});
};

/**
 * Delete User
 * Deletes a user given an existing user ID
 *
 * Arguments:
 * user_id {int} -- the ID of the user to be deleted
 * db {requires_db} -- a database session
 * admin {admin_required} -- an admin user, ensures the Admin isn't deleting
 * themselves
 * Returns:
 * ResponseMessage -- A message indicating the deletion was successful
 */
export const userDeleteUser = <ThrowOnError extends boolean = false>(
	options: Options<UserDeleteUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		UserDeleteUserResponse,
		UserDeleteUserError,
		ThrowOnError
	>({
		url: "/users/{user_id}/",
		...options,
	});
};

/**
 * Read User
 * Reads a user with 'no read up' i.e a user cannot read a user with a
 * higher role / permission
 *
 * Arguments:
 * user_id {int} -- the id of the user to read
 * db {requires_db} -- the database session
 * reader {role_required} -- the "reader" or user making the request
 *
 * Raises:
 * HTTPNotFound: The user does not exist
 * HTTPForbidden: The user does not have permission to read the user
 *
 * Returns:
 * UserResponse -- The user attempting to be read
 */
export const userReadUser = <ThrowOnError extends boolean = false>(
	options: Options<UserReadUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		UserReadUserResponse,
		UserReadUserError,
		ThrowOnError
	>({
		url: "/users/{user_id}/",
		...options,
	});
};

/**
 * Update User
 * updates the user given an id and uses the schema to update the user's data
 *
 * Arguments:
 * user_id {int} -- user id of the user to update
 * update_schema {UpdateUser} -- the request body schema
 * db {AsyncSession} -- the database session
 * Returns:
 * UserResponse -- the updated user
 */
export const userUpdateUser = <ThrowOnError extends boolean = false>(
	options: Options<UserUpdateUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		UserUpdateUserResponse,
		UserUpdateUserError,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/users/{user_id}/",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};

/**
 * Summary
 * returns a summary of recent event logs
 * Arguments:
 * log_service {LogController}
 * Returns:
 * LogMetaData
 */
export const eventLogsSummary = <ThrowOnError extends boolean = false>(
	options?: Options<EventLogsSummaryData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		EventLogsSummaryResponse,
		unknown,
		ThrowOnError
	>({
		url: "/logs/summary/",
		...options,
	});
};

/**
 * Search
 * Searches the logs based on the query parameters
 * Arguments:
 * query_params {Annotated[LogQueryParams, Query} -- the query params
 * log_service {LogController} -- the log service dep
 * Raises:
 * HTTPNotFound: if no logs are found matching the query parameters
 * Returns:
 * LogQueryResponse -- the logs that match the query parameters
 */
export const eventLogsSearch = <ThrowOnError extends boolean = false>(
	options?: Options<EventLogsSearchData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		EventLogsSearchResponse,
		EventLogsSearchError,
		ThrowOnError
	>({
		url: "/logs/search/",
		...options,
	});
};

/**
 * Logs From Today
 * Given a query filter, returns the logs from today that match the filter
 *
 * Arguments:
 * query_filter {Annotated[LogQueryParams, Query} the query params
 * log_service {LogController} -- the log service dep
 *
 * Raises:
 * HTTPNotFound: if no logs are found matching the query parameters
 *
 * Returns:
 * LogQueryResponse -- the logs that match the query parameters
 */
export const eventLogsLogsFromToday = <ThrowOnError extends boolean = false>(
	options?: Options<EventLogsLogsFromTodayData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		EventLogsLogsFromTodayResponse,
		EventLogsLogsFromTodayError,
		ThrowOnError
	>({
		url: "/logs/today/",
		...options,
	});
};

/**
 * Get All Datasources
 * gets all of the given datasource in the database
 *
 * Arguments:
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if no datasources are found
 *
 * Returns:
 * List[read_schema] -- a list of the datasources from the database
 */
export const guacGetAllDatasources = <ThrowOnError extends boolean = false>(
	options?: Options<GuacGetAllDatasourcesData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GuacGetAllDatasourcesResponse,
		unknown,
		ThrowOnError
	>({
		url: "/datasources/guacamole/",
		...options,
	});
};

/**
 * Create Datasource
 */
export const guacCreateDatasource = <ThrowOnError extends boolean = false>(
	options: Options<GuacCreateDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		GuacCreateDatasourceResponse,
		GuacCreateDatasourceError,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/datasources/guacamole/",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};

/**
 * Protected Read
 */
export const guacProtectedRead = <ThrowOnError extends boolean = false>(
	options: Options<GuacProtectedReadData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GuacProtectedReadResponse,
		GuacProtectedReadError,
		ThrowOnError
	>({
		url: "/datasources/guacamole/protected/{datasource_id}/",
		...options,
	});
};

/**
 * Delete Datasource
 * deletes a datasource given it's ID
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to delete
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if not found
 */
export const guacDeleteDatasource = <ThrowOnError extends boolean = false>(
	options: Options<GuacDeleteDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		unknown,
		GuacDeleteDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/guacamole/{datasource_id}/",
		...options,
	});
};

/**
 * Read Datasource
 */
export const guacReadDatasource = <ThrowOnError extends boolean = false>(
	options: Options<GuacReadDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GuacReadDatasourceResponse,
		GuacReadDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/guacamole/{datasource_id}/",
		...options,
	});
};

/**
 * Update Datasource
 * given an updated schema for a data source
 * it updates the datasource in the database
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to updated
 * update_ds_schema {update_schema} -- a given datasources update schema
 *
 * Raises:
 * HTTPNotFound: if the datasource is not found
 *
 * Returns:
 * read_schema -- a pydantic repr of the updated datasource
 */
export const guacUpdateDatasource = <ThrowOnError extends boolean = false>(
	options: Options<GuacUpdateDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		GuacUpdateDatasourceResponse,
		GuacUpdateDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/guacamole/{datasource_id}/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Toggle Datasource
 * toggles a datasource on provided an ID. It toggles the other
 * enabled datasource off
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to enable
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * DataSourceToggleError: if the datasource is already enabled
 * DataSourceNotFound: if the datasource is not found
 * Returns:
 * GenericAPIResponse -- a message indicating the success of the operation
 */
export const guacToggleDatasource = <ThrowOnError extends boolean = false>(
	options: Options<GuacToggleDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		GuacToggleDatasourceResponse,
		GuacToggleDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/guacamole/{datasource_id}/",
		...options,
	});
};

/**
 * Get All Datasources
 * gets all of the given datasource in the database
 *
 * Arguments:
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if no datasources are found
 *
 * Returns:
 * List[read_schema] -- a list of the datasources from the database
 */
export const openstackGetAllDatasources = <
	ThrowOnError extends boolean = false
>(
	options?: Options<OpenstackGetAllDatasourcesData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		OpenstackGetAllDatasourcesResponse,
		unknown,
		ThrowOnError
	>({
		url: "/datasources/openstack/",
		...options,
	});
};

/**
 * Create Datasource
 */
export const openstackCreateDatasource = <ThrowOnError extends boolean = false>(
	options: Options<OpenstackCreateDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		OpenstackCreateDatasourceResponse,
		OpenstackCreateDatasourceError,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/datasources/openstack/",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};

/**
 * Protected Read
 */
export const openstackProtectedRead = <ThrowOnError extends boolean = false>(
	options: Options<OpenstackProtectedReadData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		OpenstackProtectedReadResponse,
		OpenstackProtectedReadError,
		ThrowOnError
	>({
		url: "/datasources/openstack/protected/{datasource_id}/",
		...options,
	});
};

/**
 * Delete Datasource
 * deletes a datasource given it's ID
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to delete
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if not found
 */
export const openstackDeleteDatasource = <ThrowOnError extends boolean = false>(
	options: Options<OpenstackDeleteDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		unknown,
		OpenstackDeleteDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/openstack/{datasource_id}/",
		...options,
	});
};

/**
 * Read Datasource
 */
export const openstackReadDatasource = <ThrowOnError extends boolean = false>(
	options: Options<OpenstackReadDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		OpenstackReadDatasourceResponse,
		OpenstackReadDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/openstack/{datasource_id}/",
		...options,
	});
};

/**
 * Update Datasource
 * given an updated schema for a data source
 * it updates the datasource in the database
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to updated
 * update_ds_schema {update_schema} -- a given datasources update schema
 *
 * Raises:
 * HTTPNotFound: if the datasource is not found
 *
 * Returns:
 * read_schema -- a pydantic repr of the updated datasource
 */
export const openstackUpdateDatasource = <ThrowOnError extends boolean = false>(
	options: Options<OpenstackUpdateDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		OpenstackUpdateDatasourceResponse,
		OpenstackUpdateDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/openstack/{datasource_id}/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Toggle Datasource
 * toggles a datasource on provided an ID. It toggles the other
 * enabled datasource off
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to enable
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * DataSourceToggleError: if the datasource is already enabled
 * DataSourceNotFound: if the datasource is not found
 * Returns:
 * GenericAPIResponse -- a message indicating the success of the operation
 */
export const openstackToggleDatasource = <ThrowOnError extends boolean = false>(
	options: Options<OpenstackToggleDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		OpenstackToggleDatasourceResponse,
		OpenstackToggleDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/openstack/{datasource_id}/",
		...options,
	});
};

/**
 * Get All Datasources
 * gets all of the given datasource in the database
 *
 * Arguments:
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if no datasources are found
 *
 * Returns:
 * List[read_schema] -- a list of the datasources from the database
 */
export const saltstackGetAllDatasources = <
	ThrowOnError extends boolean = false
>(
	options?: Options<SaltstackGetAllDatasourcesData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		SaltstackGetAllDatasourcesResponse,
		unknown,
		ThrowOnError
	>({
		url: "/datasources/saltstack/",
		...options,
	});
};

/**
 * Create Datasource
 */
export const saltstackCreateDatasource = <ThrowOnError extends boolean = false>(
	options: Options<SaltstackCreateDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		SaltstackCreateDatasourceResponse,
		SaltstackCreateDatasourceError,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/datasources/saltstack/",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};

/**
 * Protected Read
 */
export const saltstackProtectedRead = <ThrowOnError extends boolean = false>(
	options: Options<SaltstackProtectedReadData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		SaltstackProtectedReadResponse,
		SaltstackProtectedReadError,
		ThrowOnError
	>({
		url: "/datasources/saltstack/protected/{datasource_id}/",
		...options,
	});
};

/**
 * Delete Datasource
 * deletes a datasource given it's ID
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to delete
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * HTTPNotFound: if not found
 */
export const saltstackDeleteDatasource = <ThrowOnError extends boolean = false>(
	options: Options<SaltstackDeleteDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		unknown,
		SaltstackDeleteDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/saltstack/{datasource_id}/",
		...options,
	});
};

/**
 * Read Datasource
 */
export const saltstackReadDatasource = <ThrowOnError extends boolean = false>(
	options: Options<SaltstackReadDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		SaltstackReadDatasourceResponse,
		SaltstackReadDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/saltstack/{datasource_id}/",
		...options,
	});
};

/**
 * Update Datasource
 * given an updated schema for a data source
 * it updates the datasource in the database
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to updated
 * update_ds_schema {update_schema} -- a given datasources update schema
 *
 * Raises:
 * HTTPNotFound: if the datasource is not found
 *
 * Returns:
 * read_schema -- a pydantic repr of the updated datasource
 */
export const saltstackUpdateDatasource = <ThrowOnError extends boolean = false>(
	options: Options<SaltstackUpdateDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		SaltstackUpdateDatasourceResponse,
		SaltstackUpdateDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/saltstack/{datasource_id}/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Toggle Datasource
 * toggles a datasource on provided an ID. It toggles the other
 * enabled datasource off
 *
 * Arguments:
 * datasource_id {int} -- the ID of the datasource to enable
 * db {DatabaseDep} -- the database session
 *
 * Raises:
 * DataSourceToggleError: if the datasource is already enabled
 * DataSourceNotFound: if the datasource is not found
 * Returns:
 * GenericAPIResponse -- a message indicating the success of the operation
 */
export const saltstackToggleDatasource = <ThrowOnError extends boolean = false>(
	options: Options<SaltstackToggleDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		SaltstackToggleDatasourceResponse,
		SaltstackToggleDatasourceError,
		ThrowOnError
	>({
		url: "/datasources/saltstack/{datasource_id}/",
		...options,
	});
};
