// This file is auto-generated by @hey-api/openapi-ts

export type ApiListResponseUserDetailsResponse = {
    /**
     * The total number of items in the list
     */
    total: number;
    /**
     * The list of items returned by the API
     */
    data: Array<UserDetailsResponse>;
    /**
     * Whether the list is empty
     */
    empty: boolean;
};

export type ApiListResponseUserResponse = {
    /**
     * The total number of items in the list
     */
    total: number;
    /**
     * The list of items returned by the API
     */
    data: Array<UserResponse>;
    /**
     * Whether the list is empty
     */
    empty: boolean;
};

/**
 * reprents the pagination metadata for a query
 * to help the frontend
 */
export type ApiQueryResult = {
    /**
     * The total number of records from the returned query
     */
    total: number;
    /**
     * The number of records to skip for the next 'page' of the query
     */
    nextSkip: number;
    /**
     * The number of pages of results from the query
     */
    totalPages: number;
    /**
     * The total number of items returned in the query
     */
    totalItems: number;
};

/**
 * The base model for all app authentication forms
 */
export type AuthForm = {
    /**
     * The username of the user
     */
    username: string;
    /**
     * The password of the user
     */
    password: string;
};

/**
 * form to create a user
 */
export type CreateUserForm = {
    /**
     * The username of the user
     */
    username: string;
    /**
     * The password of the user
     */
    password: string;
    /**
     * The role of the user
     */
    role: Role;
};

export type EventLogLevel = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * represents the total number of logs for each log level
 */
export type EventLogLevelTotals = {
    info: number;
    warning: number;
    error: number;
    critical: number;
};

/**
 * represents a event log returned from the API
 */
export type EventLogRead = {
    logLevel: EventLogLevel;
    message: string;
    timestamp: string;
};

/**
 * Generic API response model
 */
export type GenericApiResponse = {
    data: {
        [key: string]: unknown;
    };
    /**
     * The message returned by the API
     */
    message: string;
};

/**
 * The form for creating a new Guacamole datasource
 */
export type GuacamoleCreateForm = {
    /**
     * The username for the datasource
     */
    username: string;
    /**
     * The password for the datasource
     */
    password: string;
    /**
     * Whether the datasource is enabled by default
     */
    enabled: boolean;
    /**
     * The name of the Guacamole datasource
     */
    datasource: string;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint: string;
};

/**
 * A guacamole datasource schema from the DB
 */
export type GuacamoleRead = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The name of the Guacamole datasource
     */
    datasource: string;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint: string;
};

/**
 * The form for updating a Guacamole datasource
 */
export type GuacamoleUpdateForm = {
    /**
     * The username for the datasource
     */
    username: string | null;
    /**
     * The password for the Guacamole datasource
     */
    password?: string | null;
    /**
     * The name of the Guacamole datasource
     */
    datasource?: string | null;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * represents the most recent logs for the critical and error log levels
 */
export type LastLogs = {
    lastCritical: EventLogRead | null;
    lastError: EventLogRead | null;
};

/**
 * the event log meta data to display in a dashboard
 */
export type LogMetaData = {
    /**
     * The total count of each log level
     */
    totals: EventLogLevelTotals;
    /**
     * The last error and critical log metadata
     */
    previousLogs: LastLogs;
};

/**
 * the logs returned from a query
 */
export type LogQueryResponse = {
    /**
     * The results of the query of type SchemaT
     */
    results: Array<EventLogRead>;
    /**
     * Metadata for the query results for the frontend to handle
     */
    pageContext: ApiQueryResult;
};

/**
 * The form for creating a new Openstack datasource
 */
export type OpenstackCreateForm = {
    /**
     * The username for the datasource
     */
    username: string;
    /**
     * The password for the datasource
     */
    password: string;
    /**
     * Whether the datasource is enabled by default
     */
    enabled: boolean;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string;
};

/**
 * A Openstack datasource schema from the DB
 */
export type OpenstackRead = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string;
};

/**
 * The form for updating a Openstack datasource
 */
export type OpenstackUpdateForm = {
    /**
     * The username for the datasource
     */
    username: string | null;
    /**
     * The password for the datasource
     */
    password: string | null;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string | null;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string | null;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string | null;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string | null;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string | null;
};

export type Role = 'admin' | 'user' | 'read_only';

/**
 * The form for creating a new Saltstack datasource
 */
export type SaltstackCreateForm = {
    /**
     * The username for the datasource
     */
    username: string;
    /**
     * The password for the datasource
     */
    password: string;
    /**
     * Whether the datasource is enabled by default
     */
    enabled: boolean;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint: string;
    /**
     * The hostname for the Saltstack datasource
     */
    hostname: string;
};

/**
 * A Saltstack datasource schema from the DB
 */
export type SaltstackRead = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint: string;
    /**
     * The hostname for the Saltstack datasource
     */
    hostname: string;
};

/**
 * The form for updating a Saltstack datasource
 */
export type SaltstackUpdateForm = {
    /**
     * The username for the datasource
     */
    username: string | null;
    /**
     * The password for the datasource
     */
    password: string | null;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint?: string | null;
    /**
     * The endpoint for the Saltstack datasource
     */
    hostname?: string | null;
};

/**
 * form to update a user
 */
export type UpdateUserForm = {
    username?: string | null;
    password?: string | null;
    role?: Role | null;
};

/**
 * The response model for the user; provides all the information
 */
export type UserDetailsResponse = {
    /**
     * The ID of the user
     */
    id: number;
    /**
     * The username of the user
     */
    username: string;
    /**
     * The role of the user
     */
    role: Role;
    /**
     * The date the user was created
     */
    createdAt: string;
    /**
     * The date the user was last updated
     */
    updatedAt: string;
};

/**
 * The response model for the user; only provides the essential information
 */
export type UserResponse = {
    /**
     * The ID of the user
     */
    id: number;
    /**
     * The username of the user
     */
    username: string;
    /**
     * The role of the user
     */
    role: Role;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead1 = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The name of the Guacamole datasource
     */
    datasource: string;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint: string;
    password: string;
};

export type AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead2 = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string;
    password: string;
};

export type AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead3 = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint: string;
    /**
     * The hostname for the Saltstack datasource
     */
    hostname: string;
    password: string;
};

export type LoginData = {
    body: AuthForm;
    path?: never;
    query?: never;
    url: '/auth/login/';
};

export type LoginErrors = {
    /**
     * Invalid username or password
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login successful
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Invalid session
     */
    401: unknown;
};

export type LogoutResponses = {
    /**
     * Logout successful
     */
    200: unknown;
};

export type CurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/';
};

export type CurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetAllUsersResponses = {
    /**
     * Successful Response
     */
    200: ApiListResponseUserResponse;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
    body: CreateUserForm;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type AllUserDetailsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/details';
};

export type AllUserDetailsResponses = {
    /**
     * Successful Response
     */
    200: ApiListResponseUserDetailsResponse;
};

export type AllUserDetailsResponse = AllUserDetailsResponses[keyof AllUserDetailsResponses];

export type UserDetailsData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/details/{user_id}/';
};

export type UserDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserDetailsError = UserDetailsErrors[keyof UserDetailsErrors];

export type UserDetailsResponses = {
    /**
     * Successful Response
     */
    200: UserDetailsResponse;
};

export type UserDetailsResponse2 = UserDetailsResponses[keyof UserDetailsResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/';
};

export type ReadUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserError = ReadUserErrors[keyof ReadUserErrors];

export type ReadUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type UpdateUserData = {
    body: UpdateUserForm;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    202: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logs/summary/';
};

export type SummaryResponses = {
    /**
     * Successful Response
     */
    200: LogMetaData;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of records to skip
         */
        skip?: number;
        /**
         * The maximum items to return in the response
         */
        limit?: number;
        /**
         * To filter the output by timestamp
         */
        orderByTimestamp?: boolean | null;
        /**
         * To filter the output by log level
         */
        logLevel?: EventLogLevel | null;
        /**
         * To filter the output by message
         */
        msgLike?: string | null;
    };
    url: '/logs/search/';
};

export type SearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * Successful Response
     */
    200: LogQueryResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type LogsFromTodayData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of records to skip
         */
        skip?: number;
        /**
         * The maximum items to return in the response
         */
        limit?: number;
        /**
         * To filter the output by timestamp
         */
        orderByTimestamp?: boolean | null;
        /**
         * To filter the output by log level
         */
        logLevel?: EventLogLevel | null;
        /**
         * To filter the output by message
         */
        msgLike?: string | null;
    };
    url: '/logs/today/';
};

export type LogsFromTodayErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogsFromTodayError = LogsFromTodayErrors[keyof LogsFromTodayErrors];

export type LogsFromTodayResponses = {
    /**
     * Successful Response
     */
    200: LogQueryResponse;
};

export type LogsFromTodayResponse = LogsFromTodayResponses[keyof LogsFromTodayResponses];

export type GetAllDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/guacamole/';
};

export type GetAllDatasourcesResponses = {
    /**
     * Successful Response
     */
    200: Array<GuacamoleRead>;
};

export type GetAllDatasourcesResponse = GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
    body: GuacamoleCreateForm;
    path?: never;
    query?: never;
    url: '/datasources/guacamole/';
};

export type CreateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
    /**
     * Successful Response
     */
    201: GuacamoleRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type ProtectedReadData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/protected/{datasource_id}/';
};

export type ProtectedReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProtectedReadError = ProtectedReadErrors[keyof ProtectedReadErrors];

export type ProtectedReadResponses = {
    /**
     * Successful Response
     */
    200: AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead1;
};

export type ProtectedReadResponse = ProtectedReadResponses[keyof ProtectedReadResponses];

export type DeleteDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type DeleteDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDatasourceError = DeleteDatasourceErrors[keyof DeleteDatasourceErrors];

export type DeleteDatasourceResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ReadDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type ReadDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadDatasourceError = ReadDatasourceErrors[keyof ReadDatasourceErrors];

export type ReadDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GuacamoleRead;
};

export type ReadDatasourceResponse = ReadDatasourceResponses[keyof ReadDatasourceResponses];

export type UpdateDatasourceData = {
    body: GuacamoleUpdateForm;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type UpdateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDatasourceError = UpdateDatasourceErrors[keyof UpdateDatasourceErrors];

export type UpdateDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GuacamoleRead;
};

export type UpdateDatasourceResponse = UpdateDatasourceResponses[keyof UpdateDatasourceResponses];

export type ToggleDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type ToggleDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleDatasourceError = ToggleDatasourceErrors[keyof ToggleDatasourceErrors];

export type ToggleDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type ToggleDatasourceResponse = ToggleDatasourceResponses[keyof ToggleDatasourceResponses];

export type GetAllDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/openstack/';
};

export type GetAllDatasourcesResponses = {
    /**
     * Successful Response
     */
    200: Array<OpenstackRead>;
};

export type GetAllDatasourcesResponse = GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
    body: OpenstackCreateForm;
    path?: never;
    query?: never;
    url: '/datasources/openstack/';
};

export type CreateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
    /**
     * Successful Response
     */
    201: OpenstackRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type ProtectedReadData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/protected/{datasource_id}/';
};

export type ProtectedReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProtectedReadError = ProtectedReadErrors[keyof ProtectedReadErrors];

export type ProtectedReadResponses = {
    /**
     * Successful Response
     */
    200: AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead2;
};

export type ProtectedReadResponse = ProtectedReadResponses[keyof ProtectedReadResponses];

export type DeleteDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type DeleteDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDatasourceError = DeleteDatasourceErrors[keyof DeleteDatasourceErrors];

export type DeleteDatasourceResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ReadDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type ReadDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadDatasourceError = ReadDatasourceErrors[keyof ReadDatasourceErrors];

export type ReadDatasourceResponses = {
    /**
     * Successful Response
     */
    200: OpenstackRead;
};

export type ReadDatasourceResponse = ReadDatasourceResponses[keyof ReadDatasourceResponses];

export type UpdateDatasourceData = {
    body: OpenstackUpdateForm;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type UpdateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDatasourceError = UpdateDatasourceErrors[keyof UpdateDatasourceErrors];

export type UpdateDatasourceResponses = {
    /**
     * Successful Response
     */
    200: OpenstackRead;
};

export type UpdateDatasourceResponse = UpdateDatasourceResponses[keyof UpdateDatasourceResponses];

export type ToggleDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type ToggleDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleDatasourceError = ToggleDatasourceErrors[keyof ToggleDatasourceErrors];

export type ToggleDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type ToggleDatasourceResponse = ToggleDatasourceResponses[keyof ToggleDatasourceResponses];

export type GetAllDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/saltstack/';
};

export type GetAllDatasourcesResponses = {
    /**
     * Successful Response
     */
    200: Array<SaltstackRead>;
};

export type GetAllDatasourcesResponse = GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
    body: SaltstackCreateForm;
    path?: never;
    query?: never;
    url: '/datasources/saltstack/';
};

export type CreateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
    /**
     * Successful Response
     */
    201: SaltstackRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type ProtectedReadData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/protected/{datasource_id}/';
};

export type ProtectedReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProtectedReadError = ProtectedReadErrors[keyof ProtectedReadErrors];

export type ProtectedReadResponses = {
    /**
     * Successful Response
     */
    200: AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead3;
};

export type ProtectedReadResponse = ProtectedReadResponses[keyof ProtectedReadResponses];

export type DeleteDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type DeleteDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDatasourceError = DeleteDatasourceErrors[keyof DeleteDatasourceErrors];

export type DeleteDatasourceResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ReadDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type ReadDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadDatasourceError = ReadDatasourceErrors[keyof ReadDatasourceErrors];

export type ReadDatasourceResponses = {
    /**
     * Successful Response
     */
    200: SaltstackRead;
};

export type ReadDatasourceResponse = ReadDatasourceResponses[keyof ReadDatasourceResponses];

export type UpdateDatasourceData = {
    body: SaltstackUpdateForm;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type UpdateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDatasourceError = UpdateDatasourceErrors[keyof UpdateDatasourceErrors];

export type UpdateDatasourceResponses = {
    /**
     * Successful Response
     */
    200: SaltstackRead;
};

export type UpdateDatasourceResponse = UpdateDatasourceResponses[keyof UpdateDatasourceResponses];

export type ToggleDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type ToggleDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleDatasourceError = ToggleDatasourceErrors[keyof ToggleDatasourceErrors];

export type ToggleDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type ToggleDatasourceResponse = ToggleDatasourceResponses[keyof ToggleDatasourceResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};