// This file is auto-generated by @hey-api/openapi-ts

export type ApiListResponseUserDetailsResponse = {
    /**
     * The total number of items in the list
     */
    total: number;
    /**
     * The list of items returned by the API
     */
    data: Array<UserDetailsResponse>;
    /**
     * Whether the list is empty
     */
    empty: boolean;
};

export type ApiListResponseUserResponse = {
    /**
     * The total number of items in the list
     */
    total: number;
    /**
     * The list of items returned by the API
     */
    data: Array<UserResponse>;
    /**
     * Whether the list is empty
     */
    empty: boolean;
};

/**
 * reprents the pagination metadata for a query
 * to help the frontend
 */
export type ApiQueryResult = {
    /**
     * The total number of records from the returned query
     */
    total: number;
    /**
     * The number of records to skip for the next 'page' of the query
     */
    nextSkip: number;
    /**
     * The number of pages of results from the query
     */
    totalPages: number;
    /**
     * The total number of items returned in the query
     */
    totalItems: number;
};

/**
 * The base model for all app authentication forms
 */
export type AuthForm = {
    /**
     * The username of the user
     */
    username: string;
    /**
     * The password of the user
     */
    password: string;
};

/**
 * form to create a user
 */
export type CreateUserForm = {
    /**
     * The username of the user
     */
    username: string;
    /**
     * The password of the user
     */
    password: string;
    /**
     * The role of the user
     */
    role: Role;
};

/**
 * represents a event log returned from the API
 */
export type EventLogRead = {
    logLevel: LogLevel;
    message: string;
    timestamp: string;
};

/**
 * Generic API response model
 */
export type GenericApiResponse = {
    data: {
        [key: string]: unknown;
    };
    /**
     * The message returned by the API
     */
    message: string;
};

/**
 * The form for creating a new Guacamole datasource
 */
export type GuacamoleCreateForm = {
    /**
     * The username for the datasource
     */
    username: string;
    /**
     * The password for the datasource
     */
    password: string;
    /**
     * Whether the datasource is enabled by default
     */
    enabled: boolean;
    /**
     * The name of the Guacamole datasource
     */
    datasource: string;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint: string;
};

/**
 * A guacamole datasource schema from the DB
 */
export type GuacamoleRead = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The name of the Guacamole datasource
     */
    datasource: string;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint: string;
};

/**
 * The form for updating a Guacamole datasource
 */
export type GuacamoleUpdateForm = {
    /**
     * The username for the datasource
     */
    username: string | null;
    /**
     * The password for the Guacamole datasource
     */
    password?: string | null;
    /**
     * The name of the Guacamole datasource
     */
    datasource?: string | null;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * represents the most recent logs for the critical and error log levels
 */
export type LastLogs = {
    lastCritical: EventLogRead | null;
    lastError: EventLogRead | null;
};

export type LogLevel = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * represents the total number of logs for each log level
 */
export type LogLevelTotals = {
    info: number;
    warning: number;
    error: number;
    critical: number;
};

/**
 * the event log meta data to display in a dashboard
 */
export type LogMetaData = {
    /**
     * The total count of each log level
     */
    totals: LogLevelTotals;
    /**
     * The last error and critical log metadata
     */
    previousLogs: LastLogs;
};

/**
 * the logs returned from a query
 */
export type LogQueryResponse = {
    /**
     * The results of the query of type SchemaT
     */
    results: Array<EventLogRead>;
    /**
     * Metadata for the query results for the frontend to handle
     */
    pageContext: ApiQueryResult;
};

/**
 * The form for creating a new Openstack datasource
 */
export type OpenstackCreateForm = {
    /**
     * The username for the datasource
     */
    username: string;
    /**
     * The password for the datasource
     */
    password: string;
    /**
     * Whether the datasource is enabled by default
     */
    enabled: boolean;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string;
};

/**
 * A Openstack datasource schema from the DB
 */
export type OpenstackRead = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string;
};

/**
 * The form for updating a Openstack datasource
 */
export type OpenstackUpdateForm = {
    /**
     * The username for the datasource
     */
    username: string | null;
    /**
     * The password for the datasource
     */
    password: string | null;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string | null;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string | null;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string | null;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string | null;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string | null;
};

export type Role = 'admin' | 'user' | 'read_only';

/**
 * The form for creating a new Saltstack datasource
 */
export type SaltstackCreateForm = {
    /**
     * The username for the datasource
     */
    username: string;
    /**
     * The password for the datasource
     */
    password: string;
    /**
     * Whether the datasource is enabled by default
     */
    enabled: boolean;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint: string;
    /**
     * The hostname for the Saltstack datasource
     */
    hostname: string;
};

/**
 * A Saltstack datasource schema from the DB
 */
export type SaltstackRead = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint: string;
    /**
     * The hostname for the Saltstack datasource
     */
    hostname: string;
};

/**
 * The form for updating a Saltstack datasource
 */
export type SaltstackUpdateForm = {
    /**
     * The username for the datasource
     */
    username: string | null;
    /**
     * The password for the datasource
     */
    password: string | null;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint?: string | null;
    /**
     * The endpoint for the Saltstack datasource
     */
    hostname?: string | null;
};

/**
 * form to update a user
 */
export type UpdateUserForm = {
    username?: string | null;
    password?: string | null;
    role?: Role | null;
};

/**
 * The response model for the user; provides all the information
 */
export type UserDetailsResponse = {
    /**
     * The ID of the user
     */
    id: number;
    /**
     * The username of the user
     */
    username: string;
    /**
     * The role of the user
     */
    role: Role;
    /**
     * The date the user was created
     */
    createdAt: string;
    /**
     * The date the user was last updated
     */
    updatedAt: string;
};

/**
 * The response model for the user; only provides the essential information
 */
export type UserResponse = {
    /**
     * The ID of the user
     */
    id: number;
    /**
     * The username of the user
     */
    username: string;
    /**
     * The role of the user
     */
    role: Role;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead1 = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The name of the Guacamole datasource
     */
    datasource: string;
    /**
     * The URL for the Guacamole datasource
     */
    endpoint: string;
    password: string;
};

export type AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead2 = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The URL for the Openstack authentication
     */
    authUrl: string;
    /**
     * The project ID for the Openstack authentication
     */
    projectId?: string | null;
    /**
     * The project name for the Openstack authentication
     */
    projectName?: string | null;
    /**
     * The project domain name for the Openstack authentication
     */
    projectDomainName: string;
    /**
     * The user domain name for the Openstack authentication
     */
    userDomainName: string;
    /**
     * The region name for the Openstack authentication
     */
    regionName: string;
    /**
     * The identity API version for the Openstack authentication
     */
    identityApiVersion: string;
    password: string;
};

export type AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead3 = {
    id: number;
    username: string;
    enabled: boolean;
    /**
     * The endpoint for the Saltstack datasource
     */
    endpoint: string;
    /**
     * The hostname for the Saltstack datasource
     */
    hostname: string;
    password: string;
};

export type AuthLoginData = {
    body: AuthForm;
    path?: never;
    query?: never;
    url: '/auth/login/';
};

export type AuthLoginErrors = {
    /**
     * Invalid username or password
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Login successful
     */
    200: unknown;
};

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * Invalid session
     */
    401: unknown;
};

export type AuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: unknown;
};

export type UserCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/';
};

export type UserCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UserCurrentUserResponse = UserCurrentUserResponses[keyof UserCurrentUserResponses];

export type UserGetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type UserGetAllUsersResponses = {
    /**
     * Successful Response
     */
    200: ApiListResponseUserResponse;
};

export type UserGetAllUsersResponse = UserGetAllUsersResponses[keyof UserGetAllUsersResponses];

export type UserCreateUserData = {
    body: CreateUserForm;
    path?: never;
    query?: never;
    url: '/users/';
};

export type UserCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserCreateUserError = UserCreateUserErrors[keyof UserCreateUserErrors];

export type UserCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type UserCreateUserResponse = UserCreateUserResponses[keyof UserCreateUserResponses];

export type UserAllUserDetailsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/details';
};

export type UserAllUserDetailsResponses = {
    /**
     * Successful Response
     */
    200: ApiListResponseUserDetailsResponse;
};

export type UserAllUserDetailsResponse = UserAllUserDetailsResponses[keyof UserAllUserDetailsResponses];

export type UserUserDetailsData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/details/{user_id}/';
};

export type UserUserDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserUserDetailsError = UserUserDetailsErrors[keyof UserUserDetailsErrors];

export type UserUserDetailsResponses = {
    /**
     * Successful Response
     */
    200: UserDetailsResponse;
};

export type UserUserDetailsResponse = UserUserDetailsResponses[keyof UserUserDetailsResponses];

export type UserDeleteUserData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/';
};

export type UserDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserDeleteUserError = UserDeleteUserErrors[keyof UserDeleteUserErrors];

export type UserDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type UserDeleteUserResponse = UserDeleteUserResponses[keyof UserDeleteUserResponses];

export type UserReadUserData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/';
};

export type UserReadUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserReadUserError = UserReadUserErrors[keyof UserReadUserErrors];

export type UserReadUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UserReadUserResponse = UserReadUserResponses[keyof UserReadUserResponses];

export type UserUpdateUserData = {
    body: UpdateUserForm;
    path: {
        /**
         * The id of model.
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/';
};

export type UserUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserUpdateUserError = UserUpdateUserErrors[keyof UserUpdateUserErrors];

export type UserUpdateUserResponses = {
    /**
     * Successful Response
     */
    202: UserResponse;
};

export type UserUpdateUserResponse = UserUpdateUserResponses[keyof UserUpdateUserResponses];

export type EventLogsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logs/summary/';
};

export type EventLogsSummaryResponses = {
    /**
     * Successful Response
     */
    200: LogMetaData;
};

export type EventLogsSummaryResponse = EventLogsSummaryResponses[keyof EventLogsSummaryResponses];

export type EventLogsSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of records to skip
         */
        skip?: number;
        /**
         * The maximum items to return in the response
         */
        limit?: number;
        /**
         * To filter the output by timestamp
         */
        orderByTimestamp?: boolean | null;
        /**
         * To filter the output by log level
         */
        logLevel?: LogLevel | null;
        /**
         * To filter the output by message
         */
        msgLike?: string | null;
    };
    url: '/logs/search/';
};

export type EventLogsSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventLogsSearchError = EventLogsSearchErrors[keyof EventLogsSearchErrors];

export type EventLogsSearchResponses = {
    /**
     * Successful Response
     */
    200: LogQueryResponse;
};

export type EventLogsSearchResponse = EventLogsSearchResponses[keyof EventLogsSearchResponses];

export type EventLogsLogsFromTodayData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of records to skip
         */
        skip?: number;
        /**
         * The maximum items to return in the response
         */
        limit?: number;
        /**
         * To filter the output by timestamp
         */
        orderByTimestamp?: boolean | null;
        /**
         * To filter the output by log level
         */
        logLevel?: LogLevel | null;
        /**
         * To filter the output by message
         */
        msgLike?: string | null;
    };
    url: '/logs/today/';
};

export type EventLogsLogsFromTodayErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventLogsLogsFromTodayError = EventLogsLogsFromTodayErrors[keyof EventLogsLogsFromTodayErrors];

export type EventLogsLogsFromTodayResponses = {
    /**
     * Successful Response
     */
    200: LogQueryResponse;
};

export type EventLogsLogsFromTodayResponse = EventLogsLogsFromTodayResponses[keyof EventLogsLogsFromTodayResponses];

export type GuacGetAllDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/guacamole/';
};

export type GuacGetAllDatasourcesResponses = {
    /**
     * Successful Response
     */
    200: Array<GuacamoleRead>;
};

export type GuacGetAllDatasourcesResponse = GuacGetAllDatasourcesResponses[keyof GuacGetAllDatasourcesResponses];

export type GuacCreateDatasourceData = {
    body: GuacamoleCreateForm;
    path?: never;
    query?: never;
    url: '/datasources/guacamole/';
};

export type GuacCreateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuacCreateDatasourceError = GuacCreateDatasourceErrors[keyof GuacCreateDatasourceErrors];

export type GuacCreateDatasourceResponses = {
    /**
     * Successful Response
     */
    201: GuacamoleRead;
};

export type GuacCreateDatasourceResponse = GuacCreateDatasourceResponses[keyof GuacCreateDatasourceResponses];

export type GuacProtectedReadData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/protected/{datasource_id}/';
};

export type GuacProtectedReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuacProtectedReadError = GuacProtectedReadErrors[keyof GuacProtectedReadErrors];

export type GuacProtectedReadResponses = {
    /**
     * Successful Response
     */
    200: AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead1;
};

export type GuacProtectedReadResponse = GuacProtectedReadResponses[keyof GuacProtectedReadResponses];

export type GuacDeleteDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type GuacDeleteDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuacDeleteDatasourceError = GuacDeleteDatasourceErrors[keyof GuacDeleteDatasourceErrors];

export type GuacDeleteDatasourceResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type GuacReadDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type GuacReadDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuacReadDatasourceError = GuacReadDatasourceErrors[keyof GuacReadDatasourceErrors];

export type GuacReadDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GuacamoleRead;
};

export type GuacReadDatasourceResponse = GuacReadDatasourceResponses[keyof GuacReadDatasourceResponses];

export type GuacUpdateDatasourceData = {
    body: GuacamoleUpdateForm;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type GuacUpdateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuacUpdateDatasourceError = GuacUpdateDatasourceErrors[keyof GuacUpdateDatasourceErrors];

export type GuacUpdateDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GuacamoleRead;
};

export type GuacUpdateDatasourceResponse = GuacUpdateDatasourceResponses[keyof GuacUpdateDatasourceResponses];

export type GuacToggleDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/guacamole/{datasource_id}/';
};

export type GuacToggleDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuacToggleDatasourceError = GuacToggleDatasourceErrors[keyof GuacToggleDatasourceErrors];

export type GuacToggleDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type GuacToggleDatasourceResponse = GuacToggleDatasourceResponses[keyof GuacToggleDatasourceResponses];

export type OpenstackGetAllDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/openstack/';
};

export type OpenstackGetAllDatasourcesResponses = {
    /**
     * Successful Response
     */
    200: Array<OpenstackRead>;
};

export type OpenstackGetAllDatasourcesResponse = OpenstackGetAllDatasourcesResponses[keyof OpenstackGetAllDatasourcesResponses];

export type OpenstackCreateDatasourceData = {
    body: OpenstackCreateForm;
    path?: never;
    query?: never;
    url: '/datasources/openstack/';
};

export type OpenstackCreateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenstackCreateDatasourceError = OpenstackCreateDatasourceErrors[keyof OpenstackCreateDatasourceErrors];

export type OpenstackCreateDatasourceResponses = {
    /**
     * Successful Response
     */
    201: OpenstackRead;
};

export type OpenstackCreateDatasourceResponse = OpenstackCreateDatasourceResponses[keyof OpenstackCreateDatasourceResponses];

export type OpenstackProtectedReadData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/protected/{datasource_id}/';
};

export type OpenstackProtectedReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenstackProtectedReadError = OpenstackProtectedReadErrors[keyof OpenstackProtectedReadErrors];

export type OpenstackProtectedReadResponses = {
    /**
     * Successful Response
     */
    200: AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead2;
};

export type OpenstackProtectedReadResponse = OpenstackProtectedReadResponses[keyof OpenstackProtectedReadResponses];

export type OpenstackDeleteDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type OpenstackDeleteDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenstackDeleteDatasourceError = OpenstackDeleteDatasourceErrors[keyof OpenstackDeleteDatasourceErrors];

export type OpenstackDeleteDatasourceResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type OpenstackReadDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type OpenstackReadDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenstackReadDatasourceError = OpenstackReadDatasourceErrors[keyof OpenstackReadDatasourceErrors];

export type OpenstackReadDatasourceResponses = {
    /**
     * Successful Response
     */
    200: OpenstackRead;
};

export type OpenstackReadDatasourceResponse = OpenstackReadDatasourceResponses[keyof OpenstackReadDatasourceResponses];

export type OpenstackUpdateDatasourceData = {
    body: OpenstackUpdateForm;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type OpenstackUpdateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenstackUpdateDatasourceError = OpenstackUpdateDatasourceErrors[keyof OpenstackUpdateDatasourceErrors];

export type OpenstackUpdateDatasourceResponses = {
    /**
     * Successful Response
     */
    200: OpenstackRead;
};

export type OpenstackUpdateDatasourceResponse = OpenstackUpdateDatasourceResponses[keyof OpenstackUpdateDatasourceResponses];

export type OpenstackToggleDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/openstack/{datasource_id}/';
};

export type OpenstackToggleDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenstackToggleDatasourceError = OpenstackToggleDatasourceErrors[keyof OpenstackToggleDatasourceErrors];

export type OpenstackToggleDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type OpenstackToggleDatasourceResponse = OpenstackToggleDatasourceResponses[keyof OpenstackToggleDatasourceResponses];

export type SaltstackGetAllDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/saltstack/';
};

export type SaltstackGetAllDatasourcesResponses = {
    /**
     * Successful Response
     */
    200: Array<SaltstackRead>;
};

export type SaltstackGetAllDatasourcesResponse = SaltstackGetAllDatasourcesResponses[keyof SaltstackGetAllDatasourcesResponses];

export type SaltstackCreateDatasourceData = {
    body: SaltstackCreateForm;
    path?: never;
    query?: never;
    url: '/datasources/saltstack/';
};

export type SaltstackCreateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaltstackCreateDatasourceError = SaltstackCreateDatasourceErrors[keyof SaltstackCreateDatasourceErrors];

export type SaltstackCreateDatasourceResponses = {
    /**
     * Successful Response
     */
    201: SaltstackRead;
};

export type SaltstackCreateDatasourceResponse = SaltstackCreateDatasourceResponses[keyof SaltstackCreateDatasourceResponses];

export type SaltstackProtectedReadData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/protected/{datasource_id}/';
};

export type SaltstackProtectedReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaltstackProtectedReadError = SaltstackProtectedReadErrors[keyof SaltstackProtectedReadErrors];

export type SaltstackProtectedReadResponses = {
    /**
     * Successful Response
     */
    200: AppDatasourcesRouterSetupDatasourceRouterLocalsProtectedRead3;
};

export type SaltstackProtectedReadResponse = SaltstackProtectedReadResponses[keyof SaltstackProtectedReadResponses];

export type SaltstackDeleteDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type SaltstackDeleteDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaltstackDeleteDatasourceError = SaltstackDeleteDatasourceErrors[keyof SaltstackDeleteDatasourceErrors];

export type SaltstackDeleteDatasourceResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type SaltstackReadDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type SaltstackReadDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaltstackReadDatasourceError = SaltstackReadDatasourceErrors[keyof SaltstackReadDatasourceErrors];

export type SaltstackReadDatasourceResponses = {
    /**
     * Successful Response
     */
    200: SaltstackRead;
};

export type SaltstackReadDatasourceResponse = SaltstackReadDatasourceResponses[keyof SaltstackReadDatasourceResponses];

export type SaltstackUpdateDatasourceData = {
    body: SaltstackUpdateForm;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type SaltstackUpdateDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaltstackUpdateDatasourceError = SaltstackUpdateDatasourceErrors[keyof SaltstackUpdateDatasourceErrors];

export type SaltstackUpdateDatasourceResponses = {
    /**
     * Successful Response
     */
    200: SaltstackRead;
};

export type SaltstackUpdateDatasourceResponse = SaltstackUpdateDatasourceResponses[keyof SaltstackUpdateDatasourceResponses];

export type SaltstackToggleDatasourceData = {
    body?: never;
    path: {
        /**
         * The id of model.
         */
        datasource_id: number;
    };
    query?: never;
    url: '/datasources/saltstack/{datasource_id}/';
};

export type SaltstackToggleDatasourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaltstackToggleDatasourceError = SaltstackToggleDatasourceErrors[keyof SaltstackToggleDatasourceErrors];

export type SaltstackToggleDatasourceResponses = {
    /**
     * Successful Response
     */
    200: GenericApiResponse;
};

export type SaltstackToggleDatasourceResponse = SaltstackToggleDatasourceResponses[keyof SaltstackToggleDatasourceResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};