

default:
  tags:
    - docker-gcc
  image: python:3.12-slim
  before_script:
    - python -m pip install --upgrade pip
    - uv --version

stages:
  - lint

lint:
  stage: lint
  script: |
    set -x
    set -e 
    uv install
    uv sync
    ruff check app scripts --fix
    ruff format app scripts 
    mypy app
    ruff check app
    ruff format app --check
    