version: "3.12"

services:
  app:
    build: .
    image: app
    ports:
      - "80:80"
    environment:
      - DEPLOYMENT: "prod"
      - DATABASE_URL: ${DATABASE_URL}
      - SECRET_KEY: ${SECRET_KEY}
      - SIGNATURE_SALT: ${SIGNATURE_SALT}
      - CSRF_SECRET_KEY: ${CSRF_SECRET_KEY}
      - ENCRYPTION_KEY: ${ENCRYPTION_KEY}
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
