= Range Monitor v2
:toc:

The Range Monitor is web-based application that for monitoring and 
interacting, monitoring & browsing Guacamole, OpenStack and Saltstack.

The Range Monitor v2 wil be rewritten in FastAPI for performance, security,
scalability and to expand the existing functionality and scope of the project.
Furthermore, the end goal is creating a more modular and extensible
backend that will serve as the API for a more a robust and modern frontend made in
a Javascript framework. 


 
== Getting Started

* You will first need to have git & pip installed on your
machine

[,git]
----
git clone <http_url>
----

* Change to the directory of Version 2 from the project root

[,bash]
----
cd version_2
----

=== Create & Activate the virtual environment

*Windows*

[,ps1]
----
py -m venv .venv
.venv\Scripts\activate
----

*Unix Based*

[,bash]
----
python3 -m venv .venv
. .venv/bin/activate
----

*Install the required Python Dependencies*

[,bash]
----
pip install -r requirements.txt
----

=== Environment Variables  

* Create a .env file in the root of 'version_2' directory

[,bash]
----
echo > .env
----

* Generate the secret keys for the .env file 

[,bash]
----
py
>> import secrets; secrets.token_hex(16)
'YOUR_SECRET_KEY'
// repeat for all secrets
----

* Add the following to the .env file 

[,bash]
----
SECRET_KEY=YOUR_SECRET_KEY
DATABASE_URL=sqlite+aiosqlite:///./instance/app.db
JWT_SECRET_KEY=YOUR_JWT_SECRET_KEY
JWT_ALGORITHM=HS256
REDIS_HOST=localhost
REDIS_PORT=6379
----

=== Run the FastAPI application for the first time using the Command Line
[,bash]
----
fastapi dev api 
----

* In the console, you should've seen the SQLite / SQLAlchemy echo the database initialization at  'instance\app.db' in the version_2 directory with the tables / models and seed data. 

* Open the database with a SQLite GUI tool such as DB Browser for SQLite and confirm the tables and seed data

== Developer Notes

** *SwaggerUI API Endpoint Documentation*: one of the best features of FastAPI is the automatic generation of API documentation with SwaggerUI which will detail all of the 
API routes, the expected request & response body and the status codes which 
you can view when you run the application and navigate to the /docs endpoint 
after running the application. *IN PRODUCTION DISABLE THIS FEATURE*

* *VS Code Workspace*: Use the .code-workspace file in the root of the project to open the project in Visual Studio Code with the recommended extensions. This maintains consistency for development and formatting across the project, Click on the .code-workspace file,
and click 'Open Workspace' to open the workspace.

** *Type / Checking IMPORTANT*: the .code-workspace files enforces 'basic' level type checking with pylance for better code readability and to provide a clear definition for an other wise ambigous type. This means you are REQUIRED to provide type hints for functions, variables and it may take some getting used to but it will save you alot of time.   
  ** _Pylance can be a bit overzealous at times and a type error does not mean your code is inherently wrong, such as in instances where a type conversions such as an ORM being serialized implicitly to a Pydantic Model in a response for a route. When this occurs provide *# type: ignore comments to suppress the errors* but it is encouraged to use type hints where possible._

== Resources  

[discrete]
=== Documentation

*FastAPI*: link:https://fastapi.tiangolo.com/learn/[_here_]

*SQLAlchemy Documentation*: link:https://docs.sqlalchemy.org/en/20/intro.html[_here_]

*Pydantic Documentation*: link:https://pydantic-docs.helpmanual.io/[_here_]

=== Tutorials

*FastAPI CRUD & Beyond*: a tutorial series that covers, the basics, how to structure your app, production
grade security, ORM, Pydantic Routing, JWT & more that I cannot reccomend enough for learning FastAPI. 
link:https://www.youtube.com/playlist?list=PLEt8Tae2spYnHy378vMlPH--87cfeh33P[_here_] 

=== Recommendations


* *Use a REST Client*: saves you time, effort and offers better security & visibility into API behavior 

- *Insomnia*: A Free REST client that will be invaluable for testing the API endpoints, security and
Pydantic Models (_use hobby version_) which you can install link:https://insomnia.rest/[here]

- *DB Browser for SQLite*: A Free GUI tool for managing SQLite databases which you can install link:https://sqlitebrowser.org/[here]

== Project Structure 

The project structure is designed to be modular to allow shared logic among modules and api routes
following the Model-View-Controller (MVC) pattern.

* The "*models*" directory contains the database models for the application
    ** NOTE: when creating a new model, ensure in the init_db() function in db\main.py
    imports it or it will not be created or associated with ORM.
    
* The "*db*" directory contains the main database logic and interface for the application
    ** _main.py_: contains the database functions used to interact with the database
    ** _crud.py_: contains mixins for services to share logic such as CRUD operations, 
    they should be inherited from by a Service

* The "*utils*" directory contains utility functions that are shared among the modules
(e.g password hashing, token generation, decorators etc.) 

=== Routes
When creating a new route prefix, create a new directory with the same name 
* _service.py_:  CRUD operations and utilities for manipulating the corresponding 
ORM and core logic for the routes 

* _routes.py_:  API router for the module 

* _schemas.py_:  Pydantic models for the route

_If any of these files grow either grow in scope or are excessively long, break it into a module / directory with an __init__.py file to import the necessary logic_

=== Layout

----

version_2/
    .venv

    .env 
    instance/app.db
    
    api/
      __init__.py # stores app instance 

      build.py # contains app building logic (e.g registering routes)

      config/ 
        __init__.py 
        settings.py # settings for the app


      db/ 
        ...
        main.py # database logic and interface 
        crud.py # CRUD operations for models

      models/ 
        ... # DB / ORM models  

      utils/ ...

     main/ 
        schemas/ 
            ... # Pydantic models
        datasources/
            ...
            routes.py # API router
            services.py # CRUD operations
        user/
            ...
            routes.py # API router
            services.py # CRUD operations

      guacamole/ 
        utils/
          ... # guac specific utilities
        routes.py
        services.py
        schemas.py
      openstack/ 
        ... same as guac
        
      saltstack/ 
        ... same as guac
----