x-app-env: &app_env
  env_file:
    - ./.env
    - ./.${APP_ENV:-dev}.env
  environment:
    APP_ENV: ${APP_ENV:-dev}
    SQLITE_URL: ${SQLITE_URL:-sqlite:////app/instance/db.sqlite3}
    REDIS_URL: ${REDIS_URL:-redis://${REDIS_USER:-app}:${REDIS_PASSWORD:-password}@redis:6379}

services:
  redis:
    image: redis:8.2.2-alpine3.22
    container_name: monitor_redis
    command: ["redis-server", "--appendonly", "no"]
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: monitor_api
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    <<: *app_env
    volumes:
      - uv_cache:/home/nonroot/.cache/uv
      - ./server:/app/server
      - ./configs:/app/configs
      - ./pyproject.toml:/app/pyproject.toml
      - ./.${APP_ENV:-dev}.env:/app/.${APP_ENV:-dev}.env:ro
      - .env:/app/.env:ro
      - ./secrets:/run/secrets:ro
      - ./instance:/app/instance

volumes:
  uv_cache: {}
