// This file is auto-generated by @hey-api/openapi-ts

import {
	type Options as ClientOptions,
	type TDataShape,
	type Client,
	urlSearchParamsBodySerializer
} from '@hey-api/client-fetch';
import type {
	LoginData,
	LoginError,
	LogoutData,
	CurrentUserData,
	CurrentUserResponse,
	GetAllUsersData,
	GetAllUsersResponse,
	CreateUserData,
	CreateUserResponse,
	CreateUserError,
	AllUserDetailsData,
	AllUserDetailsResponse,
	UserDetailsData,
	UserDetailsResponse2,
	UserDetailsError,
	DeleteUserData,
	DeleteUserResponse,
	DeleteUserError,
	ReadUserData,
	ReadUserResponse,
	ReadUserError,
	UpdateUserData,
	UpdateUserResponse,
	UpdateUserError,
	SummaryData,
	SummaryResponse,
	SearchData,
	SearchResponse,
	SearchError,
	LogsFromTodayData,
	LogsFromTodayResponse,
	LogsFromTodayError,
	GetAllOpenstackSourcesData,
	GetAllOpenstackSourcesResponse,
	CreateOpenstackDatasourceData,
	CreateOpenstackDatasourceResponse,
	CreateOpenstackDatasourceError,
	GetOpenstackDetailsData,
	GetOpenstackDetailsResponse,
	GetOpenstackDetailsError,
	ToggleOpenstackDatasourceData,
	ToggleOpenstackDatasourceResponse,
	ToggleOpenstackDatasourceError,
	TestOpenstackConnectionData,
	TestOpenstackConnectionResponse,
	TestOpenstackDatasourceData,
	TestOpenstackDatasourceResponse,
	TestOpenstackDatasourceError,
	DeleteOpenstackSourceData,
	DeleteOpenstackSourceResponse,
	DeleteOpenstackSourceError,
	GetOpenstackSourceData,
	GetOpenstackSourceResponse,
	GetOpenstackSourceError,
	UpdateOpenstackSourceData,
	UpdateOpenstackSourceResponse,
	UpdateOpenstackSourceError,
	GetAllGuacamoleSourcesData,
	GetAllGuacamoleSourcesResponse,
	CreateGuacamoleDatasourceData,
	CreateGuacamoleDatasourceResponse,
	CreateGuacamoleDatasourceError,
	GetGuacamoleDetailsData,
	GetGuacamoleDetailsResponse,
	GetGuacamoleDetailsError,
	ToggleGuacamoleDatasourceData,
	ToggleGuacamoleDatasourceResponse,
	ToggleGuacamoleDatasourceError,
	TestGuacamoleConnectionData,
	TestGuacamoleConnectionResponse,
	TestGuacamoleDatasourceData,
	TestGuacamoleDatasourceResponse,
	TestGuacamoleDatasourceError,
	DeleteGuacamoleSourceData,
	DeleteGuacamoleSourceResponse,
	DeleteGuacamoleSourceError,
	ReadGuacamoleSourceData,
	ReadGuacamoleSourceResponse,
	ReadGuacamoleSourceError,
	UpdateGuacamoleSourceData,
	UpdateGuacamoleSourceResponse,
	UpdateGuacamoleSourceError
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export class AuthService {
	/**
	 * Login
	 * Checks the credentials provided by the 'AuthForm'
	 * and in the response sets a cookie with the session id when given
	 * valid login credentials.
	 *
	 * Arguments:
	 * auth_form {AuthForm} -- Has types to enforce constraints on the request body
	 * client {RequireClientIdentity} -- The client identity
	 * user_service {UserController} -- The user controller
	 * Raises:
	 * HTTPUnauthorized: 401 - If the user is not authenticated
	 * Returns:
	 * Response
	 */
	public static login<ThrowOnError extends boolean = false>(
		options: Options<LoginData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<unknown, LoginError, ThrowOnError>({
			...urlSearchParamsBodySerializer,
			url: '/auth/login/',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}

	/**
	 * Logout
	 * Logs out the user using the _"api_key" dependency_
	 *
	 * - Load the clients signed api key from the clients cookies
	 * - Decrypts the api key in the Redis store,
	 *
	 * - if the key hasn't been tampered with by the user and is valid the
	 * session is revoked by deleting the key in the Redis store mapped to the api key
	 * and the cookie is removed from the client
	 * Arguments:
	 * request {Request}  - the request to get the existing session ID from
	 * Raises:
	 * If the api_key is not found or was tampered with
	 * by the client
	 * Returns:
	 * JSONResponse -- a message indicating the logout was successful
	 */
	public static logout<ThrowOnError extends boolean = false>(
		options?: Options<LogoutData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
			url: '/auth/logout/',
			...options
		});
	}
}

export class UserService {
	/**
	 * Current User
	 * Reads the current user
	 *
	 * Arguments:
	 * reader {CurrentUser} -- the reader
	 *
	 * Returns:
	 * UserResponse -- the current user
	 */
	public static currentUser<ThrowOnError extends boolean = false>(
		options?: Options<CurrentUserData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<CurrentUserResponse, unknown, ThrowOnError>({
			url: '/users/me/',
			...options
		});
	}

	/**
	 * Get All Users
	 * reads all users based on the role of the reader (no read up)
	 * Arguments:
	 * user_service {UserController} -- _the user controller_
	 * reader {CurrentUser} -- _the reader_
	 *
	 * Returns:
	 * list[UserResponse] -- _description_
	 */
	public static getAllUsers<ThrowOnError extends boolean = false>(
		options?: Options<GetAllUsersData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<GetAllUsersResponse, unknown, ThrowOnError>({
			url: '/users/',
			...options
		});
	}

	/**
	 * Create User
	 * **[ADMIN]**
	 * Creates a user given valid form data and inserts
	 * the created user into the database and returns the
	 * created user
	 *
	 * _Arguments_:
	 * - create_schema {CreateUserForm} -- the form data
	 * - db {AsyncSession} - the database session
	 * _Raises_:
	 * HTTPException: 400 - Username is already taken
	 * _Returns_:
	 * UserResponse -- the created user
	 */
	public static createUser<ThrowOnError extends boolean = false>(
		options: Options<CreateUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			CreateUserResponse,
			CreateUserError,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/users/',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}

	/**
	 * All User Details
	 * Admin protected route to read all of the user details, including
	 * the creation date and last updated timestamps
	 *
	 * Arguments:
	 * db {requires_db}
	 *
	 * Returns:
	 * list[UserDetailsResponse]
	 */
	public static allUserDetails<ThrowOnError extends boolean = false>(
		options?: Options<AllUserDetailsData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<AllUserDetailsResponse, unknown, ThrowOnError>({
			url: '/users/details',
			...options
		});
	}

	/**
	 * User Details
	 * reads the details of an individual user
	 *
	 * Arguments:
	 * user_id {int} -- the id of the user to read
	 * db {DatabaseRequired} -- the database session
	 *
	 * Raises:
	 * HTTPNotFound: the user does not exist
	 *
	 * Returns:
	 * UserDetailsResponse -- the details of the individual user
	 */
	public static userDetails<ThrowOnError extends boolean = false>(
		options: Options<UserDetailsData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			UserDetailsResponse2,
			UserDetailsError,
			ThrowOnError
		>({
			url: '/users/details/{user_id}/',
			...options
		});
	}

	/**
	 * Delete User
	 * Deletes a user given an existing user ID
	 *
	 * Arguments:
	 * user_id {int} -- the ID of the user to be deleted
	 * db {requires_db} -- a database session
	 * admin {admin_required} -- an admin user, ensures the Admin isn't deleting
	 * themselves
	 * Returns:
	 * ResponseMessage -- A message indicating the deletion was successful
	 */
	public static deleteUser<ThrowOnError extends boolean = false>(
		options: Options<DeleteUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).delete<
			DeleteUserResponse,
			DeleteUserError,
			ThrowOnError
		>({
			url: '/users/{user_id}/',
			...options
		});
	}

	/**
	 * Read User
	 * Reads a user with 'no read up' i.e a user cannot read a user with a
	 * higher role / permission
	 *
	 * Arguments:
	 * user_id {int} -- the id of the user to read
	 * db {requires_db} -- the database session
	 * reader {role_required} -- the "reader" or user making the request
	 *
	 * Raises:
	 * HTTPNotFound: The user does not exist
	 * HTTPForbidden: The user does not have permission to read the user
	 *
	 * Returns:
	 * UserResponse -- The user attempting to be read
	 */
	public static readUser<ThrowOnError extends boolean = false>(
		options: Options<ReadUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<ReadUserResponse, ReadUserError, ThrowOnError>({
			url: '/users/{user_id}/',
			...options
		});
	}

	/**
	 * Update User
	 * updates the user given an id and uses the schema to update the user's data
	 *
	 * Arguments:
	 * user_id {int} -- user id of the user to update
	 * update_schema {UpdateUser} -- the request body schema
	 * db {AsyncSession} -- the database session
	 * Returns:
	 * UserResponse -- the updated user
	 */
	public static updateUser<ThrowOnError extends boolean = false>(
		options: Options<UpdateUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).patch<
			UpdateUserResponse,
			UpdateUserError,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/users/{user_id}/',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}
}

export class EventLogsService {
	/**
	 * Summary
	 * returns a summary of recent event logs
	 * Arguments:
	 * log_service {LogServiceDep}
	 * Returns:
	 * LogMetaData
	 */
	public static summary<ThrowOnError extends boolean = false>(
		options?: Options<SummaryData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<SummaryResponse, unknown, ThrowOnError>({
			url: '/logs/summary/',
			...options
		});
	}

	/**
	 * Search
	 * Searches the logs based on the query parameters
	 * Arguments:
	 * query_params {Annotated[LogQueryParams, Query} -- the query params
	 * log_service {LogServiceDep} -- the log service dep
	 * Raises:
	 * HTTPNotFound: if no logs are found matching the query parameters
	 * Returns:
	 * LogQueryResponse -- the logs that match the query parameters
	 */
	public static search<ThrowOnError extends boolean = false>(
		options?: Options<SearchData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<SearchResponse, SearchError, ThrowOnError>({
			url: '/logs/search/',
			...options
		});
	}

	/**
	 * Logs From Today
	 * Given a query filter, returns the logs from today that match the filter
	 *
	 * Arguments:
	 * query_filter {Annotated[LogQueryParams, Query} the query params
	 * log_service {LogServiceDep} -- the log service dep
	 *
	 * Raises:
	 * HTTPNotFound: if no logs are found matching the query parameters
	 *
	 * Returns:
	 * LogQueryResponse -- the logs that match the query parameters
	 */
	public static logsFromToday<ThrowOnError extends boolean = false>(
		options?: Options<LogsFromTodayData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			LogsFromTodayResponse,
			LogsFromTodayError,
			ThrowOnError
		>({
			url: '/logs/today/',
			...options
		});
	}
}

export class OpenstackDatasourceService {
	/**
	 * Get All Openstack Sources
	 * 'Reads all the openstack datasources
	 * Arguments:
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 * Returns:
	 * OpenstackListResponse -- the list of openstack datasources
	 */
	public static getAllOpenstackSources<ThrowOnError extends boolean = false>(
		options?: Options<GetAllOpenstackSourcesData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetAllOpenstackSourcesResponse,
			unknown,
			ThrowOnError
		>({
			url: '/datasources/openstack/',
			...options
		});
	}

	/**
	 * Create Openstack Datasource
	 * Creates a new openstack datasource
	 *
	 * Arguments:
	 * openstack_data {Annotated[OpenstackCreateForm, Form} -- the openstack datasource data
	 * openstack_controller {OpenstackControllerDep} -- the openstack controller dependency
	 *
	 * Returns:
	 * OpenstackRead -- the created openstack datasource
	 */
	public static createOpenstackDatasource<ThrowOnError extends boolean = false>(
		options: Options<CreateOpenstackDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			CreateOpenstackDatasourceResponse,
			CreateOpenstackDatasourceError,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/datasources/openstack/',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}

	/**
	 * Get Openstack Details
	 * Reads the details of an openstack datasource, (i.e w/ the password)
	 *
	 * Arguments:
	 * source_id {PathID} -- the datasource id
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * OpenstackProtectedRead -- the openstack datasource details
	 */
	public static getOpenstackDetails<ThrowOnError extends boolean = false>(
		options: Options<GetOpenstackDetailsData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			GetOpenstackDetailsResponse,
			GetOpenstackDetailsError,
			ThrowOnError
		>({
			url: '/datasources/openstack/{source_id}/protected',
			...options
		});
	}

	/**
	 * Toggle Openstack Datasource
	 * toggles the enabled datasource given it's ID, a datasource that is already enabled
	 * cannot be disabled. When a disabled datasource is toggled, it will be enabled and the
	 * previously enabled datasource will be disabled
	 *
	 * Arguments:
	 * source_id {PathID} -- the ID of the openstack datasource to toggle
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * OpenstackRead -- the updated openstack datasource
	 */
	public static toggleOpenstackDatasource<ThrowOnError extends boolean = false>(
		options: Options<ToggleOpenstackDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			ToggleOpenstackDatasourceResponse,
			ToggleOpenstackDatasourceError,
			ThrowOnError
		>({
			url: '/datasources/openstack/toggle/{source_id}',
			...options
		});
	}

	/**
	 * Test Openstack Connection
	 * Tests the connection to the openstack datasource
	 *
	 * Arguments:
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GenericAPIResponse -- the api response with the details on the connection attempt
	 */
	public static testOpenstackConnection<ThrowOnError extends boolean = false>(
		options?: Options<TestOpenstackConnectionData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			TestOpenstackConnectionResponse,
			unknown,
			ThrowOnError
		>({
			url: '/datasources/openstack/test',
			...options
		});
	}

	/**
	 * Test Openstack Datasource
	 * Tests the connection to the openstack datasource by ID
	 *
	 * Arguments:
	 * source_id {PathID} -- the ID of the datasource
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GenericAPIResponse -- the api response with the details on the connection attempt
	 */
	public static testOpenstackDatasource<ThrowOnError extends boolean = false>(
		options: Options<TestOpenstackDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			TestOpenstackDatasourceResponse,
			TestOpenstackDatasourceError,
			ThrowOnError
		>({
			url: '/datasources/openstack/test/{source_id}',
			...options
		});
	}

	/**
	 * Delete Openstack Source
	 */
	public static deleteOpenstackSource<ThrowOnError extends boolean = false>(
		options: Options<DeleteOpenstackSourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).delete<
			DeleteOpenstackSourceResponse,
			DeleteOpenstackSourceError,
			ThrowOnError
		>({
			url: '/datasources/openstack/{source_id}',
			...options
		});
	}

	/**
	 * Get Openstack Source
	 * Reads an openstack datasource by ID
	 *
	 * Arguments:
	 * source_id {PathID} -- The ID of the datasource
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * OpenstackRead -- the openstack datasource
	 */
	public static getOpenstackSource<ThrowOnError extends boolean = false>(
		options: Options<GetOpenstackSourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			GetOpenstackSourceResponse,
			GetOpenstackSourceError,
			ThrowOnError
		>({
			url: '/datasources/openstack/{source_id}',
			...options
		});
	}

	/**
	 * Update Openstack Source
	 * Updates an openstack datasource by ID
	 *
	 * Arguments:
	 * source_id {PathID} -- The ID of the datasource
	 * openstack_data {Annotated[OpenstackCreateForm, Form} -- the updated data
	 * openstack_controller {OpenstackControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * OpenstackRead -- the resulting updated datasource
	 */
	public static updateOpenstackSource<ThrowOnError extends boolean = false>(
		options: Options<UpdateOpenstackSourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).patch<
			UpdateOpenstackSourceResponse,
			UpdateOpenstackSourceError,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/datasources/openstack/{source_id}',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}
}

export class GuacDatasourceService {
	/**
	 * Get All Guacamole Sources
	 * returns a list of all the Guacamole datasources in the system
	 * Arguments:
	 * guac_controller {GuacControllerDep} -- the controller
	 *
	 * Returns:
	 * GuacamoleListResponse -- the response model
	 */
	public static getAllGuacamoleSources<ThrowOnError extends boolean = false>(
		options?: Options<GetAllGuacamoleSourcesData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetAllGuacamoleSourcesResponse,
			unknown,
			ThrowOnError
		>({
			url: '/datasources/guacamole/',
			...options
		});
	}

	/**
	 * Create Guacamole Datasource
	 * Given a form with the data to create a Guacamole datasource and an admin
	 * user with the proper permissions, creates a new Guacamole datasource.
	 *
	 * Arguments:
	 * guac_create_data {Annotated[GuacamoleCreateForm, Form} -- the form with the data to create a Guacamole datasource
	 * guac_controller {GuacControllerDep} -- the controller to use to create the Guacamole datasource
	 *
	 * Returns:
	 * GuacamoleRead -- the resulting the datasource
	 */
	public static createGuacamoleDatasource<ThrowOnError extends boolean = false>(
		options: Options<CreateGuacamoleDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			CreateGuacamoleDatasourceResponse,
			CreateGuacamoleDatasourceError,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/datasources/guacamole/',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}

	/**
	 * Get Guacamole Details
	 * allows the reader to see the password field for the datasource
	 *
	 * Arguments:
	 * source_id {PathID} -- the ID of the datasource to read
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GuacamoleProtectedRead -- the complete datasource model
	 */
	public static getGuacamoleDetails<ThrowOnError extends boolean = false>(
		options: Options<GetGuacamoleDetailsData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			GetGuacamoleDetailsResponse,
			GetGuacamoleDetailsError,
			ThrowOnError
		>({
			url: '/datasources/guacamole/details/{source_id}',
			...options
		});
	}

	/**
	 * Toggle Guacamole Datasource
	 * given an ID of a Guacamole datasource, toggles the enabled datasource if possible
	 *
	 * Arguments:
	 * source_id {int} -- ID of the datasource to toggle
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GuacamoleRead -- the resulting datasource model
	 */
	public static toggleGuacamoleDatasource<ThrowOnError extends boolean = false>(
		options: Options<ToggleGuacamoleDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			ToggleGuacamoleDatasourceResponse,
			ToggleGuacamoleDatasourceError,
			ThrowOnError
		>({
			url: '/datasources/guacamole/toggle/{source_id}/',
			...options
		});
	}

	/**
	 * Test Guacamole Connection
	 * tests the connection to the Guacamole datasource and returns a message
	 * to the user if the connection was successful or not
	 *
	 * Arguments:
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GenericAPIResponse -- the API response model with a message and the result of the connection test
	 */
	public static testGuacamoleConnection<ThrowOnError extends boolean = false>(
		options?: Options<TestGuacamoleConnectionData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			TestGuacamoleConnectionResponse,
			unknown,
			ThrowOnError
		>({
			url: '/datasources/guacamole/test',
			...options
		});
	}

	/**
	 * Test Guacamole Datasource
	 * attempts to create a session to the Guacamole datasource and whether the
	 * connection was successful or not, returns a message to the user
	 * Arguments:
	 * source_id {PathID} -- the ID of the Guacamole datasource to test
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 * Returns:
	 * GenericAPIResponse -- the API response model with a message and the result of the connection test
	 */
	public static testGuacamoleDatasource<ThrowOnError extends boolean = false>(
		options: Options<TestGuacamoleDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			TestGuacamoleDatasourceResponse,
			TestGuacamoleDatasourceError,
			ThrowOnError
		>({
			url: '/datasources/guacamole/test/{source_id}',
			...options
		});
	}

	/**
	 * Delete Guacamole Source
	 * deletes a Guacamole datasource by its ID
	 *
	 * Arguments:
	 * source_id {PathID} -- the ID of the datasource to delete
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GenericAPIResponse -- the API response model with a message and the ID of the deleted datasource
	 */
	public static deleteGuacamoleSource<ThrowOnError extends boolean = false>(
		options: Options<DeleteGuacamoleSourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).delete<
			DeleteGuacamoleSourceResponse,
			DeleteGuacamoleSourceError,
			ThrowOnError
		>({
			url: '/datasources/guacamole/{source_id}/',
			...options
		});
	}

	/**
	 * Read Guacamole Source
	 * returns the Guacamole datasource model by its ID, excluding the password field
	 *
	 * Arguments:
	 * source_id {PathID} -- the ID of the datasource to read
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GuacamoleRead -- the resulting datasource model
	 */
	public static readGuacamoleSource<ThrowOnError extends boolean = false>(
		options: Options<ReadGuacamoleSourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			ReadGuacamoleSourceResponse,
			ReadGuacamoleSourceError,
			ThrowOnError
		>({
			url: '/datasources/guacamole/{source_id}/',
			...options
		});
	}

	/**
	 * Update Guacamole Source
	 * updates a Guacamole datasource by its ID
	 *
	 * Arguments:
	 * source_id {PathID} -- the ID of the datasource to update
	 * guac_update_data {Annotated[GuacamoleUpdateForm, Form} -- the form with the data to update the Guacamole
	 * datasource.
	 * guac_controller {GuacControllerDep} -- the controller dependency
	 *
	 * Returns:
	 * GuacamoleRead -- the model updated
	 */
	public static updateGuacamoleSource<ThrowOnError extends boolean = false>(
		options: Options<UpdateGuacamoleSourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).patch<
			UpdateGuacamoleSourceResponse,
			UpdateGuacamoleSourceError,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/datasources/guacamole/{source_id}/',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options?.headers
			}
		});
	}
}
