// This file is auto-generated by @hey-api/openapi-ts

export type ApiListResponseUserDetailsResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<UserDetailsResponse>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

export type ApiListResponseUserResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<UserResponse>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * reprents the pagination metadata for a query
 * to help the frontend
 */
export type ApiQueryResult = {
	/**
	 * The total number of records from the returned query
	 */
	total: number;
	/**
	 * The number of records to skip for the next 'page' of the query
	 */
	nextSkip: number;
	/**
	 * The number of pages of results from the query
	 */
	totalPages: number;
	/**
	 * The total number of items returned in the query
	 */
	totalItems: number;
};

/**
 * The base model for all app authentication forms
 */
export type AuthForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
};

/**
 * form to create a user
 */
export type CreateUserForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type EventLogLevel = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * represents the total number of logs for each log level
 */
export type EventLogLevelTotals = {
	info: number;
	warning: number;
	error: number;
	critical: number;
};

/**
 * represents a event log returned from the API
 */
export type EventLogRead = {
	logLevel: EventLogLevel;
	message: string;
	timestamp: string;
};

/**
 * Generic API response model
 */
export type GenericApiResponse = {
	data: {
		[key: string]: unknown;
	};
	/**
	 * The message returned by the API
	 */
	message: string;
};

/**
 * The form for creating a new Guacamole datasource
 */
export type GuacamoleCreateForm = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The password for the datasource
	 */
	password: string;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint: string;
};

/**
 * The response for listing Guacamole datasources
 */
export type GuacamoleListResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	data: Array<GuacamoleRead>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * A Guacamole datasource schema with protected fields
 */
export type GuacamoleProtectedRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint: string;
	/**
	 * The password for the Guacamole datasource
	 */
	password: string;
};

/**
 * A guacamole datasource schema from the DB
 */
export type GuacamoleRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint: string;
};

/**
 * The form for updating a Guacamole datasource
 */
export type GuacamoleUpdateForm = {
	/**
	 * The username for the datasource
	 */
	username: string | null;
	/**
	 * The password for the Guacamole datasource
	 */
	password?: string | null;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource?: string | null;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint?: string | null;
};

export type HttpValidationError = {
	detail?: Array<ValidationError>;
};

/**
 * represents the most recent logs for the critical and error log levels
 */
export type LastLogs = {
	lastCritical: EventLogRead | null;
	lastError: EventLogRead | null;
};

/**
 * the event log meta data to display in a dashboard
 */
export type LogMetaData = {
	/**
	 * The total count of each log level
	 */
	totals: EventLogLevelTotals;
	/**
	 * The last error and critical log metadata
	 */
	previousLogs: LastLogs;
};

/**
 * the logs returned from a query
 */
export type LogQueryResponse = {
	/**
	 * The results of the query of type SchemaT
	 */
	results: Array<EventLogRead>;
	/**
	 * Metadata for the query results for the frontend to handle
	 */
	pageContext: ApiQueryResult;
};

export type OpenstackConnectionResults = {
	message: string;
	success: boolean;
	error: string | null;
};

/**
 * The form for creating a new Openstack datasource
 */
export type OpenstackCreateForm = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The password for the datasource
	 */
	password: string;
	/**
	 * The URL for the Openstack authentication
	 */
	authUrl: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

export type OpenstackListResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	data: Array<OpenstackRead>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * A Openstack datasource schema with protected fields
 */
export type OpenstackProtectedRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The URL for the Openstack authentication
	 */
	authUrl: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
	/**
	 * The password for the Openstack datasource
	 */
	password: string;
};

/**
 * A Openstack datasource schema from the DB
 */
export type OpenstackRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The URL for the Openstack authentication
	 */
	authUrl: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

export type Role = 'admin' | 'user' | 'read_only';

/**
 * form to update a user
 */
export type UpdateUserForm = {
	username?: string | null;
	password?: string | null;
	role?: Role | null;
};

/**
 * The response model for the user; provides all the information
 */
export type UserDetailsResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
	/**
	 * The date the user was created
	 */
	createdAt: string;
	/**
	 * The date the user was last updated
	 */
	updatedAt: string;
};

/**
 * The response model for the user; only provides the essential information
 */
export type UserResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type LoginData = {
	body: AuthForm;
	path?: never;
	query?: never;
	url: '/auth/login/';
};

export type LoginErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type LogoutData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/logout/';
};

export type LogoutResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type CurrentUserData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/me/';
};

export type CurrentUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type GetAllUsersData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/';
};

export type GetAllUsersResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserResponse;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
	body: CreateUserForm;
	path?: never;
	query?: never;
	url: '/users/';
};

export type CreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
	/**
	 * Successful Response
	 */
	201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type AllUserDetailsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/details';
};

export type AllUserDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserDetailsResponse;
};

export type AllUserDetailsResponse = AllUserDetailsResponses[keyof AllUserDetailsResponses];

export type UserDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/details/{user_id}/';
};

export type UserDetailsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserDetailsError = UserDetailsErrors[keyof UserDetailsErrors];

export type UserDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: UserDetailsResponse;
};

export type UserDetailsResponse2 = UserDetailsResponses[keyof UserDetailsResponses];

export type DeleteUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type DeleteUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type ReadUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ReadUserError = ReadUserErrors[keyof ReadUserErrors];

export type ReadUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type UpdateUserData = {
	body: UpdateUserForm;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type UpdateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
	/**
	 * Successful Response
	 */
	202: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SummaryData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/logs/summary/';
};

export type SummaryResponses = {
	/**
	 * Successful Response
	 */
	200: LogMetaData;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SearchData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/search/';
};

export type SearchErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type LogsFromTodayData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/today/';
};

export type LogsFromTodayErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LogsFromTodayError = LogsFromTodayErrors[keyof LogsFromTodayErrors];

export type LogsFromTodayResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type LogsFromTodayResponse = LogsFromTodayResponses[keyof LogsFromTodayResponses];

export type GetAllOpenstackSourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/openstack/';
};

export type GetAllOpenstackSourcesResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackListResponse;
};

export type GetAllOpenstackSourcesResponse =
	GetAllOpenstackSourcesResponses[keyof GetAllOpenstackSourcesResponses];

export type CreateOpenstackDatasourceData = {
	body: OpenstackCreateForm;
	path?: never;
	query?: never;
	url: '/datasources/openstack/';
};

export type CreateOpenstackDatasourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateOpenstackDatasourceError =
	CreateOpenstackDatasourceErrors[keyof CreateOpenstackDatasourceErrors];

export type CreateOpenstackDatasourceResponses = {
	/**
	 * Successful Response
	 */
	201: OpenstackRead;
};

export type CreateOpenstackDatasourceResponse =
	CreateOpenstackDatasourceResponses[keyof CreateOpenstackDatasourceResponses];

export type GetOpenstackDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}/protected';
};

export type GetOpenstackDetailsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetOpenstackDetailsError = GetOpenstackDetailsErrors[keyof GetOpenstackDetailsErrors];

export type GetOpenstackDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackProtectedRead;
};

export type GetOpenstackDetailsResponse =
	GetOpenstackDetailsResponses[keyof GetOpenstackDetailsResponses];

export type ToggleOpenstackDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/toggle/{source_id}';
};

export type ToggleOpenstackDatasourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ToggleOpenstackDatasourceError =
	ToggleOpenstackDatasourceErrors[keyof ToggleOpenstackDatasourceErrors];

export type ToggleOpenstackDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type ToggleOpenstackDatasourceResponse =
	ToggleOpenstackDatasourceResponses[keyof ToggleOpenstackDatasourceResponses];

export type TestOpenstackConnectionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/openstack/test';
};

export type TestOpenstackConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackConnectionResults;
};

export type TestOpenstackConnectionResponse =
	TestOpenstackConnectionResponses[keyof TestOpenstackConnectionResponses];

export type TestOpenstackDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/test/{source_id}';
};

export type TestOpenstackDatasourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type TestOpenstackDatasourceError =
	TestOpenstackDatasourceErrors[keyof TestOpenstackDatasourceErrors];

export type TestOpenstackDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackConnectionResults;
};

export type TestOpenstackDatasourceResponse =
	TestOpenstackDatasourceResponses[keyof TestOpenstackDatasourceResponses];

export type DeleteOpenstackSourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}';
};

export type DeleteOpenstackSourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteOpenstackSourceError =
	DeleteOpenstackSourceErrors[keyof DeleteOpenstackSourceErrors];

export type DeleteOpenstackSourceResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteOpenstackSourceResponse =
	DeleteOpenstackSourceResponses[keyof DeleteOpenstackSourceResponses];

export type GetOpenstackSourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}';
};

export type GetOpenstackSourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetOpenstackSourceError = GetOpenstackSourceErrors[keyof GetOpenstackSourceErrors];

export type GetOpenstackSourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type GetOpenstackSourceResponse =
	GetOpenstackSourceResponses[keyof GetOpenstackSourceResponses];

export type UpdateOpenstackSourceData = {
	body: OpenstackCreateForm;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}';
};

export type UpdateOpenstackSourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateOpenstackSourceError =
	UpdateOpenstackSourceErrors[keyof UpdateOpenstackSourceErrors];

export type UpdateOpenstackSourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type UpdateOpenstackSourceResponse =
	UpdateOpenstackSourceResponses[keyof UpdateOpenstackSourceResponses];

export type GetAllGuacamoleSourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/';
};

export type GetAllGuacamoleSourcesResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleListResponse;
};

export type GetAllGuacamoleSourcesResponse =
	GetAllGuacamoleSourcesResponses[keyof GetAllGuacamoleSourcesResponses];

export type CreateGuacamoleDatasourceData = {
	body: GuacamoleCreateForm;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/';
};

export type CreateGuacamoleDatasourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateGuacamoleDatasourceError =
	CreateGuacamoleDatasourceErrors[keyof CreateGuacamoleDatasourceErrors];

export type CreateGuacamoleDatasourceResponses = {
	/**
	 * Successful Response
	 */
	201: GuacamoleRead;
};

export type CreateGuacamoleDatasourceResponse =
	CreateGuacamoleDatasourceResponses[keyof CreateGuacamoleDatasourceResponses];

export type GetGuacamoleDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/details/{source_id}';
};

export type GetGuacamoleDetailsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetGuacamoleDetailsError = GetGuacamoleDetailsErrors[keyof GetGuacamoleDetailsErrors];

export type GetGuacamoleDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleProtectedRead;
};

export type GetGuacamoleDetailsResponse =
	GetGuacamoleDetailsResponses[keyof GetGuacamoleDetailsResponses];

export type ToggleGuacamoleDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/toggle/{source_id}/';
};

export type ToggleGuacamoleDatasourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ToggleGuacamoleDatasourceError =
	ToggleGuacamoleDatasourceErrors[keyof ToggleGuacamoleDatasourceErrors];

export type ToggleGuacamoleDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type ToggleGuacamoleDatasourceResponse =
	ToggleGuacamoleDatasourceResponses[keyof ToggleGuacamoleDatasourceResponses];

export type TestGuacamoleConnectionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/test';
};

export type TestGuacamoleConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type TestGuacamoleConnectionResponse =
	TestGuacamoleConnectionResponses[keyof TestGuacamoleConnectionResponses];

export type TestGuacamoleDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/test/{source_id}';
};

export type TestGuacamoleDatasourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type TestGuacamoleDatasourceError =
	TestGuacamoleDatasourceErrors[keyof TestGuacamoleDatasourceErrors];

export type TestGuacamoleDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type TestGuacamoleDatasourceResponse =
	TestGuacamoleDatasourceResponses[keyof TestGuacamoleDatasourceResponses];

export type DeleteGuacamoleSourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type DeleteGuacamoleSourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteGuacamoleSourceError =
	DeleteGuacamoleSourceErrors[keyof DeleteGuacamoleSourceErrors];

export type DeleteGuacamoleSourceResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteGuacamoleSourceResponse =
	DeleteGuacamoleSourceResponses[keyof DeleteGuacamoleSourceResponses];

export type ReadGuacamoleSourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type ReadGuacamoleSourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ReadGuacamoleSourceError = ReadGuacamoleSourceErrors[keyof ReadGuacamoleSourceErrors];

export type ReadGuacamoleSourceResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type ReadGuacamoleSourceResponse =
	ReadGuacamoleSourceResponses[keyof ReadGuacamoleSourceResponses];

export type UpdateGuacamoleSourceData = {
	body: GuacamoleUpdateForm;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type UpdateGuacamoleSourceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateGuacamoleSourceError =
	UpdateGuacamoleSourceErrors[keyof UpdateGuacamoleSourceErrors];

export type UpdateGuacamoleSourceResponses = {
	/**
	 * Successful Response
	 */
	202: GuacamoleRead;
};

export type UpdateGuacamoleSourceResponse =
	UpdateGuacamoleSourceResponses[keyof UpdateGuacamoleSourceResponses];

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {});
};
