// This file is auto-generated by @hey-api/openapi-ts

/**
 * The response returned when an error occurs during an API request
 */
export type ApiErrorResponse = {
	/**
	 * A description of the error that occured
	 */
	message: string;
	success?: boolean;
	/**
	 * An optional label for the error for errors that share status codes but have different meanings
	 */
	error_label?: string | null;
};

/**
 * The response after a successful login that contains the signed API key and
 * the identity of the client
 */
export type ApiKeyResponse = {
	/**
	 * the signed API key to be issued to the client
	 */
	apiKey: string;
	/**
	 * the identity of the user associated with the API key
	 */
	identity: KeyBearerIdentity;
};

export type ApiListResponseUserDetailsResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<UserDetailsResponse>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

export type ApiListResponseUserResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<UserResponse>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * reprents the pagination metadata for a query
 * to help the frontend
 */
export type ApiQueryResult = {
	/**
	 * The total number of records from the returned query
	 */
	total: number;
	/**
	 * The number of records to skip for the next 'page' of the query
	 */
	nextSkip: number;
	/**
	 * The number of pages of results from the query
	 */
	totalPages: number;
	/**
	 * The total number of items returned in the query
	 */
	totalItems: number;
};

/**
 * The base model for all app authentication forms
 */
export type AuthForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
};

/**
 * form to create a user
 */
export type CreateUserForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type EventLogLevel = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * represents the total number of logs for each log level
 */
export type EventLogLevelTotals = {
	info: number;
	warning: number;
	error: number;
	critical: number;
};

/**
 * represents a event log returned from the API
 */
export type EventLogRead = {
	logLevel: EventLogLevel;
	message: string;
	timestamp: string;
};

/**
 * Generic API response model
 */
export type GenericApiResponse = {
	data: {
		[key: string]: unknown;
	};
	/**
	 * The message returned by the API
	 */
	message: string;
};

/**
 * The form for creating a new Guacamole datasource
 */
export type GuacamoleCreateForm = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The password for the datasource
	 */
	password: string;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint: string;
};

/**
 * The response for listing Guacamole datasources
 */
export type GuacamoleListResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	data: Array<GuacamoleRead>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * A Guacamole datasource schema with protected fields
 */
export type GuacamoleProtectedRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint: string;
	/**
	 * The password for the Guacamole datasource
	 */
	password: string;
};

/**
 * A guacamole datasource schema from the DB
 */
export type GuacamoleRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint: string;
};

/**
 * The form for updating a Guacamole datasource
 */
export type GuacamoleUpdateForm = {
	/**
	 * The username for the datasource
	 */
	username: string | null;
	/**
	 * The password for the Guacamole datasource
	 */
	password?: string | null;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource?: string | null;
	/**
	 * The URL for the Guacamole datasource
	 */
	endpoint?: string | null;
};

export type HttpValidationError = {
	detail?: Array<ValidationError>;
};

/**
 * Information about the user assigned an APIKey
 */
export type KeyBearerIdentity = {
	/**
	 * The username of the users session
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: string;
};

/**
 * represents the most recent logs for the critical and error log levels
 */
export type LastLogs = {
	lastCritical: EventLogRead | null;
	lastError: EventLogRead | null;
};

/**
 * the event log meta data to display in a dashboard
 */
export type LogMetaData = {
	/**
	 * The total count of each log level
	 */
	totals: EventLogLevelTotals;
	/**
	 * The last error and critical log metadata
	 */
	previousLogs: LastLogs;
};

/**
 * the logs returned from a query
 */
export type LogQueryResponse = {
	/**
	 * The results of the query of type SchemaT
	 */
	results: Array<EventLogRead>;
	/**
	 * Metadata for the query results for the frontend to handle
	 */
	pageContext: ApiQueryResult;
};

/**
 * A model to represent the response after a successful logout
 */
export type LogoutResponse = {
	/**
	 * the message to be sent to the client after a successful logout
	 */
	message?: string;
	success?: boolean;
};

export type OpenstackConnectionResults = {
	message: string;
	success: boolean;
	error: string | null;
};

/**
 * The form for creating a new Openstack datasource
 */
export type OpenstackCreateForm = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The password for the datasource
	 */
	password: string;
	/**
	 * The URL for the Openstack authentication
	 */
	authUrl: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

export type OpenstackListResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	data: Array<OpenstackRead>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * A Openstack datasource schema with protected fields
 */
export type OpenstackProtectedRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The URL for the Openstack authentication
	 */
	authUrl: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
	/**
	 * The password for the Openstack datasource
	 */
	password: string;
};

/**
 * A Openstack datasource schema from the DB
 */
export type OpenstackRead = {
	id: number;
	username: string;
	enabled: boolean;
	/**
	 * The URL for the Openstack authentication
	 */
	authUrl: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

export type Role = 'admin' | 'user' | 'read_only';

/**
 * form to update a user
 */
export type UpdateUserForm = {
	username?: string | null;
	password?: string | null;
	role?: Role | null;
};

/**
 * The response model for the user; provides all the information
 */
export type UserDetailsResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
	/**
	 * The date the user was created
	 */
	createdAt: string;
	/**
	 * The date the user was last updated
	 */
	updatedAt: string;
};

/**
 * The response model for the user; only provides the essential information
 */
export type UserResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type ValidationError = {
	message?: string;
	success?: boolean;
	/**
	 * An optional label for the error for errors that share status codes but have different meanings
	 */
	error_label?: string | null;
	errors: Array<PydanticError>;
};

export type LoginUserData = {
	body: AuthForm;
	path?: never;
	query?: never;
	url: '/auth/';
};

export type LoginUserErrors = {
	/**
	 * When the user provides invalid credentials
	 */
	401: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
	/**
	 * Successful Response
	 */
	200: ApiKeyResponse;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type LogoutUserData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/logout/';
};

export type LogoutUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type LogoutUserError = LogoutUserErrors[keyof LogoutUserErrors];

export type LogoutUserResponses = {
	/**
	 * Successful Response
	 */
	200: LogoutResponse;
};

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses];

export type GetCurrentUserData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/me/';
};

export type GetCurrentUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetAllUsersData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/';
};

export type GetAllUsersErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
};

export type GetAllUsersError = GetAllUsersErrors[keyof GetAllUsersErrors];

export type GetAllUsersResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserResponse;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
	body: CreateUserForm;
	path?: never;
	query?: never;
	url: '/users/';
};

export type CreateUserErrors = {
	/**
	 * The username provided is taken.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
	/**
	 * Successful Response
	 */
	201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetAllDetailsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/details';
};

export type GetAllDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type GetAllDetailsError = GetAllDetailsErrors[keyof GetAllDetailsErrors];

export type GetAllDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserDetailsResponse;
};

export type GetAllDetailsResponse = GetAllDetailsResponses[keyof GetAllDetailsResponses];

export type GetUserDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/details/{user_id}/';
};

export type GetUserDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type GetUserDetailsError = GetUserDetailsErrors[keyof GetUserDetailsErrors];

export type GetUserDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: UserDetailsResponse;
};

export type GetUserDetailsResponse = GetUserDetailsResponses[keyof GetUserDetailsResponses];

export type DeleteUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type DeleteUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * An admin cannot delete their own account.
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type ReadUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ReadUserError = ReadUserErrors[keyof ReadUserErrors];

export type ReadUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type UpdateUserData = {
	body: UpdateUserForm;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type UpdateUserErrors = {
	/**
	 * The username provided is taken.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
	/**
	 * Successful Response
	 */
	202: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SummaryData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/logs/summary/';
};

export type SummaryErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type SummaryError = SummaryErrors[keyof SummaryErrors];

export type SummaryResponses = {
	/**
	 * Successful Response
	 */
	200: LogMetaData;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SearchData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/search/';
};

export type SearchErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type LogsFromTodayData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/today/';
};

export type LogsFromTodayErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type LogsFromTodayError = LogsFromTodayErrors[keyof LogsFromTodayErrors];

export type LogsFromTodayResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type LogsFromTodayResponse = LogsFromTodayResponses[keyof LogsFromTodayResponses];

export type GetAllDatasourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/openstack/';
};

export type GetAllDatasourcesErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
};

export type GetAllDatasourcesError = GetAllDatasourcesErrors[keyof GetAllDatasourcesErrors];

export type GetAllDatasourcesResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackListResponse;
};

export type GetAllDatasourcesResponse =
	GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
	body: OpenstackCreateForm;
	path?: never;
	query?: never;
	url: '/datasources/openstack/';
};

export type CreateDatasourceErrors = {
	/**
	 * When missing both project name and ID
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	201: OpenstackRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type GetDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}/details';
};

export type GetDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type GetDetailsError = GetDetailsErrors[keyof GetDetailsErrors];

export type GetDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackProtectedRead;
};

export type GetDetailsResponse = GetDetailsResponses[keyof GetDetailsResponses];

export type ToggleDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/toggle/{source_id}';
};

export type ToggleDatasourceErrors = {
	/**
	 * When the datasource cannot be toggled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * When the datasource does not exist
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ToggleDatasourceError = ToggleDatasourceErrors[keyof ToggleDatasourceErrors];

export type ToggleDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type ToggleDatasourceResponse = ToggleDatasourceResponses[keyof ToggleDatasourceResponses];

export type TestConnectionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/openstack/test';
};

export type TestConnectionErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackConnectionResults;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type TestDatasourceConnectionData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/test/{source_id}';
};

export type TestDatasourceConnectionErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type TestDatasourceConnectionError =
	TestDatasourceConnectionErrors[keyof TestDatasourceConnectionErrors];

export type TestDatasourceConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackConnectionResults;
};

export type TestDatasourceConnectionResponse =
	TestDatasourceConnectionResponses[keyof TestDatasourceConnectionResponses];

export type DeleteDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}';
};

export type DeleteDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DeleteDatasourceError = DeleteDatasourceErrors[keyof DeleteDatasourceErrors];

export type DeleteDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteDatasourceResponse = DeleteDatasourceResponses[keyof DeleteDatasourceResponses];

export type GetDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}';
};

export type GetDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type GetDatasourceError = GetDatasourceErrors[keyof GetDatasourceErrors];

export type GetDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type GetDatasourceResponse = GetDatasourceResponses[keyof GetDatasourceResponses];

export type UpdateDatasourceData = {
	body: OpenstackCreateForm;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}';
};

export type UpdateDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type UpdateDatasourceError = UpdateDatasourceErrors[keyof UpdateDatasourceErrors];

export type UpdateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type UpdateDatasourceResponse = UpdateDatasourceResponses[keyof UpdateDatasourceResponses];

export type GetAllDatasourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/';
};

export type GetAllDatasourcesErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type GetAllDatasourcesError = GetAllDatasourcesErrors[keyof GetAllDatasourcesErrors];

export type GetAllDatasourcesResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleListResponse;
};

export type GetAllDatasourcesResponse =
	GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
	body: GuacamoleCreateForm;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/';
};

export type CreateDatasourceErrors = {
	/**
	 * When no password is provided
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	201: GuacamoleRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type GetDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/details/{source_id}';
};

export type GetDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type GetDetailsError = GetDetailsErrors[keyof GetDetailsErrors];

export type GetDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleProtectedRead;
};

export type GetDetailsResponse = GetDetailsResponses[keyof GetDetailsResponses];

export type ToggleDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/toggle/{source_id}/';
};

export type ToggleDatasourceErrors = {
	/**
	 * When the datasource cannot be toggled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * When the datasource does not exist
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ToggleDatasourceError = ToggleDatasourceErrors[keyof ToggleDatasourceErrors];

export type ToggleDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type ToggleDatasourceResponse = ToggleDatasourceResponses[keyof ToggleDatasourceResponses];

export type TestConnectionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/test';
};

export type TestConnectionErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type TestDatasourceConnectionData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/test/{source_id}';
};

export type TestDatasourceConnectionErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type TestDatasourceConnectionError =
	TestDatasourceConnectionErrors[keyof TestDatasourceConnectionErrors];

export type TestDatasourceConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type TestDatasourceConnectionResponse =
	TestDatasourceConnectionResponses[keyof TestDatasourceConnectionResponses];

export type DeleteDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type DeleteDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DeleteDatasourceError = DeleteDatasourceErrors[keyof DeleteDatasourceErrors];

export type DeleteDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteDatasourceResponse = DeleteDatasourceResponses[keyof DeleteDatasourceResponses];

export type GetDatasourceData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type GetDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type GetDatasourceError = GetDatasourceErrors[keyof GetDatasourceErrors];

export type GetDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type GetDatasourceResponse = GetDatasourceResponses[keyof GetDatasourceResponses];

export type UpdateDatasourceData = {
	body: GuacamoleUpdateForm;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type UpdateDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type UpdateDatasourceError = UpdateDatasourceErrors[keyof UpdateDatasourceErrors];

export type UpdateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	202: GuacamoleRead;
};

export type UpdateDatasourceResponse = UpdateDatasourceResponses[keyof UpdateDatasourceResponses];

export type ClientOptions = {
	baseURL: `${string}://${string}` | (string & {});
};
