// This file is auto-generated by @hey-api/openapi-ts

export const APIErrorResponseSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
			description: 'A description of the error that occured'
		},
		success: {
			type: 'boolean',
			title: 'Success',
			default: false
		},
		error_label: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Error Label',
			description:
				'An optional label for the error for errors that share status codes but have different meanings'
		}
	},
	type: 'object',
	required: ['message'],
	title: 'APIErrorResponse',
	description: 'The response returned when an error occurs during an API request'
} as const;

export const APIKeyHealthSchema = {
	properties: {
		maxAgeAt: {
			type: 'string',
			format: 'date-time',
			title: 'Maxageat',
			description: 'the time the session expires in seconds ( time.tme() )'
		},
		expiresNext: {
			type: 'string',
			format: 'date-time',
			title: 'Expiresnext',
			description: 'the time the session expires in seconds ( time.tme() )'
		},
		issuedAt: {
			type: 'string',
			format: 'date-time',
			title: 'Issuedat',
			description: 'the time the session was created in seconds ( time.tme() )'
		}
	},
	type: 'object',
	required: ['maxAgeAt', 'expiresNext', 'issuedAt'],
	title: 'APIKeyHealth'
} as const;

export const APIKeyResponseSchema = {
	properties: {
		apiKey: {
			type: 'string',
			title: 'Apikey',
			description: 'the signed API key to be issued to the client'
		},
		identity: {
			$ref: '#/components/schemas/KeyBearerIdentity',
			description: 'the identity of the user associated with the API key'
		}
	},
	type: 'object',
	required: ['apiKey', 'identity'],
	title: 'APIKeyResponse',
	description: `The response after a successful login that contains the signed API key and
the identity of the client `
} as const;

export const APIListResponse_GuacamoleRead_Schema = {
	properties: {
		total: {
			type: 'integer',
			title: 'Total',
			description: 'The total number of items in the list'
		},
		data: {
			items: {
				$ref: '#/components/schemas/GuacamoleRead'
			},
			type: 'array',
			title: 'Data',
			description: 'The list of items returned by the API'
		},
		empty: {
			type: 'boolean',
			title: 'Empty',
			description: 'Whether the list is empty'
		}
	},
	type: 'object',
	required: ['total', 'data', 'empty'],
	title: 'APIListResponse[GuacamoleRead]'
} as const;

export const APIListResponse_OpenstackRead_Schema = {
	properties: {
		total: {
			type: 'integer',
			title: 'Total',
			description: 'The total number of items in the list'
		},
		data: {
			items: {
				$ref: '#/components/schemas/OpenstackRead'
			},
			type: 'array',
			title: 'Data',
			description: 'The list of items returned by the API'
		},
		empty: {
			type: 'boolean',
			title: 'Empty',
			description: 'Whether the list is empty'
		}
	},
	type: 'object',
	required: ['total', 'data', 'empty'],
	title: 'APIListResponse[OpenstackRead]'
} as const;

export const APIListResponse_UserDetailsResponse_Schema = {
	properties: {
		total: {
			type: 'integer',
			title: 'Total',
			description: 'The total number of items in the list'
		},
		data: {
			items: {
				$ref: '#/components/schemas/UserDetailsResponse'
			},
			type: 'array',
			title: 'Data',
			description: 'The list of items returned by the API'
		},
		empty: {
			type: 'boolean',
			title: 'Empty',
			description: 'Whether the list is empty'
		}
	},
	type: 'object',
	required: ['total', 'data', 'empty'],
	title: 'APIListResponse[UserDetailsResponse]'
} as const;

export const APIListResponse_UserResponse_Schema = {
	properties: {
		total: {
			type: 'integer',
			title: 'Total',
			description: 'The total number of items in the list'
		},
		data: {
			items: {
				$ref: '#/components/schemas/UserResponse'
			},
			type: 'array',
			title: 'Data',
			description: 'The list of items returned by the API'
		},
		empty: {
			type: 'boolean',
			title: 'Empty',
			description: 'Whether the list is empty'
		}
	},
	type: 'object',
	required: ['total', 'data', 'empty'],
	title: 'APIListResponse[UserResponse]'
} as const;

export const APIQueryResultSchema = {
	properties: {
		total: {
			type: 'integer',
			minimum: 0,
			title: 'Total',
			description: 'The total number of records from the returned query'
		},
		nextSkip: {
			type: 'integer',
			minimum: 0,
			title: 'Nextskip',
			description: "The number of records to skip for the next 'page' of the query"
		},
		totalPages: {
			type: 'integer',
			minimum: 1,
			title: 'Totalpages',
			description: 'The number of pages of results from the query'
		},
		totalItems: {
			type: 'integer',
			minimum: 0,
			title: 'Totalitems',
			description: 'The total number of items returned in the query'
		}
	},
	type: 'object',
	required: ['total', 'nextSkip', 'totalPages', 'totalItems'],
	title: 'APIQueryResult',
	description: `reprents the pagination metadata for a query
to help the frontend`
} as const;

export const AuthContextSchema = {
	properties: {
		user: {
			$ref: '#/components/schemas/UserResponse',
			description: 'The user object'
		},
		auth: {
			$ref: '#/components/schemas/KeyContext',
			description: 'The authentication object'
		}
	},
	type: 'object',
	required: ['user', 'auth'],
	title: 'AuthContext'
} as const;

export const AuthFormSchema = {
	properties: {
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username of the user'
		},
		password: {
			type: 'string',
			title: 'Password',
			description: 'The password of the user'
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['username', 'password'],
	title: 'AuthForm',
	description: 'The base model for all app authentication forms'
} as const;

export const ConnectionTestResultSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
			description: 'The message indicating the connection result'
		},
		success: {
			type: 'boolean',
			title: 'Success',
			description: 'Whether the connection was successful'
		},
		error: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Error',
			description: 'The error message if the connection failed'
		}
	},
	type: 'object',
	required: ['message', 'success'],
	title: 'ConnectionTestResult',
	description: 'The schema for the results of testing a datasource connection'
} as const;

export const CreateUserFormSchema = {
	properties: {
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username of the user'
		},
		password: {
			type: 'string',
			title: 'Password',
			description: 'The password of the user'
		},
		role: {
			$ref: '#/components/schemas/Role',
			description: 'The role of the user'
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['username', 'password', 'role'],
	title: 'CreateUserForm',
	description: 'form to create a user'
} as const;

export const EventLogLevelSchema = {
	type: 'string',
	enum: ['INFO', 'WARNING', 'ERROR', 'CRITICAL'],
	title: 'EventLogLevel'
} as const;

export const EventLogLevelTotalsSchema = {
	properties: {
		info: {
			type: 'integer',
			title: 'Info'
		},
		warning: {
			type: 'integer',
			title: 'Warning'
		},
		error: {
			type: 'integer',
			title: 'Error'
		},
		critical: {
			type: 'integer',
			title: 'Critical'
		}
	},
	type: 'object',
	required: ['info', 'warning', 'error', 'critical'],
	title: 'EventLogLevelTotals',
	description: 'represents the total number of logs for each log level'
} as const;

export const EventLogReadSchema = {
	properties: {
		logLevel: {
			$ref: '#/components/schemas/EventLogLevel'
		},
		message: {
			type: 'string',
			title: 'Message'
		},
		timestamp: {
			type: 'string',
			format: 'date-time',
			title: 'Timestamp'
		}
	},
	type: 'object',
	required: ['logLevel', 'message', 'timestamp'],
	title: 'EventLogRead',
	description: 'represents a event log returned from the API'
} as const;

export const GenericAPIResponseSchema = {
	properties: {
		data: {
			type: 'object',
			title: 'Data'
		},
		message: {
			type: 'string',
			title: 'Message',
			description: 'The message returned by the API'
		}
	},
	type: 'object',
	required: ['data', 'message'],
	title: 'GenericAPIResponse',
	description: 'Generic API response model'
} as const;

export const GuacamoleCreateSchema = {
	properties: {
		username: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Username',
			description: 'The username for the datasource'
		},
		password: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Password',
			description: 'The password for the datasource'
		},
		endpoint: {
			type: 'string',
			title: 'Endpoint',
			description: 'The endpoint for the Saltstack datasource'
		},
		datasource: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Datasource',
			description: 'The name of the Guacamole datasource'
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['username', 'password', 'endpoint', 'datasource'],
	title: 'GuacamoleCreate',
	description: 'The data for creating a new Guacamole datasource'
} as const;

export const GuacamoleReadSchema = {
	properties: {
		id: {
			type: 'integer',
			title: 'Id',
			description: 'The ID of the datasource'
		},
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username for the datasource'
		},
		enabled: {
			type: 'boolean',
			title: 'Enabled',
			description: 'Whether the datasource is enabled'
		},
		endpoint: {
			type: 'string',
			title: 'Endpoint',
			description: 'The endpoint for the datasource'
		},
		datasource: {
			type: 'string',
			title: 'Datasource',
			description: 'The name of the Guacamole datasource'
		}
	},
	type: 'object',
	required: ['id', 'username', 'enabled', 'endpoint', 'datasource'],
	title: 'GuacamoleRead',
	description: 'A guacamole datasource schema from the DB'
} as const;

export const GuacamoleUpdateSchema = {
	properties: {
		username: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Username',
			description: 'The username for the datasource'
		},
		password: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Password',
			description: 'The password for the datasource'
		},
		endpoint: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Endpoint',
			description: 'The endpoint for the Saltstack datasource'
		},
		datasource: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					minLength: 1
				},
				{
					type: 'null'
				}
			],
			title: 'Datasource',
			description: 'The name of the Guacamole datasource'
		}
	},
	additionalProperties: false,
	type: 'object',
	title: 'GuacamoleUpdate',
	description: 'The data for updating a Guacamole datasource'
} as const;

export const HTTPValidationErrorSchema = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError'
			},
			type: 'array',
			title: 'Detail'
		}
	},
	type: 'object',
	title: 'HTTPValidationError'
} as const;

export const KeyBearerIdentitySchema = {
	properties: {
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username of the users session'
		},
		role: {
			type: 'string',
			title: 'Role',
			description: 'The role of the user'
		}
	},
	type: 'object',
	required: ['username', 'role'],
	title: 'KeyBearerIdentity',
	description: 'Information about the user assigned an APIKey'
} as const;

export const KeyContextSchema = {
	properties: {
		maxAgeAt: {
			type: 'string',
			format: 'date-time',
			title: 'Maxageat',
			description: 'the time the session expires in seconds ( time.tme() )'
		},
		expiresNext: {
			type: 'string',
			format: 'date-time',
			title: 'Expiresnext',
			description: 'the time the session expires in seconds ( time.tme() )'
		},
		issuedAt: {
			type: 'string',
			format: 'date-time',
			title: 'Issuedat',
			description: 'the time the session was created in seconds ( time.tme() )'
		},
		apiKey: {
			type: 'string',
			title: 'Apikey',
			description: 'The API key object'
		}
	},
	type: 'object',
	required: ['maxAgeAt', 'expiresNext', 'issuedAt', 'apiKey'],
	title: 'KeyContext'
} as const;

export const KeyInfoSchema = {
	properties: {
		owner: {
			anyOf: [
				{
					$ref: '#/components/schemas/KeyBearerIdentity'
				},
				{
					type: 'null'
				}
			],
			description: 'the identity of the user associated with the API key'
		},
		health: {
			$ref: '#/components/schemas/APIKeyHealth',
			description: 'the health of the API key with the relevant timestamps'
		}
	},
	type: 'object',
	required: ['owner', 'health'],
	title: 'KeyInfo',
	description: 'A model to represent the information stored in the redis store'
} as const;

export const LastLogsSchema = {
	properties: {
		lastCritical: {
			anyOf: [
				{
					$ref: '#/components/schemas/EventLogRead'
				},
				{
					type: 'null'
				}
			]
		},
		lastError: {
			anyOf: [
				{
					$ref: '#/components/schemas/EventLogRead'
				},
				{
					type: 'null'
				}
			]
		}
	},
	type: 'object',
	required: ['lastCritical', 'lastError'],
	title: 'LastLogs',
	description: 'represents the most recent logs for the critical and error log levels'
} as const;

export const LogMetaDataSchema = {
	properties: {
		totals: {
			$ref: '#/components/schemas/EventLogLevelTotals',
			description: 'The total count of each log level'
		},
		previousLogs: {
			$ref: '#/components/schemas/LastLogs',
			description: 'The last error and critical log metadata'
		}
	},
	type: 'object',
	required: ['totals', 'previousLogs'],
	title: 'LogMetaData',
	description: 'the event log meta data to display in a dashboard'
} as const;

export const LogQueryResponseSchema = {
	properties: {
		results: {
			items: {
				$ref: '#/components/schemas/EventLogRead'
			},
			type: 'array',
			title: 'Results',
			description: 'The results of the query of type SchemaT'
		},
		pageContext: {
			$ref: '#/components/schemas/APIQueryResult',
			description: 'Metadata for the query results for the frontend to handle'
		}
	},
	type: 'object',
	required: ['results', 'pageContext'],
	title: 'LogQueryResponse',
	description: 'the logs returned from a query'
} as const;

export const LogoutResponseSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
			description: 'the message to be sent to the client after a successful logout',
			default: 'You have been logged out successfully'
		},
		success: {
			type: 'boolean',
			title: 'Success',
			default: true
		}
	},
	type: 'object',
	title: 'LogoutResponse',
	description: 'A model to represent the response after a successful logout'
} as const;

export const OpenstackCreateSchema = {
	properties: {
		username: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Username',
			description: 'The username for the datasource'
		},
		password: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Password',
			description: 'The password for the datasource'
		},
		endpoint: {
			type: 'string',
			title: 'Endpoint',
			description: 'The endpoint for the Saltstack datasource'
		},
		projectId: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectid',
			description: 'The project ID for the Openstack authentication'
		},
		projectName: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectname',
			description: 'The project name for the Openstack authentication'
		},
		projectDomainName: {
			type: 'string',
			title: 'Projectdomainname',
			description: 'The project domain name for the Openstack authentication'
		},
		userDomainName: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Userdomainname',
			description: 'The user domain name for the Openstack authentication'
		},
		regionName: {
			type: 'string',
			maxLength: 50,
			minLength: 1,
			title: 'Regionname',
			description: 'The region name for the Openstack authentication'
		},
		identityApiVersion: {
			type: 'string',
			maxLength: 3,
			minLength: 1,
			pattern: '^(2.0|3)$',
			title: 'Identityapiversion',
			description: 'The identity API version for the Openstack authentication'
		}
	},
	additionalProperties: false,
	type: 'object',
	required: [
		'username',
		'password',
		'endpoint',
		'projectDomainName',
		'userDomainName',
		'regionName',
		'identityApiVersion'
	],
	title: 'OpenstackCreate',
	description: 'The form for creating a new Openstack datasource'
} as const;

export const OpenstackReadSchema = {
	properties: {
		id: {
			type: 'integer',
			title: 'Id',
			description: 'The ID of the datasource'
		},
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username for the datasource'
		},
		enabled: {
			type: 'boolean',
			title: 'Enabled',
			description: 'Whether the datasource is enabled'
		},
		endpoint: {
			type: 'string',
			title: 'Endpoint',
			description: 'The endpoint for the datasource'
		},
		projectId: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectid',
			description: 'The project ID for the Openstack authentication'
		},
		projectName: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectname',
			description: 'The project name for the Openstack authentication'
		},
		projectDomainName: {
			type: 'string',
			title: 'Projectdomainname',
			description: 'The project domain name for the Openstack authentication'
		},
		userDomainName: {
			type: 'string',
			title: 'Userdomainname',
			description: 'The user domain name for the Openstack authentication'
		},
		regionName: {
			type: 'string',
			title: 'Regionname',
			description: 'The region name for the Openstack authentication'
		},
		identityApiVersion: {
			type: 'string',
			title: 'Identityapiversion',
			description: 'The identity API version for the Openstack authentication'
		}
	},
	type: 'object',
	required: [
		'id',
		'username',
		'enabled',
		'endpoint',
		'projectDomainName',
		'userDomainName',
		'regionName',
		'identityApiVersion'
	],
	title: 'OpenstackRead',
	description: 'A Openstack datasource schema from the DB'
} as const;

export const OpenstackUpdateSchema = {
	properties: {
		username: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Username',
			description: 'The username for the datasource'
		},
		password: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Password',
			description: 'The password for the datasource'
		},
		endpoint: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Endpoint',
			description: 'The endpoint for the Saltstack datasource'
		},
		projectId: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectid',
			description: 'The project ID for the Openstack authentication'
		},
		projectName: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectname',
			description: 'The project name for the Openstack authentication'
		},
		projectDomainName: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Projectdomainname',
			description: 'The project domain name for the Openstack authentication'
		},
		userDomainName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					minLength: 1
				},
				{
					type: 'null'
				}
			],
			title: 'Userdomainname',
			description: 'The user domain name for the Openstack authentication'
		},
		regionName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 50,
					minLength: 1
				},
				{
					type: 'null'
				}
			],
			title: 'Regionname',
			description: 'The region name for the Openstack authentication'
		},
		identityApiVersion: {
			anyOf: [
				{
					type: 'string',
					maxLength: 3,
					minLength: 1,
					pattern: '^(2.0|3)$'
				},
				{
					type: 'null'
				}
			],
			title: 'Identityapiversion',
			description: 'The identity API version for the Openstack authentication'
		}
	},
	additionalProperties: false,
	type: 'object',
	title: 'OpenstackUpdate',
	description: 'The form for updating a Openstack datasource'
} as const;

export const RoleSchema = {
	type: 'string',
	enum: ['admin', 'user', 'read_only'],
	title: 'Role'
} as const;

export const UpdateUserFormSchema = {
	properties: {
		username: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Username'
		},
		password: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			title: 'Password'
		},
		role: {
			anyOf: [
				{
					$ref: '#/components/schemas/Role'
				},
				{
					type: 'null'
				}
			]
		}
	},
	additionalProperties: false,
	type: 'object',
	title: 'UpdateUserForm',
	description: 'form to update a user'
} as const;

export const UserDetailsResponseSchema = {
	properties: {
		id: {
			type: 'integer',
			title: 'ID',
			description: 'The ID of the user'
		},
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username of the user'
		},
		role: {
			$ref: '#/components/schemas/Role',
			description: 'The role of the user'
		},
		createdAt: {
			type: 'string',
			format: 'date-time',
			title: 'Createdat',
			description: 'The date the user was created'
		},
		updatedAt: {
			type: 'string',
			format: 'date-time',
			title: 'Updatedat',
			description: 'The date the user was last updated'
		}
	},
	type: 'object',
	required: ['id', 'username', 'role', 'createdAt', 'updatedAt'],
	title: 'UserDetailsResponse',
	description: 'The response model for the user; provides all the information'
} as const;

export const UserResponseSchema = {
	properties: {
		id: {
			type: 'integer',
			title: 'ID',
			description: 'The ID of the user'
		},
		username: {
			type: 'string',
			title: 'Username',
			description: 'The username of the user'
		},
		role: {
			$ref: '#/components/schemas/Role',
			description: 'The role of the user'
		}
	},
	type: 'object',
	required: ['id', 'username', 'role'],
	title: 'UserResponse',
	description: 'The response model for the user; only provides the essential information '
} as const;

export const ValidationErrorSchema = {
	$defs: {
		PydanticError: {
			properties: {
				field: {
					description: 'The field that caused the error',
					title: 'Field',
					type: 'string'
				},
				message: {
					description: 'The error message',
					title: 'Message',
					type: 'string'
				},
				type: {
					description: 'The type of error',
					title: 'Type',
					type: 'string'
				}
			},
			required: ['field', 'message', 'type'],
			title: 'PydanticError',
			type: 'object'
		}
	},
	properties: {
		message: {
			default: 'Invalid data.',
			title: 'Message',
			type: 'string'
		},
		success: {
			default: false,
			title: 'Success',
			type: 'boolean'
		},
		error_label: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			],
			default: null,
			description:
				'An optional label for the error for errors that share status codes but have different meanings',
			title: 'Error Label'
		},
		errors: {
			items: {
				$ref: '#/components/schemas/ValidationError/$defs/PydanticError'
			},
			title: 'Errors',
			type: 'array'
		}
	},
	required: ['errors'],
	title: 'HTTPValidationErrorDetails',
	type: 'object'
} as const;
