// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type {
	LoginUserData,
	LoginUserResponse,
	LoginUserError,
	RefreshAuthenticationData,
	RefreshAuthenticationResponse,
	RefreshAuthenticationError,
	GetTokenDetailsData,
	GetTokenDetailsResponse,
	GetTokenDetailsError,
	LogoutUserData,
	LogoutUserResponse,
	LogoutUserError,
	ReadUserProfileData,
	ReadUserProfileResponse,
	ReadUserProfileError,
	PatchUserProfileData,
	PatchUserProfileResponse,
	PatchUserProfileError,
	ListUsersData,
	ListUsersResponse,
	ListUsersError,
	CreateUserData,
	CreateUserResponse,
	CreateUserError,
	DeleteUserData,
	DeleteUserResponse,
	DeleteUserError,
	ReadUserData,
	ReadUserResponse,
	ReadUserError,
	PatchUserData,
	PatchUserResponse,
	PatchUserError,
	ListOpenstackSourcesData,
	ListOpenstackSourcesResponse,
	ListOpenstackSourcesError,
	CreateOpenstackSourceData,
	CreateOpenstackSourceResponse,
	CreateOpenstackSourceError,
	DeleteOpenstackSourceData,
	DeleteOpenstackSourceResponse,
	DeleteOpenstackSourceError,
	GetOpenstackSourceData,
	GetOpenstackSourceResponse,
	GetOpenstackSourceError,
	UpdateOpenstackSourceData,
	UpdateOpenstackSourceResponse,
	UpdateOpenstackSourceError,
	GetConnectedOpenstackSourceData,
	GetConnectedOpenstackSourceResponse,
	GetConnectedOpenstackSourceError,
	TestOpenstackConnectionData,
	TestOpenstackConnectionError,
	ConnectOpenstackDatasourceData,
	ConnectOpenstackDatasourceResponse,
	ConnectOpenstackDatasourceError,
	DisconnectOpenstackDatasourceData,
	DisconnectOpenstackDatasourceResponse,
	DisconnectOpenstackDatasourceError,
	ListGuacamoleSourcesData,
	ListGuacamoleSourcesResponse,
	ListGuacamoleSourcesError,
	CreateGuacamoleSourceData,
	CreateGuacamoleSourceResponse,
	CreateGuacamoleSourceError,
	DeleteGuacamoleSourceData,
	DeleteGuacamoleSourceResponse,
	DeleteGuacamoleSourceError,
	GetGuacamoleSourceData,
	GetGuacamoleSourceResponse,
	GetGuacamoleSourceError,
	UpdateGuacamoleSourceData,
	UpdateGuacamoleSourceResponse,
	UpdateGuacamoleSourceError,
	GetConnectedGuacamoleSourceData,
	GetConnectedGuacamoleSourceResponse,
	GetConnectedGuacamoleSourceError,
	TestGuacamoleConnectionData,
	TestGuacamoleConnectionError,
	ConnectGuacamoleSourceData,
	ConnectGuacamoleSourceResponse,
	ConnectGuacamoleSourceError,
	DisconnectGuacamoleData,
	DisconnectGuacamoleResponse,
	DisconnectGuacamoleError,
	ListSaltstackSourcesData,
	ListSaltstackSourcesResponse,
	ListSaltstackSourcesError,
	CreateSaltstackSourceData,
	CreateSaltstackSourceResponse,
	CreateSaltstackSourceError,
	DeleteSaltstackSourceData,
	DeleteSaltstackSourceResponse,
	DeleteSaltstackSourceError,
	GetSaltstackSourceData,
	GetSaltstackSourceResponse,
	GetSaltstackSourceError,
	UpdateSaltstackSourceData,
	UpdateSaltstackSourceResponse,
	UpdateSaltstackSourceError,
	GetConnectedSaltstackSourceData,
	GetConnectedSaltstackSourceResponse,
	GetConnectedSaltstackSourceError,
	TestSaltstackConnectionData,
	TestSaltstackConnectionError,
	ConnectSaltstackDatasourceData,
	ConnectSaltstackDatasourceResponse,
	ConnectSaltstackDatasourceError,
	DisconnectSaltstackDatasourceData,
	DisconnectSaltstackDatasourceResponse,
	DisconnectSaltstackDatasourceError,
	GetGuacamoleSummaryData,
	GetGuacamoleSummaryResponse,
	GetGuacamoleSummaryError,
	GetTopologyData,
	GetTopologyResponse,
	GetTopologyError,
	GetSubtopologyData,
	GetSubtopologyResponse,
	GetSubtopologyError,
	GetTimelineData,
	GetTimelineResponse,
	GetTimelineError,
	GetConnectionHistoryData,
	GetConnectionHistoryResponse,
	GetConnectionHistoryError,
	KillConnectionsData,
	KillConnectionsResponse,
	KillConnectionsError,
	GetConnectableUrlData,
	GetConnectableUrlResponse,
	GetConnectableUrlError,
	GetConnectionOverviewData,
	GetConnectionOverviewResponse,
	GetConnectionOverviewError,
	StreamConnectionsHistoryData,
	StreamConnectionsHistoryError,
	StreamUsersHistoryData,
	StreamUsersHistoryError
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Login User
 * Authenticates a user and issues a JWT token pair upon successful login.
 * The access token is to be used for authenticating API requests, while the refresh
 * token can be used to obtain new access tokens when the current one expires.
 */
export const loginUser = <ThrowOnError extends boolean = false>(
	options: Options<LoginUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<LoginUserResponse, LoginUserError, ThrowOnError>({
		url: '/auth/login/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Refresh Authentication
 * **protected**
 * Refreshes an access token using a valid refresh token
 * returning the rotated token claims.
 */
export const refreshAuthentication = <ThrowOnError extends boolean = false>(
	options: Options<RefreshAuthenticationData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		RefreshAuthenticationResponse,
		RefreshAuthenticationError,
		ThrowOnError
	>({
		url: '/auth/refresh/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Get Token Details
 * **protected**
 * Retrieves details about the currently authenticated access token.
 * The provided token must be a valid access token.
 */
export const getTokenDetails = <ThrowOnError extends boolean = false>(
	options?: Options<GetTokenDetailsData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetTokenDetailsResponse,
		GetTokenDetailsError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/auth/token',
		...options
	});
};

/**
 * Logout User
 * **protected**
 * Revokes the given refresh token and its associated access token.
 * This effectively logs the user out by invalidating their current
 * session tokens.
 */
export const logoutUser = <ThrowOnError extends boolean = false>(
	options: Options<LogoutUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		LogoutUserResponse,
		LogoutUserError,
		ThrowOnError
	>({
		url: '/auth/logout/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Read User Profile
 * **Guest Role Required**
 * Retrieves the profile of the currently authenticated user.
 */
export const readUserProfile = <ThrowOnError extends boolean = false>(
	options?: Options<ReadUserProfileData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadUserProfileResponse,
		ReadUserProfileError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/users/profile/',
		...options
	});
};

/**
 * Patch User Profile
 * **User Role Required**
 * Updates the profile of the currently authenticated user.
 * If the password changes, the users `credential_version` is incremented.
 * Meaning, they must re-authenticate.
 */
export const patchUserProfile = <ThrowOnError extends boolean = false>(
	options: Options<PatchUserProfileData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchUserProfileResponse,
		PatchUserProfileError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/users/profile/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * List Users
 * **Admin Role Required**
 * Lists users with optional filtering and pagination.
 */
export const listUsers = <ThrowOnError extends boolean = false>(
	options?: Options<ListUsersData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<ListUsersResponse, ListUsersError, ThrowOnError>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/users/',
		...options
	});
};

/**
 * Create User
 * **User Role Required**
 * Creates a new user, if the current user is not admin
 * and attempts to create a non-guest user, a ForbiddenError is raised.
 */
export const createUser = <ThrowOnError extends boolean = false>(
	options: Options<CreateUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		CreateUserResponse,
		CreateUserError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/users/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Delete User
 * **Admin Role Required**
 * Deletes a user and lazy deletes the token claims
 * by incrementing the `credential_version`.
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
	options: Options<DeleteUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteUserResponse,
		DeleteUserError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/users/{user_id}/',
		...options
	});
};

/**
 * Read User
 * **Admin Role Required**
 * Retrieves a user by their unique ID.
 */
export const readUser = <ThrowOnError extends boolean = false>(
	options: Options<ReadUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<ReadUserResponse, ReadUserError, ThrowOnError>({
		url: '/users/{user_id}/',
		...options
	});
};

/**
 * Patch User
 * **Admin Role Required**
 * Updates a user's information. If the users
 * Role or password changes, the users `credential_version` is
 * incremented.
 */
export const patchUser = <ThrowOnError extends boolean = false>(
	options: Options<PatchUserData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<PatchUserResponse, PatchUserError, ThrowOnError>(
		{
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/{user_id}/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		}
	);
};

/**
 * List Openstack Sources
 * Retrieve a paginated list of Openstack datasources.
 */
export const listOpenstackSources = <ThrowOnError extends boolean = false>(
	options?: Options<ListOpenstackSourcesData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		ListOpenstackSourcesResponse,
		ListOpenstackSourcesError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/',
		...options
	});
};

/**
 * Create Openstack Source
 * Create a new Openstack datasource.
 */
export const createOpenstackSource = <ThrowOnError extends boolean = false>(
	options: Options<CreateOpenstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		CreateOpenstackSourceResponse,
		CreateOpenstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Delete Openstack Source
 * Delete a Openstack datasource by its UUID.
 */
export const deleteOpenstackSource = <ThrowOnError extends boolean = false>(
	options: Options<DeleteOpenstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteOpenstackSourceResponse,
		DeleteOpenstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/{openstack_id}',
		...options
	});
};

/**
 * Get Openstack Source
 * **User**
 * Retrieve a specific Openstack datasource by its UUID.
 */
export const getOpenstackSource = <ThrowOnError extends boolean = false>(
	options: Options<GetOpenstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GetOpenstackSourceResponse,
		GetOpenstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/{openstack_id}',
		...options
	});
};

/**
 * Update Openstack Source
 * **Admin**
 * Update an existing Openstack datasource.
 */
export const updateOpenstackSource = <ThrowOnError extends boolean = false>(
	options: Options<UpdateOpenstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdateOpenstackSourceResponse,
		UpdateOpenstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/{openstack_id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Get Connected Openstack Source
 * Retrieve the currently enabled Openstack datasource.
 */
export const getConnectedOpenstackSource = <ThrowOnError extends boolean = false>(
	options?: Options<GetConnectedOpenstackSourceData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetConnectedOpenstackSourceResponse,
		GetConnectedOpenstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/connected/',
		...options
	});
};

/**
 * Test Openstack Connection
 * Test the connection to a specific Openstack datasource by its UUID.
 */
export const testOpenstackConnection = <ThrowOnError extends boolean = false>(
	options: Options<TestOpenstackConnectionData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		unknown,
		TestOpenstackConnectionError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/test/{datasource_id}',
		...options
	});
};

/**
 * Connect Openstack Datasource
 * Connect to a specific Openstack datasource by its UUID.
 */
export const connectOpenstackDatasource = <ThrowOnError extends boolean = false>(
	options: Options<ConnectOpenstackDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		ConnectOpenstackDatasourceResponse,
		ConnectOpenstackDatasourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/connect/{datasource_id}',
		...options
	});
};

/**
 * Disconnect Openstack Datasource
 * Disconnect the currently enabled Openstack datasource.
 */
export const disconnectOpenstackDatasource = <ThrowOnError extends boolean = false>(
	options?: Options<DisconnectOpenstackDatasourceData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).delete<
		DisconnectOpenstackDatasourceResponse,
		DisconnectOpenstackDatasourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/openstack/disconnect/',
		...options
	});
};

/**
 * List Guacamole Sources
 * Retrieve a paginated list of Guacamole datasources.
 */
export const listGuacamoleSources = <ThrowOnError extends boolean = false>(
	options?: Options<ListGuacamoleSourcesData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		ListGuacamoleSourcesResponse,
		ListGuacamoleSourcesError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/',
		...options
	});
};

/**
 * Create Guacamole Source
 * Create a new Guacamole datasource.
 */
export const createGuacamoleSource = <ThrowOnError extends boolean = false>(
	options: Options<CreateGuacamoleSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		CreateGuacamoleSourceResponse,
		CreateGuacamoleSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Delete Guacamole Source
 * Delete a Guacamole datasource by its UUID.
 */
export const deleteGuacamoleSource = <ThrowOnError extends boolean = false>(
	options: Options<DeleteGuacamoleSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteGuacamoleSourceResponse,
		DeleteGuacamoleSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/{guac_id}',
		...options
	});
};

/**
 * Get Guacamole Source
 * **User**
 * Retrieve a specific Guacamole datasource by its UUID.
 */
export const getGuacamoleSource = <ThrowOnError extends boolean = false>(
	options: Options<GetGuacamoleSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GetGuacamoleSourceResponse,
		GetGuacamoleSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/{guac_id}',
		...options
	});
};

/**
 * Update Guacamole Source
 * **Admin**
 * Update an existing Guacamole datasource.
 */
export const updateGuacamoleSource = <ThrowOnError extends boolean = false>(
	options: Options<UpdateGuacamoleSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdateGuacamoleSourceResponse,
		UpdateGuacamoleSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/{guac_id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Get Connected Guacamole Source
 * Retrieve the currently enabled Guacamole datasource.
 */
export const getConnectedGuacamoleSource = <ThrowOnError extends boolean = false>(
	options?: Options<GetConnectedGuacamoleSourceData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetConnectedGuacamoleSourceResponse,
		GetConnectedGuacamoleSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/connected/',
		...options
	});
};

/**
 * Test Guacamole Connection
 * Test the connection to a specific Guacamole datasource by its UUID.
 */
export const testGuacamoleConnection = <ThrowOnError extends boolean = false>(
	options: Options<TestGuacamoleConnectionData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		unknown,
		TestGuacamoleConnectionError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/test/{datasource_id}',
		...options
	});
};

/**
 * Connect Guacamole Source
 * Connect to a specific Guacamole datasource by its UUID.
 */
export const connectGuacamoleSource = <ThrowOnError extends boolean = false>(
	options: Options<ConnectGuacamoleSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		ConnectGuacamoleSourceResponse,
		ConnectGuacamoleSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/connect/{datasource_id}',
		...options
	});
};

/**
 * Disconnect Guacamole
 * Disconnect the currently enabled Guacamole datasource.
 */
export const disconnectGuacamole = <ThrowOnError extends boolean = false>(
	options?: Options<DisconnectGuacamoleData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).delete<
		DisconnectGuacamoleResponse,
		DisconnectGuacamoleError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/guacamole/disconnect/',
		...options
	});
};

/**
 * List Saltstack Sources
 * Retrieve a paginated list of Saltstack datasources.
 */
export const listSaltstackSources = <ThrowOnError extends boolean = false>(
	options?: Options<ListSaltstackSourcesData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		ListSaltstackSourcesResponse,
		ListSaltstackSourcesError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/',
		...options
	});
};

/**
 * Create Saltstack Source
 * Create a new Saltstack datasource.
 */
export const createSaltstackSource = <ThrowOnError extends boolean = false>(
	options: Options<CreateSaltstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		CreateSaltstackSourceResponse,
		CreateSaltstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Delete Saltstack Source
 * Delete a Saltstack datasource by its UUID.
 */
export const deleteSaltstackSource = <ThrowOnError extends boolean = false>(
	options: Options<DeleteSaltstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteSaltstackSourceResponse,
		DeleteSaltstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/{saltstack_id}',
		...options
	});
};

/**
 * Get Saltstack Source
 * **User**
 * Retrieve a specific Saltstack datasource by its UUID.
 */
export const getSaltstackSource = <ThrowOnError extends boolean = false>(
	options: Options<GetSaltstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GetSaltstackSourceResponse,
		GetSaltstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/{saltstack_id}',
		...options
	});
};

/**
 * Update Saltstack Source
 * **Admin**
 * Update an existing Saltstack datasource.
 */
export const updateSaltstackSource = <ThrowOnError extends boolean = false>(
	options: Options<UpdateSaltstackSourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdateSaltstackSourceResponse,
		UpdateSaltstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/{saltstack_id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Get Connected Saltstack Source
 * Retrieve the currently enabled Saltstack datasource.
 */
export const getConnectedSaltstackSource = <ThrowOnError extends boolean = false>(
	options?: Options<GetConnectedSaltstackSourceData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetConnectedSaltstackSourceResponse,
		GetConnectedSaltstackSourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/connected/',
		...options
	});
};

/**
 * Test Saltstack Connection
 * Test the connection to a specific Saltstack datasource by its UUID.
 */
export const testSaltstackConnection = <ThrowOnError extends boolean = false>(
	options: Options<TestSaltstackConnectionData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		unknown,
		TestSaltstackConnectionError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/test/{datasource_id}',
		...options
	});
};

/**
 * Connect Saltstack Datasource
 * Connect to a specific Saltstack datasource by its UUID.
 */
export const connectSaltstackDatasource = <ThrowOnError extends boolean = false>(
	options: Options<ConnectSaltstackDatasourceData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		ConnectSaltstackDatasourceResponse,
		ConnectSaltstackDatasourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/connect/{datasource_id}',
		...options
	});
};

/**
 * Disconnect Saltstack Datasource
 * Disconnect the currently enabled Saltstack datasource.
 */
export const disconnectSaltstackDatasource = <ThrowOnError extends boolean = false>(
	options?: Options<DisconnectSaltstackDatasourceData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).delete<
		DisconnectSaltstackDatasourceResponse,
		DisconnectSaltstackDatasourceError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/sources/saltstack/disconnect/',
		...options
	});
};

/**
 * Get Guacamole Summary
 * Provides a summary of the Guacamole data source including
 * details about the connected datasource
 */
export const getGuacamoleSummary = <ThrowOnError extends boolean = false>(
	options?: Options<GetGuacamoleSummaryData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetGuacamoleSummaryResponse,
		GetGuacamoleSummaryError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/',
		...options
	});
};

/**
 * Get Topology
 * Returns the full topology of connections from the root.
 */
export const getTopology = <ThrowOnError extends boolean = false>(
	options?: Options<GetTopologyData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetTopologyResponse,
		GetTopologyError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/topology',
		...options
	});
};

/**
 * Get Subtopology
 * Gets the topology of the a connection group
 */
export const getSubtopology = <ThrowOnError extends boolean = false>(
	options: Options<GetSubtopologyData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GetSubtopologyResponse,
		GetSubtopologyError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/topology/{group_id}/',
		...options
	});
};

/**
 * Get Timeline
 * Returns the timestamped history of connection events.
 */
export const getTimeline = <ThrowOnError extends boolean = false>(
	options?: Options<GetTimelineData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetTimelineResponse,
		GetTimelineError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/timeline/',
		...options
	});
};

/**
 * Get Connection History
 * Retrieves the connection history for a specific connection.
 */
export const getConnectionHistory = <ThrowOnError extends boolean = false>(
	options: Options<GetConnectionHistoryData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).get<
		GetConnectionHistoryResponse,
		GetConnectionHistoryError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/history/{connection_id}',
		...options
	});
};

/**
 * Kill Connections
 * Kills one or more active connections by their identifiers.
 */
export const killConnections = <ThrowOnError extends boolean = false>(
	options: Options<KillConnectionsData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).delete<
		KillConnectionsResponse,
		KillConnectionsError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/kill/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Get Connectable Url
 * Gets a Guacamole URL that can be used to connect to one or more
 * connections or active instances.
 */
export const getConnectableUrl = <ThrowOnError extends boolean = false>(
	options: Options<GetConnectableUrlData, ThrowOnError>
) => {
	return (options.client ?? _heyApiClient).post<
		GetConnectableUrlResponse,
		GetConnectableUrlError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/connect/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers
		}
	});
};

/**
 * Get Connection Overview
 */
export const getConnectionOverview = <ThrowOnError extends boolean = false>(
	options?: Options<GetConnectionOverviewData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		GetConnectionOverviewResponse,
		GetConnectionOverviewError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/connections/activity/',
		...options
	});
};

/**
 * Stream Connections History
 * Streams the connection history for all connections as NDJSON.
 */
export const streamConnectionsHistory = <ThrowOnError extends boolean = false>(
	options?: Options<StreamConnectionsHistoryData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<
		unknown,
		StreamConnectionsHistoryError,
		ThrowOnError
	>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/history/connections/',
		...options
	});
};

/**
 * Stream Users History
 * Streams the user history for all users as NDJSON.
 */
export const streamUsersHistory = <ThrowOnError extends boolean = false>(
	options?: Options<StreamUsersHistoryData, ThrowOnError>
) => {
	return (options?.client ?? _heyApiClient).get<unknown, StreamUsersHistoryError, ThrowOnError>({
		security: [
			{
				scheme: 'bearer',
				type: 'http'
			}
		],
		url: '/guacamole/api/history/users/',
		...options
	});
};
