// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type {
	LoginData,
	LoginResponse,
	LoginError,
	LogoutData,
	LogoutResponse2,
	LogoutError,
	GetApiKeyStatusData,
	GetApiKeyStatusResponse,
	GetApiKeyStatusError,
	GetCurrentUserData,
	GetCurrentUserResponse,
	GetCurrentUserError,
	GetAllUsersData,
	GetAllUsersResponse,
	GetAllUsersError,
	CreateUserData,
	CreateUserResponse,
	CreateUserError,
	GetAllDetailsData,
	GetAllDetailsResponse,
	GetAllDetailsError,
	GetUserDetailsData,
	GetUserDetailsResponse,
	GetUserDetailsError,
	DeleteUserData,
	DeleteUserResponse,
	DeleteUserError,
	ReadUserData,
	ReadUserResponse,
	ReadUserError,
	UpdateUserData,
	UpdateUserResponse,
	UpdateUserError,
	SummaryData,
	SummaryResponse,
	SummaryError,
	SearchData,
	SearchResponse,
	SearchError,
	LogsFromTodayData,
	LogsFromTodayResponse,
	LogsFromTodayError,
	GetAllDatasourcesData,
	GetAllDatasourcesResponse,
	GetAllDatasourcesError,
	CreateDatasourceData,
	CreateDatasourceResponse,
	CreateDatasourceError,
	DeleteSourceIdData,
	DeleteSourceIdResponse,
	DeleteSourceIdError,
	ReadSourceIdData,
	ReadSourceIdResponse,
	ReadSourceIdError,
	UpdateSourceIdData,
	UpdateSourceIdResponse,
	UpdateSourceIdError,
	EnableSourceIdData,
	EnableSourceIdResponse,
	EnableSourceIdError,
	DisableSourceIdData,
	DisableSourceIdResponse,
	DisableSourceIdError,
	ToggleSourceIdData,
	ToggleSourceIdResponse,
	ToggleSourceIdError,
	TestConnectionIdData,
	TestConnectionIdResponse,
	TestConnectionIdError,
	TestConnectionData,
	TestConnectionResponse,
	TestConnectionError
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export class AuthService {
	/**
	 * Login
	 * Checks the credentials provided by the 'AuthForm'
	 * and in the response sets a cookie with the session id when given
	 * valid login credentials.
	 *
	 * Arguments:
	 * auth_form {AuthForm} -- Has types to enforce constraints on the request body
	 * client {RequireClientIdentity} -- The client identity
	 * user_service {UserController} -- The user controller
	 * Raises:
	 * HTTPUnauthorized: 401 - If the user is not authenticated
	 * Returns:
	 * Response
	 */
	public static login<ThrowOnError extends boolean = false>(
		options: Options<LoginData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<LoginResponse, LoginError, ThrowOnError>({
			url: '/auth/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}

	/**
	 * Logout
	 * Logs out the user using the _"api_key" dependency_
	 *
	 * - Load the clients signed api key from the clients cookies
	 * - Decrypts the api key in the Redis store,
	 *
	 * - if the key hasn't been tampered with by the user and is valid the
	 * session is revoked by deleting the key in the Redis store mapped to the api key
	 * and the cookie is removed from the client
	 * Arguments:
	 * request {Request}  - the request to get the existing session ID from
	 * Raises:
	 * If the api_key is not found or was tampered with
	 * by the client
	 * Returns:
	 * JSONResponse -- a message indicating the logout was successful
	 */
	public static logout<ThrowOnError extends boolean = false>(
		options?: Options<LogoutData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).post<LogoutResponse2, LogoutError, ThrowOnError>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/auth/logout/',
			...options
		});
	}

	/**
	 * Get Api Key Status
	 */
	public static getApiKeyStatus<ThrowOnError extends boolean = false>(
		options?: Options<GetApiKeyStatusData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetApiKeyStatusResponse,
			GetApiKeyStatusError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/auth/key/',
			...options
		});
	}
}

export class UserService {
	/**
	 * Get Current User
	 * Reads the current user and returns the authentication context
	 * of said user
	 *
	 * Arguments:
	 * reader {CurrentUser} -- the reader
	 *
	 * Returns:
	 * UserResponse -- the current user
	 */
	public static getCurrentUser<ThrowOnError extends boolean = false>(
		options?: Options<GetCurrentUserData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetCurrentUserResponse,
			GetCurrentUserError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/me/',
			...options
		});
	}

	/**
	 * Get All Users
	 * reads all users based on the role of the reader (no read up)
	 * Arguments:
	 * user_service {UserServiceDep} -- the service dep
	 * reader {CurrentUser} -- the current user
	 *
	 * Returns:
	 * list[UserResponse] -- all of the users based on the readers role
	 */
	public static getAllUsers<ThrowOnError extends boolean = false>(
		options?: Options<GetAllUsersData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetAllUsersResponse,
			GetAllUsersError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/',
			...options
		});
	}

	/**
	 * Create User
	 * **[ADMIN]**
	 * Creates a user given valid form data and inserts
	 * the created user into the database and returns the
	 * created user
	 *
	 * _Arguments_:
	 * - create_schema {CreateUserForm} -- the form data
	 * - db {AsyncSession} - the database session
	 * _Raises_:
	 * HTTPException: 400 - Username is already taken
	 * _Returns_:
	 * UserResponse -- the created user
	 */
	public static createUser<ThrowOnError extends boolean = false>(
		options: Options<CreateUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			CreateUserResponse,
			CreateUserError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}

	/**
	 * Get All Details
	 * Admin protected route to read all of the user details, including
	 * the creation date and last updated timestamps
	 *
	 * Arguments:
	 * user_service: UserServiceDep
	 *
	 * Returns:
	 * list[UserDetailsResponse]
	 */
	public static getAllDetails<ThrowOnError extends boolean = false>(
		options?: Options<GetAllDetailsData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetAllDetailsResponse,
			GetAllDetailsError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/details',
			...options
		});
	}

	/**
	 * Get User Details
	 * reads the details of an individual user
	 *
	 * Arguments:
	 * user_id {int} -- the id of the user to read
	 * db {DatabaseRequired} -- the database session
	 *
	 * Raises:
	 * HTTPNotFound: the user does not exist
	 *
	 * Returns:
	 * UserDetailsResponse -- the details of the individual user
	 */
	public static getUserDetails<ThrowOnError extends boolean = false>(
		options: Options<GetUserDetailsData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			GetUserDetailsResponse,
			GetUserDetailsError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/details/{user_id}/',
			...options
		});
	}

	/**
	 * Delete User
	 * Deletes a user given an existing user ID
	 *
	 * Arguments:
	 * user_id {int} -- the ID of the user to be deleted
	 * db {requires_db} -- a database session
	 * admin {admin_required} -- an admin user, ensures the Admin isn't deleting
	 * themselves
	 * Returns:
	 * ResponseMessage -- A message indicating the deletion was successful
	 */
	public static deleteUser<ThrowOnError extends boolean = false>(
		options: Options<DeleteUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).delete<
			DeleteUserResponse,
			DeleteUserError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/{user_id}/',
			...options
		});
	}

	/**
	 * Read User
	 * Reads a user with 'no read up' i.e a user cannot read a user with a
	 * higher role / permission
	 *
	 * Arguments:
	 * user_id {int} -- the id of the user to read
	 * db {requires_db} -- the database session
	 * reader {role_required} -- the "reader" or user making the request
	 *
	 * Raises:
	 * HTTPNotFound: The user does not exist
	 * HTTPForbidden: The user does not have permission to read the user
	 *
	 * Returns:
	 * UserResponse -- The user attempting to be read
	 */
	public static readUser<ThrowOnError extends boolean = false>(
		options: Options<ReadUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<ReadUserResponse, ReadUserError, ThrowOnError>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/{user_id}/',
			...options
		});
	}

	/**
	 * Update User
	 * updates the user given an id and uses the schema to update the user's data
	 *
	 * Arguments:
	 * user_id {int} -- user id of the user to update
	 * update_schema {UpdateUser} -- the request body schema
	 * db {AsyncSession} -- the database session
	 * Returns:
	 * UserResponse -- the updated user
	 */
	public static updateUser<ThrowOnError extends boolean = false>(
		options: Options<UpdateUserData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).patch<
			UpdateUserResponse,
			UpdateUserError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/users/{user_id}/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}
}

export class EventLogsService {
	/**
	 * Summary
	 * returns a summary of recent event logs
	 * Arguments:
	 * log_service {LogServiceDep}
	 * Returns:
	 * LogMetaData
	 */
	public static summary<ThrowOnError extends boolean = false>(
		options?: Options<SummaryData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<SummaryResponse, SummaryError, ThrowOnError>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/logs/summary/',
			...options
		});
	}

	/**
	 * Search
	 * Searches the logs based on the query parameters
	 * Arguments:
	 * query_params {Annotated[LogQueryParams, Query} -- the query params
	 * log_service {LogServiceDep} -- the log service dep
	 * Raises:
	 * HTTPNotFound: if no logs are found matching the query parameters
	 * Returns:
	 * LogQueryResponse -- the logs that match the query parameters
	 */
	public static search<ThrowOnError extends boolean = false>(
		options?: Options<SearchData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<SearchResponse, SearchError, ThrowOnError>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/logs/search/',
			...options
		});
	}

	/**
	 * Logs From Today
	 * Given a query filter, returns the logs from today that match the filter
	 *
	 * Arguments:
	 * query_filter {Annotated[LogQueryParams, Query} the query params
	 * log_service {LogServiceDep} -- the log service dep
	 *
	 * Raises:
	 * HTTPNotFound: if no logs are found matching the query parameters
	 *
	 * Returns:
	 * LogQueryResponse -- the logs that match the query parameters
	 */
	public static logsFromToday<ThrowOnError extends boolean = false>(
		options?: Options<LogsFromTodayData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			LogsFromTodayResponse,
			LogsFromTodayError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/logs/today/',
			...options
		});
	}
}

export class OpenstackService {
	/**
	 * Get All Datasources
	 */
	public static getAllDatasources<ThrowOnError extends boolean = false>(
		options?: Options<GetAllDatasourcesData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetAllDatasourcesResponse,
			GetAllDatasourcesError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/',
			...options
		});
	}

	/**
	 * Create Datasource
	 */
	public static createDatasource<ThrowOnError extends boolean = false>(
		options: Options<CreateDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			CreateDatasourceResponse,
			CreateDatasourceError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}

	/**
	 * Delete Source Id
	 */
	public static deleteSourceId<ThrowOnError extends boolean = false>(
		options: Options<DeleteSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).delete<
			DeleteSourceIdResponse,
			DeleteSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/{source_id}/',
			...options
		});
	}

	/**
	 * Read Source Id
	 */
	public static readSourceId<ThrowOnError extends boolean = false>(
		options: Options<ReadSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			ReadSourceIdResponse,
			ReadSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/{source_id}/',
			...options
		});
	}

	/**
	 * Update Source Id
	 */
	public static updateSourceId<ThrowOnError extends boolean = false>(
		options: Options<UpdateSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).patch<
			UpdateSourceIdResponse,
			UpdateSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/{source_id}/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}

	/**
	 * Enable Source Id
	 */
	public static enableSourceId<ThrowOnError extends boolean = false>(
		options: Options<EnableSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			EnableSourceIdResponse,
			EnableSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/enable/{source_id}',
			...options
		});
	}

	/**
	 * Disable Source Id
	 */
	public static disableSourceId<ThrowOnError extends boolean = false>(
		options: Options<DisableSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			DisableSourceIdResponse,
			DisableSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/disable',
			...options
		});
	}

	/**
	 * Toggle Source Id
	 */
	public static toggleSourceId<ThrowOnError extends boolean = false>(
		options: Options<ToggleSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			ToggleSourceIdResponse,
			ToggleSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/toggle/{source_id}',
			...options
		});
	}

	/**
	 * Test Connection Id
	 */
	public static testConnectionId<ThrowOnError extends boolean = false>(
		options: Options<TestConnectionIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			TestConnectionIdResponse,
			TestConnectionIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/test/{source_id}',
			...options
		});
	}

	/**
	 * Test Connection
	 */
	public static testConnection<ThrowOnError extends boolean = false>(
		options?: Options<TestConnectionData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			TestConnectionResponse,
			TestConnectionError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/openstack/test',
			...options
		});
	}
}

export class GuacamoleService {
	/**
	 * Get All Datasources
	 */
	public static getAllDatasources<ThrowOnError extends boolean = false>(
		options?: Options<GetAllDatasourcesData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			GetAllDatasourcesResponse,
			GetAllDatasourcesError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/',
			...options
		});
	}

	/**
	 * Create Datasource
	 */
	public static createDatasource<ThrowOnError extends boolean = false>(
		options: Options<CreateDatasourceData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			CreateDatasourceResponse,
			CreateDatasourceError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}

	/**
	 * Delete Source Id
	 */
	public static deleteSourceId<ThrowOnError extends boolean = false>(
		options: Options<DeleteSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).delete<
			DeleteSourceIdResponse,
			DeleteSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/{source_id}/',
			...options
		});
	}

	/**
	 * Read Source Id
	 */
	public static readSourceId<ThrowOnError extends boolean = false>(
		options: Options<ReadSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			ReadSourceIdResponse,
			ReadSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/{source_id}/',
			...options
		});
	}

	/**
	 * Update Source Id
	 */
	public static updateSourceId<ThrowOnError extends boolean = false>(
		options: Options<UpdateSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).patch<
			UpdateSourceIdResponse,
			UpdateSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/{source_id}/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers
			}
		});
	}

	/**
	 * Enable Source Id
	 */
	public static enableSourceId<ThrowOnError extends boolean = false>(
		options: Options<EnableSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			EnableSourceIdResponse,
			EnableSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/enable/{source_id}',
			...options
		});
	}

	/**
	 * Disable Source Id
	 */
	public static disableSourceId<ThrowOnError extends boolean = false>(
		options: Options<DisableSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			DisableSourceIdResponse,
			DisableSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/disable',
			...options
		});
	}

	/**
	 * Toggle Source Id
	 */
	public static toggleSourceId<ThrowOnError extends boolean = false>(
		options: Options<ToggleSourceIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).post<
			ToggleSourceIdResponse,
			ToggleSourceIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/toggle/{source_id}',
			...options
		});
	}

	/**
	 * Test Connection Id
	 */
	public static testConnectionId<ThrowOnError extends boolean = false>(
		options: Options<TestConnectionIdData, ThrowOnError>
	) {
		return (options.client ?? _heyApiClient).get<
			TestConnectionIdResponse,
			TestConnectionIdError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/test/{source_id}',
			...options
		});
	}

	/**
	 * Test Connection
	 */
	public static testConnection<ThrowOnError extends boolean = false>(
		options?: Options<TestConnectionData, ThrowOnError>
	) {
		return (options?.client ?? _heyApiClient).get<
			TestConnectionResponse,
			TestConnectionError,
			ThrowOnError
		>({
			security: [
				{
					scheme: 'bearer',
					type: 'http'
				}
			],
			url: '/datasources/guacamole/test',
			...options
		});
	}
}
