// This file is auto-generated by @hey-api/openapi-ts

/**
 * The response returned when an error occurs during an API request
 */
export type ApiErrorResponse = {
	/**
	 * A description of the error that occured
	 */
	message: string;
	success?: boolean;
	/**
	 * An optional label for the error for errors that share status codes but have different meanings
	 */
	error_label?: string | null;
};

export type ApiKeyHealth = {
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	maxAgeAt: string;
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	expiresNext: string;
	/**
	 * the time the session was created in seconds ( time.tme() )
	 */
	issuedAt: string;
};

/**
 * The response after a successful login that contains the signed API key and
 * the identity of the client
 */
export type ApiKeyResponse = {
	/**
	 * the signed API key to be issued to the client
	 */
	apiKey: string;
	/**
	 * the identity of the user associated with the API key
	 */
	identity: KeyBearerIdentity;
};

export type ApiListResponseGuacamoleRead = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<GuacamoleRead>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

export type ApiListResponseOpenstackRead = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<OpenstackRead>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

export type ApiListResponseUserDetailsResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<UserDetailsResponse>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

export type ApiListResponseUserResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: Array<UserResponse>;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * reprents the pagination metadata for a query
 * to help the frontend
 */
export type ApiQueryResult = {
	/**
	 * The total number of records from the returned query
	 */
	total: number;
	/**
	 * The number of records to skip for the next 'page' of the query
	 */
	nextSkip: number;
	/**
	 * The number of pages of results from the query
	 */
	totalPages: number;
	/**
	 * The total number of items returned in the query
	 */
	totalItems: number;
};

export type AuthContext = {
	/**
	 * The user object
	 */
	user: UserResponse;
	/**
	 * The authentication object
	 */
	auth: KeyContext;
};

/**
 * The base model for all app authentication forms
 */
export type AuthForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
};

/**
 * The schema for the results of testing a datasource connection
 */
export type ConnectionTestResult = {
	/**
	 * The message indicating the connection result
	 */
	message: string;
	/**
	 * Whether the connection was successful
	 */
	success: boolean;
	/**
	 * The error message if the connection failed
	 */
	error?: string | null;
};

/**
 * form to create a user
 */
export type CreateUserForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type EventLogLevel = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * represents the total number of logs for each log level
 */
export type EventLogLevelTotals = {
	info: number;
	warning: number;
	error: number;
	critical: number;
};

/**
 * represents a event log returned from the API
 */
export type EventLogRead = {
	logLevel: EventLogLevel;
	message: string;
	timestamp: string;
};

/**
 * Generic API response model
 */
export type GenericApiResponse = {
	data: {
		[key: string]: unknown;
	};
	/**
	 * The message returned by the API
	 */
	message: string;
};

/**
 * The data for creating a new Guacamole datasource
 */
export type GuacamoleCreate = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The password for the datasource
	 */
	password: string;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint: string;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
};

/**
 * A guacamole datasource schema from the DB
 */
export type GuacamoleRead = {
	/**
	 * The ID of the datasource
	 */
	id: number;
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * Whether the datasource is enabled
	 */
	enabled: boolean;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
};

/**
 * The data for updating a Guacamole datasource
 */
export type GuacamoleUpdate = {
	/**
	 * The username for the datasource
	 */
	username?: string | null;
	/**
	 * The password for the datasource
	 */
	password?: string | null;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint?: string | null;
	/**
	 * The name of the Guacamole datasource
	 */
	datasource?: string | null;
};

export type HttpValidationError = {
	detail?: Array<ValidationError>;
};

/**
 * Information about the user assigned an APIKey
 */
export type KeyBearerIdentity = {
	/**
	 * The username of the users session
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: string;
};

export type KeyContext = {
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	maxAgeAt: string;
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	expiresNext: string;
	/**
	 * the time the session was created in seconds ( time.tme() )
	 */
	issuedAt: string;
	/**
	 * The API key object
	 */
	apiKey: string;
};

/**
 * A model to represent the information stored in the redis store
 */
export type KeyInfo = {
	/**
	 * the identity of the user associated with the API key
	 */
	owner: KeyBearerIdentity | null;
	/**
	 * the health of the API key with the relevant timestamps
	 */
	health: ApiKeyHealth;
};

/**
 * represents the most recent logs for the critical and error log levels
 */
export type LastLogs = {
	lastCritical: EventLogRead | null;
	lastError: EventLogRead | null;
};

/**
 * the event log meta data to display in a dashboard
 */
export type LogMetaData = {
	/**
	 * The total count of each log level
	 */
	totals: EventLogLevelTotals;
	/**
	 * The last error and critical log metadata
	 */
	previousLogs: LastLogs;
};

/**
 * the logs returned from a query
 */
export type LogQueryResponse = {
	/**
	 * The results of the query of type SchemaT
	 */
	results: Array<EventLogRead>;
	/**
	 * Metadata for the query results for the frontend to handle
	 */
	pageContext: ApiQueryResult;
};

/**
 * A model to represent the response after a successful logout
 */
export type LogoutResponse = {
	/**
	 * the message to be sent to the client after a successful logout
	 */
	message?: string;
	success?: boolean;
};

/**
 * The form for creating a new Openstack datasource
 */
export type OpenstackCreate = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The password for the datasource
	 */
	password: string;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

/**
 * A Openstack datasource schema from the DB
 */
export type OpenstackRead = {
	/**
	 * The ID of the datasource
	 */
	id: number;
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * Whether the datasource is enabled
	 */
	enabled: boolean;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

/**
 * The form for updating a Openstack datasource
 */
export type OpenstackUpdate = {
	/**
	 * The username for the datasource
	 */
	username?: string | null;
	/**
	 * The password for the datasource
	 */
	password?: string | null;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint?: string | null;
	/**
	 * The project ID for the Openstack authentication
	 */
	projectId?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName?: string | null;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName?: string | null;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName?: string | null;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion?: string | null;
};

export type Role = 'admin' | 'user' | 'read_only';

/**
 * form to update a user
 */
export type UpdateUserForm = {
	username?: string | null;
	password?: string | null;
	role?: Role | null;
};

/**
 * The response model for the user; provides all the information
 */
export type UserDetailsResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
	/**
	 * The date the user was created
	 */
	createdAt: string;
	/**
	 * The date the user was last updated
	 */
	updatedAt: string;
};

/**
 * The response model for the user; only provides the essential information
 */
export type UserResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type ValidationError = {
	message?: string;
	success?: boolean;
	/**
	 * An optional label for the error for errors that share status codes but have different meanings
	 */
	error_label?: string | null;
	errors: Array<PydanticError>;
};

export type LoginData = {
	body: AuthForm;
	path?: never;
	query?: never;
	url: '/auth/';
};

export type LoginErrors = {
	/**
	 * When the user provides invalid credentials
	 */
	401: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
	/**
	 * Successful Response
	 */
	200: ApiKeyResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/logout/';
};

export type LogoutErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
	/**
	 * Successful Response
	 */
	200: LogoutResponse;
};

export type LogoutResponse2 = LogoutResponses[keyof LogoutResponses];

export type GetApiKeyStatusData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/key/';
};

export type GetApiKeyStatusErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type GetApiKeyStatusError = GetApiKeyStatusErrors[keyof GetApiKeyStatusErrors];

export type GetApiKeyStatusResponses = {
	/**
	 * Successful Response
	 */
	200: KeyInfo;
};

export type GetApiKeyStatusResponse = GetApiKeyStatusResponses[keyof GetApiKeyStatusResponses];

export type GetCurrentUserData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/me/';
};

export type GetCurrentUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
	/**
	 * Successful Response
	 */
	200: AuthContext;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetAllUsersData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/';
};

export type GetAllUsersErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
};

export type GetAllUsersError = GetAllUsersErrors[keyof GetAllUsersErrors];

export type GetAllUsersResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserResponse;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
	body: CreateUserForm;
	path?: never;
	query?: never;
	url: '/users/';
};

export type CreateUserErrors = {
	/**
	 * The username provided is taken.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
	/**
	 * Successful Response
	 */
	201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetAllDetailsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/details';
};

export type GetAllDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type GetAllDetailsError = GetAllDetailsErrors[keyof GetAllDetailsErrors];

export type GetAllDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserDetailsResponse;
};

export type GetAllDetailsResponse = GetAllDetailsResponses[keyof GetAllDetailsResponses];

export type GetUserDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/details/{user_id}/';
};

export type GetUserDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type GetUserDetailsError = GetUserDetailsErrors[keyof GetUserDetailsErrors];

export type GetUserDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: UserDetailsResponse;
};

export type GetUserDetailsResponse = GetUserDetailsResponses[keyof GetUserDetailsResponses];

export type DeleteUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type DeleteUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * An admin cannot delete their own account.
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type ReadUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ReadUserError = ReadUserErrors[keyof ReadUserErrors];

export type ReadUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type UpdateUserData = {
	body: UpdateUserForm;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type UpdateUserErrors = {
	/**
	 * The username provided is taken.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
	/**
	 * Successful Response
	 */
	202: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SummaryData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/logs/summary/';
};

export type SummaryErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type SummaryError = SummaryErrors[keyof SummaryErrors];

export type SummaryResponses = {
	/**
	 * Successful Response
	 */
	200: LogMetaData;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SearchData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/search/';
};

export type SearchErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type LogsFromTodayData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/today/';
};

export type LogsFromTodayErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type LogsFromTodayError = LogsFromTodayErrors[keyof LogsFromTodayErrors];

export type LogsFromTodayResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type LogsFromTodayResponse = LogsFromTodayResponses[keyof LogsFromTodayResponses];

export type GetAllDatasourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/openstack/';
};

export type GetAllDatasourcesErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
};

export type GetAllDatasourcesError = GetAllDatasourcesErrors[keyof GetAllDatasourcesErrors];

export type GetAllDatasourcesResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseOpenstackRead;
};

export type GetAllDatasourcesResponse =
	GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
	body: OpenstackCreate;
	path?: never;
	query?: never;
	url: '/datasources/openstack/';
};

export type CreateDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type DeleteSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}/';
};

export type DeleteSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DeleteSourceIdError = DeleteSourceIdErrors[keyof DeleteSourceIdErrors];

export type DeleteSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteSourceIdResponse = DeleteSourceIdResponses[keyof DeleteSourceIdResponses];

export type ReadSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}/';
};

export type ReadSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ReadSourceIdError = ReadSourceIdErrors[keyof ReadSourceIdErrors];

export type ReadSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type ReadSourceIdResponse = ReadSourceIdResponses[keyof ReadSourceIdResponses];

export type UpdateSourceIdData = {
	body: OpenstackUpdate;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/{source_id}/';
};

export type UpdateSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type UpdateSourceIdError = UpdateSourceIdErrors[keyof UpdateSourceIdErrors];

export type UpdateSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type UpdateSourceIdResponse = UpdateSourceIdResponses[keyof UpdateSourceIdResponses];

export type EnableSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/enable/{source_id}';
};

export type EnableSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type EnableSourceIdError = EnableSourceIdErrors[keyof EnableSourceIdErrors];

export type EnableSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type EnableSourceIdResponse = EnableSourceIdResponses[keyof EnableSourceIdResponses];

export type DisableSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/disable';
};

export type DisableSourceIdErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DisableSourceIdError = DisableSourceIdErrors[keyof DisableSourceIdErrors];

export type DisableSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type DisableSourceIdResponse = DisableSourceIdResponses[keyof DisableSourceIdResponses];

export type ToggleSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/toggle/{source_id}';
};

export type ToggleSourceIdErrors = {
	/**
	 * When the datasource cannot be toggled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * When the datasource does not exist
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ToggleSourceIdError = ToggleSourceIdErrors[keyof ToggleSourceIdErrors];

export type ToggleSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: OpenstackRead;
};

export type ToggleSourceIdResponse = ToggleSourceIdResponses[keyof ToggleSourceIdResponses];

export type TestConnectionIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/openstack/test/{source_id}';
};

export type TestConnectionIdErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type TestConnectionIdError = TestConnectionIdErrors[keyof TestConnectionIdErrors];

export type TestConnectionIdResponses = {
	/**
	 * Successful Response
	 */
	200: ConnectionTestResult;
};

export type TestConnectionIdResponse = TestConnectionIdResponses[keyof TestConnectionIdResponses];

export type TestConnectionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/openstack/test';
};

export type TestConnectionErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: ConnectionTestResult;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type GetAllDatasourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/';
};

export type GetAllDatasourcesErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
};

export type GetAllDatasourcesError = GetAllDatasourcesErrors[keyof GetAllDatasourcesErrors];

export type GetAllDatasourcesResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseGuacamoleRead;
};

export type GetAllDatasourcesResponse =
	GetAllDatasourcesResponses[keyof GetAllDatasourcesResponses];

export type CreateDatasourceData = {
	body: GuacamoleCreate;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/';
};

export type CreateDatasourceErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type DeleteSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type DeleteSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DeleteSourceIdError = DeleteSourceIdErrors[keyof DeleteSourceIdErrors];

export type DeleteSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteSourceIdResponse = DeleteSourceIdResponses[keyof DeleteSourceIdResponses];

export type ReadSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type ReadSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ReadSourceIdError = ReadSourceIdErrors[keyof ReadSourceIdErrors];

export type ReadSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type ReadSourceIdResponse = ReadSourceIdResponses[keyof ReadSourceIdResponses];

export type UpdateSourceIdData = {
	body: GuacamoleUpdate;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/{source_id}/';
};

export type UpdateSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type UpdateSourceIdError = UpdateSourceIdErrors[keyof UpdateSourceIdErrors];

export type UpdateSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type UpdateSourceIdResponse = UpdateSourceIdResponses[keyof UpdateSourceIdResponses];

export type EnableSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/enable/{source_id}';
};

export type EnableSourceIdErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type EnableSourceIdError = EnableSourceIdErrors[keyof EnableSourceIdErrors];

export type EnableSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type EnableSourceIdResponse = EnableSourceIdResponses[keyof EnableSourceIdResponses];

export type DisableSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/disable';
};

export type DisableSourceIdErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type DisableSourceIdError = DisableSourceIdErrors[keyof DisableSourceIdErrors];

export type DisableSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type DisableSourceIdResponse = DisableSourceIdResponses[keyof DisableSourceIdResponses];

export type ToggleSourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/toggle/{source_id}';
};

export type ToggleSourceIdErrors = {
	/**
	 * When the datasource cannot be toggled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * When the datasource does not exist
	 */
	404: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type ToggleSourceIdError = ToggleSourceIdErrors[keyof ToggleSourceIdErrors];

export type ToggleSourceIdResponses = {
	/**
	 * Successful Response
	 */
	200: GuacamoleRead;
};

export type ToggleSourceIdResponse = ToggleSourceIdResponses[keyof ToggleSourceIdResponses];

export type TestConnectionIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		source_id: number;
	};
	query?: never;
	url: '/datasources/guacamole/test/{source_id}';
};

export type TestConnectionIdErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Validation Error
	 */
	422: ValidationError;
};

export type TestConnectionIdError = TestConnectionIdErrors[keyof TestConnectionIdErrors];

export type TestConnectionIdResponses = {
	/**
	 * Successful Response
	 */
	200: ConnectionTestResult;
};

export type TestConnectionIdResponse = TestConnectionIdResponses[keyof TestConnectionIdResponses];

export type TestConnectionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/guacamole/test';
};

export type TestConnectionErrors = {
	/**
	 * When the datasource is not enabled
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
	/**
	 * Successful Response
	 */
	200: ConnectionTestResult;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type ClientOptions = {
	baseURL: `${string}://${string}` | (string & {});
};
