// This file is auto-generated by @hey-api/openapi-ts

/**
 * The response returned when an error occurs during an API request
 */
export type ApiErrorResponse = {
	/**
	 * A description of the error that occured
	 */
	message: string;
	success?: boolean;
	/**
	 * An optional label for the error for errors that share status codes but have different meanings
	 */
	error_label?: string | null;
};

export type ApiKeyHealth = {
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	maxAgeAt: string;
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	expiresNext: string;
	/**
	 * the time the session was created in seconds ( time.tme() )
	 */
	issuedAt: string;
};

/**
 * The response after a successful login that contains the signed API key and
 * the identity of the client
 */
export type ApiKeyResponse = {
	/**
	 * the signed API key to be issued to the client
	 */
	apiKey: string;
	/**
	 * the identity of the user associated with the API key
	 */
	identity: KeyBearerIdentity;
};

export type ApiListResponseUserDetailsResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: unknown;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

export type ApiListResponseUserResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: unknown;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
};

/**
 * reprents the pagination metadata for a query
 * to help the frontend
 */
export type ApiQueryResult = {
	/**
	 * The total number of records from the returned query
	 */
	total: number;
	/**
	 * The number of items to skip for the next 'page' of the query
	 */
	nextSkip: number;
	/**
	 * The number of pages of results from the query
	 */
	totalPages: number;
	/**
	 * The total number of items returned in the query
	 */
	totalItems: number;
};

/**
 * The response listing all of the datasources of each type
 * in a single response.
 */
export type AllDatasourcesResponse = {
	/**
	 * The list of openstack datasources
	 */
	openstackData: OpenstackListResponse;
	/**
	 * The list of guacamole datasources
	 */
	guacamoleData: GuacamoleListResponse;
	/**
	 * The list of saltstack datasources
	 */
	saltstackData: SaltstackListResponse;
};

export type AuthContext = {
	/**
	 * The user object
	 */
	user: UserResponse;
	/**
	 * The authentication object
	 */
	auth: KeyContext;
};

/**
 * The base model for all app authentication forms
 */
export type AuthForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
};

/**
 * The response of a connection test of a datasource
 */
export type ConnectionTestResults = {
	/**
	 * Whether the connection test was successful
	 */
	success: boolean;
	/**
	 * The result of the operation
	 */
	message: string;
	/**
	 * The error message if the operation failed
	 */
	error: string | null;
};

/**
 * form to create a user
 */
export type CreateUserForm = {
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The password of the user
	 */
	password: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

/**
 * The meta data of a datasource deleted returned in the response
 */
export type DatasourceDeleteData = {
	/**
	 * The type of the datasource deleted
	 */
	datasourceType: string;
	/**
	 * The username of the datasource deleted
	 */
	username: string;
	/**
	 * Whether the datasource was enabled before deletion
	 */
	wasEnabled: boolean;
};

/**
 * The response for a datasource when deleted
 */
export type DatasourceDeleteResponse = {
	/**
	 * Whether the operation was successful
	 */
	success: boolean;
	/**
	 * Describes the result of the operation
	 */
	message: string;
	/**
	 * The meta data of the datasource deleted
	 */
	data: DatasourceDeleteData;
};

/**
 * The status / health of a datasource
 */
export type DatasourceStatus = {
	/**
	 * Whether the datasource has an enabled model
	 */
	isEnabled: boolean;
	/**
	 * Whether the datasource is enabled or not
	 */
	enabledDatasource?: OpenstackResponse | GuacamoleResponse | SaltstackResponse | null;
	/**
	 * Whether the datasource connection test was successful
	 */
	isAlive: boolean;
	/**
	 * The error message if the connection test failed
	 */
	errorMessage?: string | null;
};

export type EventLogLevel = 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * represents the total number of logs for each log level
 */
export type EventLogLevelTotals = {
	info: number;
	warning: number;
	error: number;
	critical: number;
};

/**
 * represents a event log returned from the API
 */
export type EventLogRead = {
	logLevel: EventLogLevel;
	message: string;
	timestamp: string;
};

/**
 * Generic API response model
 */
export type GenericApiResponse = {
	data: {
		[key: string]: unknown;
	};
	/**
	 * The message returned by the API
	 */
	message: string;
};

export type GuacamoleCreate = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType: 'guacamole';
	/**
	 * The password for the datasource
	 */
	password: string;
	options: GuacamoleOptions;
};

export type GuacamoleListResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: unknown;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
	/**
	 * Whether any of the datasources are enabled
	 */
	anyEnabled?: boolean;
	datasourceType?: 'guacamole';
	list: Array<GuacamoleResponse>;
};

/**
 * The options for a Guacamole datasource
 */
export type GuacamoleOptions = {
	/**
	 * The name of the Guacamole datasource
	 */
	datasource: string;
};

/**
 * The optional options for updating a Guacamole datasource
 */
export type GuacamoleOptionsUpdate = {
	/**
	 * The name of the Guacamole datasource
	 */
	datasource?: string | null;
};

/**
 * The response model for a Guacamole datasource
 */
export type GuacamoleResponse = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType?: 'guacamole';
	/**
	 * The ID of the datasource
	 */
	id: number;
	options: GuacamoleOptions;
	/**
	 * Whether the datasource is enabled
	 */
	enabled: boolean;
};

/**
 * The update model for a Guacamole datasource
 */
export type GuacamoleUpdate = {
	/**
	 * The username for the datasource
	 */
	username?: string | null;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint?: string | null;
	datasourceType: 'guacamole';
	/**
	 * The password for the datasource
	 */
	password?: string | null;
	options?: GuacamoleOptionsUpdate | null;
};

export type HttpValidationErrorDetails = {
	message?: string;
	success?: boolean;
	/**
	 * An optional label for the error for errors that share status codes but have different meanings
	 */
	error_label?: string | null;
	errors: Array<PydanticError>;
};

/**
 * Information about the user assigned an APIKey
 */
export type KeyBearerIdentity = {
	/**
	 * The username of the users session
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: string;
};

export type KeyContext = {
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	maxAgeAt: string;
	/**
	 * the time the session expires in seconds ( time.tme() )
	 */
	expiresNext: string;
	/**
	 * the time the session was created in seconds ( time.tme() )
	 */
	issuedAt: string;
	/**
	 * The API key object
	 */
	apiKey: string;
};

/**
 * A model to represent the information stored in the redis store
 */
export type KeyInfo = {
	/**
	 * the identity of the user associated with the API key
	 */
	owner: KeyBearerIdentity | null;
	/**
	 * the health of the API key with the relevant timestamps
	 */
	health: ApiKeyHealth;
};

/**
 * represents the most recent logs for the critical and error log levels
 */
export type LastLogs = {
	lastCritical: EventLogRead | null;
	lastError: EventLogRead | null;
};

/**
 * the event log meta data to display in a dashboard
 */
export type LogMetaData = {
	/**
	 * The total count of each log level
	 */
	totals: EventLogLevelTotals;
	/**
	 * The last error and critical log metadata
	 */
	previousLogs: LastLogs;
};

/**
 * the logs returned from a query
 */
export type LogQueryResponse = {
	/**
	 * The results of the query of type SchemaT
	 */
	results: Array<EventLogRead>;
	/**
	 * Metadata for the query results for the frontend to handle
	 */
	pageContext: ApiQueryResult;
};

/**
 * A model to represent the response after a successful logout
 */
export type LogoutResponse = {
	/**
	 * the message to be sent to the client after a successful logout
	 */
	message?: string;
	success?: boolean;
};

/**
 * The request body to create a new openstack datasource
 */
export type OpenstackCreate = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType: 'openstack';
	/**
	 * The password for the datasource
	 */
	password: string;
	options: OpenstackOptions;
};

/**
 * The response body for a list of openstack datasources
 */
export type OpenstackListResponse = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType?: 'openstack';
	/**
	 * The ID of the datasource
	 */
	id: number;
	/**
	 * The options for the datasource
	 */
	options: OpenstackOptions;
	/**
	 * Whether the datasource is enabled
	 */
	enabled: boolean;
	data: Array<OpenstackResponse>;
};

/**
 * The options for a openstack
 */
export type OpenstackOptions = {
	/**
	 * The project ID for the Openstack authentication
	 */
	projectID?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName: string;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName: string;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName: string;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion: string;
};

/**
 * The response body for an openstack datasource
 */
export type OpenstackResponse = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType?: 'openstack';
	/**
	 * The ID of the datasource
	 */
	id: number;
	options: OpenstackOptions;
	/**
	 * Whether the datasource is enabled
	 */
	enabled: boolean;
};

/**
 * The request body to update an openstack datasource
 */
export type OpenstackUpdate = {
	/**
	 * The username for the datasource
	 */
	username?: string | null;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint?: string | null;
	datasourceType: 'openstack';
	/**
	 * The password for the datasource
	 */
	password?: string | null;
	options?: OpenstackUpdateOptions | null;
};

/**
 * The options for openstack as optional arguments
 */
export type OpenstackUpdateOptions = {
	/**
	 * The project ID for the Openstack authentication
	 */
	projectID?: string | null;
	/**
	 * The project name for the Openstack authentication
	 */
	projectName?: string | null;
	/**
	 * The project domain name for the Openstack authentication
	 */
	projectDomainName?: string | null;
	/**
	 * The user domain name for the Openstack authentication
	 */
	userDomainName?: string | null;
	/**
	 * The region name for the Openstack authentication
	 */
	regionName?: string | null;
	/**
	 * The identity API version for the Openstack authentication
	 */
	identityApiVersion?: string | null;
};

/**
 * The response listing all of the enabled datasources of
 * each type.
 */
export type PluginHealthCheck = {
	/**
	 * The status of openstack plugin
	 */
	openstack: DatasourceStatus;
	/**
	 * The status of guacamole plugin
	 */
	guacamole: DatasourceStatus;
	/**
	 * The enabled saltstack datasource
	 */
	saltstack: SaltstackResponse | null;
};

export type PydanticError = {
	/**
	 * The field that caused the error
	 */
	field: string;
	/**
	 * The error message
	 */
	message: string;
	/**
	 * The type of error
	 */
	type: string;
};

/**
 * The response returned when a rate limit is exceeded
 */
export type RateLimitErrorResponse = {
	message?: string;
	success?: boolean;
	error_label?: string;
	status: RateLimitStatus;
};

/**
 * the status pulled from redis of the rate limit for a given client
 */
export type RateLimitStatus = {
	/**
	 * Whether the request is rate limited
	 */
	isLimited: boolean;
	/**
	 * Remaining requests in current window
	 */
	remaining: number;
	/**
	 * Seconds until retry is allowed if limited
	 */
	retryAfter?: number;
	/**
	 * Maximum requests allowed in window
	 */
	limit: number;
	/**
	 * Time window in seconds
	 */
	windowSeconds: number;
	/**
	 * Timestamp when the current window resets
	 */
	resetAt: number;
};

/**
 * represents the role of a user
 */
export type Role = 'admin' | 'user' | 'read_only';

/**
 * The request model for creating a saltstack datasource
 */
export type SaltstackCreate = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType: 'saltstack';
	/**
	 * The password for the datasource
	 */
	password: string;
	options: SaltstackOptions;
};

/**
 * The response model for a list of saltstack datasources
 */
export type SaltstackListResponse = {
	/**
	 * The total number of items in the list
	 */
	total: number;
	/**
	 * The list of items returned by the API
	 */
	data: unknown;
	/**
	 * Whether the list is empty
	 */
	empty: boolean;
	/**
	 * Whether any of the datasources are enabled
	 */
	anyEnabled?: boolean;
	datasourceType?: 'saltstack';
	list: Array<SaltstackResponse>;
};

/**
 * The options for creating a saltstack datasource
 */
export type SaltstackOptions = {
	/**
	 * The hostname of the saltstack datasource.
	 */
	hostname: string;
};

/**
 * The response model for a saltstack datasource
 */
export type SaltstackResponse = {
	/**
	 * The username for the datasource
	 */
	username: string;
	/**
	 * The endpoint for the datasource
	 */
	endpoint: string;
	datasourceType?: 'saltstack';
	/**
	 * The ID of the datasource
	 */
	id: number;
	options: SaltstackOptions;
	/**
	 * Whether the datasource is enabled
	 */
	enabled: boolean;
};

/**
 * The request model for updating a saltstack datasource
 */
export type SaltstackUpdate = {
	/**
	 * The username for the datasource
	 */
	username?: string | null;
	/**
	 * The endpoint for the Saltstack datasource
	 */
	endpoint?: string | null;
	datasourceType: 'saltstack';
	/**
	 * The password for the datasource
	 */
	password?: string | null;
	options?: SaltstackUpdateOptions | null;
};

/**
 * The options for updating a saltstack datasource
 */
export type SaltstackUpdateOptions = {
	/**
	 * The hostname of the saltstack datasource.
	 */
	hostname?: string | null;
};

/**
 * form to update a user
 */
export type UpdateUserForm = {
	username?: string | null;
	password?: string | null;
	role?: Role | null;
};

/**
 * The response model for the user; provides all the information
 */
export type UserDetailsResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
	/**
	 * The date the user was created
	 */
	createdAt: string;
	/**
	 * The date the user was last updated
	 */
	updatedAt: string;
};

/**
 * The response model for the user; only provides the essential information
 */
export type UserResponse = {
	/**
	 * The ID of the user
	 */
	id: number;
	/**
	 * The username of the user
	 */
	username: string;
	/**
	 * The role of the user
	 */
	role: Role;
};

export type LoginData = {
	body: AuthForm;
	path?: never;
	query?: never;
	url: '/auth/';
};

export type LoginErrors = {
	/**
	 * When the user provides invalid credentials
	 */
	401: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
	/**
	 * Successful Response
	 */
	200: ApiKeyResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/logout/';
};

export type LogoutErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
	/**
	 * Successful Response
	 */
	200: LogoutResponse;
};

export type LogoutResponse2 = LogoutResponses[keyof LogoutResponses];

export type GetApiKeyStatusData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/key/';
};

export type GetApiKeyStatusErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetApiKeyStatusError = GetApiKeyStatusErrors[keyof GetApiKeyStatusErrors];

export type GetApiKeyStatusResponses = {
	/**
	 * Successful Response
	 */
	200: KeyInfo;
};

export type GetApiKeyStatusResponse = GetApiKeyStatusResponses[keyof GetApiKeyStatusResponses];

export type CheckPluginsHealthData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/status/';
};

export type CheckPluginsHealthErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type CheckPluginsHealthError = CheckPluginsHealthErrors[keyof CheckPluginsHealthErrors];

export type CheckPluginsHealthResponses = {
	/**
	 * Successful Response
	 */
	200: PluginHealthCheck;
};

export type CheckPluginsHealthResponse =
	CheckPluginsHealthResponses[keyof CheckPluginsHealthResponses];

export type GetAllPluginDatasourcesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/datasources/all/';
};

export type GetAllPluginDatasourcesErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetAllPluginDatasourcesError =
	GetAllPluginDatasourcesErrors[keyof GetAllPluginDatasourcesErrors];

export type GetAllPluginDatasourcesResponses = {
	/**
	 * Successful Response
	 */
	200: AllDatasourcesResponse;
};

export type GetAllPluginDatasourcesResponse =
	GetAllPluginDatasourcesResponses[keyof GetAllPluginDatasourcesResponses];

export type ReadAllDatasourcesData = {
	body?: never;
	path: {
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/';
};

export type ReadAllDatasourcesErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type ReadAllDatasourcesError = ReadAllDatasourcesErrors[keyof ReadAllDatasourcesErrors];

export type ReadAllDatasourcesResponses = {
	/**
	 * Successful Response
	 */
	200:
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackListResponse)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleListResponse)
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackListResponse);
};

export type ReadAllDatasourcesResponse =
	ReadAllDatasourcesResponses[keyof ReadAllDatasourcesResponses];

export type CreateDatasourceData = {
	/**
	 * The request body to create a which must match the create schema of the target datasource
	 */
	body:
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackCreate)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleCreate)
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackCreate);
	path: {
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/';
};

export type CreateDatasourceErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type CreateDatasourceError = CreateDatasourceErrors[keyof CreateDatasourceErrors];

export type CreateDatasourceResponses = {
	/**
	 * Successful Response
	 */
	201:
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackResponse)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleResponse)
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackResponse);
};

export type CreateDatasourceResponse = CreateDatasourceResponses[keyof CreateDatasourceResponses];

export type UpdateDatasourceIdData = {
	/**
	 * The request body to update a datasource which must match the update schema of the target datasource
	 */
	body:
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackUpdate)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleUpdate)
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackUpdate);
	path: {
		/**
		 * The id of model.
		 */
		datasource_id: number;
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/update/{datasource_id}';
};

export type UpdateDatasourceIdErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The datasource provided does not exist on the type provide.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type UpdateDatasourceIdError = UpdateDatasourceIdErrors[keyof UpdateDatasourceIdErrors];

export type UpdateDatasourceIdResponses = {
	/**
	 * Successful Response
	 */
	200:
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackResponse)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleResponse)
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackResponse);
};

export type UpdateDatasourceIdResponse =
	UpdateDatasourceIdResponses[keyof UpdateDatasourceIdResponses];

export type DeleteDatasourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		datasource_id: number;
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/delete/{datasource_id}';
};

export type DeleteDatasourceIdErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The datasource provided does not exist on the type provide.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type DeleteDatasourceIdError = DeleteDatasourceIdErrors[keyof DeleteDatasourceIdErrors];

export type DeleteDatasourceIdResponses = {
	/**
	 * Successful Response
	 */
	202: DatasourceDeleteResponse;
};

export type DeleteDatasourceIdResponse =
	DeleteDatasourceIdResponses[keyof DeleteDatasourceIdResponses];

export type ReadDatasourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		datasource_id: number;
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/read/{datasource_id}';
};

export type ReadDatasourceIdErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The datasource provided does not exist on the type provide.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type ReadDatasourceIdError = ReadDatasourceIdErrors[keyof ReadDatasourceIdErrors];

export type ReadDatasourceIdResponses = {
	/**
	 * Successful Response
	 */
	200:
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackResponse)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleResponse)
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackResponse);
};

export type ReadDatasourceIdResponse = ReadDatasourceIdResponses[keyof ReadDatasourceIdResponses];

export type TestConnectionIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		datasource_id: number;
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/test/{datasource_id}';
};

export type TestConnectionIdErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The datasource provided does not exist on the type provide.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type TestConnectionIdError = TestConnectionIdErrors[keyof TestConnectionIdErrors];

export type TestConnectionIdResponses = {
	/**
	 * Successful Response
	 */
	200: ConnectionTestResults;
};

export type TestConnectionIdResponse = TestConnectionIdResponses[keyof TestConnectionIdResponses];

export type ToggleDatasourceIdData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		datasource_id: number;
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/toggle/{datasource_id}';
};

export type ToggleDatasourceIdErrors = {
	/**
	 * When the datasource attempted to be toggled is already enable which would result in no datasources being enabled thus causing an error.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The datasource provided does not exist on the type provide.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type ToggleDatasourceIdError = ToggleDatasourceIdErrors[keyof ToggleDatasourceIdErrors];

export type ToggleDatasourceIdResponses = {
	/**
	 * Successful Response
	 */
	200:
		| ({
				datasourceType?: 'openstack';
		  } & OpenstackResponse)
		| ({
				datasourceType?: 'guacamole';
		  } & GuacamoleResponse)
		| ({
				datasourceType?: 'saltstack';
		  } & SaltstackResponse);
};

export type ToggleDatasourceIdResponse =
	ToggleDatasourceIdResponses[keyof ToggleDatasourceIdResponses];

export type GetDatasourceStatusData = {
	body?: never;
	path: {
		/**
		 * The datasource type to act on
		 */
		datasource: 'openstack' | 'guacamole' | 'saltstack';
	};
	query?: never;
	url: '/datasources/{datasource}/enabled/';
};

export type GetDatasourceStatusErrors = {
	/**
	 * When the datasource type is not known for datasource_type in request body (not guacamole, openstack or saltstack).
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetDatasourceStatusError = GetDatasourceStatusErrors[keyof GetDatasourceStatusErrors];

export type GetDatasourceStatusResponses = {
	/**
	 * Successful Response
	 */
	200: DatasourceStatus;
};

export type GetDatasourceStatusResponse =
	GetDatasourceStatusResponses[keyof GetDatasourceStatusResponses];

export type GetCurrentUserData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/me/';
};

export type GetCurrentUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
	/**
	 * Successful Response
	 */
	200: AuthContext;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetAllUsersData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/';
};

export type GetAllUsersErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetAllUsersError = GetAllUsersErrors[keyof GetAllUsersErrors];

export type GetAllUsersResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserResponse;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
	body: CreateUserForm;
	path?: never;
	query?: never;
	url: '/users/';
};

export type CreateUserErrors = {
	/**
	 * The username provided is taken.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
	/**
	 * Successful Response
	 */
	201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetAllDetailsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/users/details';
};

export type GetAllDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetAllDetailsError = GetAllDetailsErrors[keyof GetAllDetailsErrors];

export type GetAllDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: ApiListResponseUserDetailsResponse;
};

export type GetAllDetailsResponse = GetAllDetailsResponses[keyof GetAllDetailsResponses];

export type GetUserDetailsData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/details/{user_id}/';
};

export type GetUserDetailsErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type GetUserDetailsError = GetUserDetailsErrors[keyof GetUserDetailsErrors];

export type GetUserDetailsResponses = {
	/**
	 * Successful Response
	 */
	200: UserDetailsResponse;
};

export type GetUserDetailsResponse = GetUserDetailsResponses[keyof GetUserDetailsResponses];

export type DeleteUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type DeleteUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * An admin cannot delete their own account.
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: GenericApiResponse;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserData = {
	body?: never;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type ReadUserErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type ReadUserError = ReadUserErrors[keyof ReadUserErrors];

export type ReadUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type UpdateUserData = {
	body: UpdateUserForm;
	path: {
		/**
		 * The id of model.
		 */
		user_id: number;
	};
	query?: never;
	url: '/users/{user_id}/';
};

export type UpdateUserErrors = {
	/**
	 * The username provided is taken.
	 */
	400: ApiErrorResponse;
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
	/**
	 * Successful Response
	 */
	202: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SummaryData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/logs/summary/';
};

export type SummaryErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type SummaryError = SummaryErrors[keyof SummaryErrors];

export type SummaryResponses = {
	/**
	 * Successful Response
	 */
	200: LogMetaData;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SearchData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip (offset)
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/search/';
};

export type SearchErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type LogsFromTodayData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The number of records to skip (offset)
		 */
		skip?: number;
		/**
		 * The maximum items to return in the response
		 */
		limit?: number;
		/**
		 * To filter the output by timestamp
		 */
		orderByTimestamp?: boolean | null;
		/**
		 * To filter the output by log level
		 */
		logLevel?: EventLogLevel | null;
		/**
		 * To filter the output by message
		 */
		msgLike?: string | null;
	};
	url: '/logs/today/';
};

export type LogsFromTodayErrors = {
	/**
	 * When the user does not provide an API Key
	 */
	401: ApiErrorResponse;
	/**
	 * When the API Key is invalid
	 */
	403: ApiErrorResponse;
	/**
	 * Resource not found / doesn't exist.
	 */
	404: ApiErrorResponse;
	/**
	 * The users API Key was tampered with in a way it would attempt a Redis Key Injection.
	 */
	406: ApiErrorResponse;
	/**
	 * Pydantic raises due to improper data being provided
	 */
	422: HttpValidationErrorDetails;
	/**
	 * Rate limit exceeded
	 */
	429: RateLimitErrorResponse;
};

export type LogsFromTodayError = LogsFromTodayErrors[keyof LogsFromTodayErrors];

export type LogsFromTodayResponses = {
	/**
	 * Successful Response
	 */
	200: LogQueryResponse;
};

export type LogsFromTodayResponse = LogsFromTodayResponses[keyof LogsFromTodayResponses];

export type ClientOptions = {
	baseURL: `${string}://${string}` | (string & {});
};
