// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zApiErrorResponse = z.object({
	message: z.string(),
	success: z.boolean().optional().default(false),
	error_label: z.union([z.string(), z.null()]).optional()
});

export const zApiKeyHealth = z.object({
	maxAgeAt: z.string().datetime(),
	expiresNext: z.string().datetime(),
	issuedAt: z.string().datetime()
});

export const zApiKeyResponse = z.object({
	apiKey: z.string(),
	identity: z.object({
		username: z.string(),
		role: z.string()
	})
});

export const zApiListResponseUserDetailsResponse = z.object({
	total: z.number().int(),
	data: z.unknown(),
	empty: z.boolean()
});

export const zApiListResponseUserResponse = z.object({
	total: z.number().int(),
	data: z.unknown(),
	empty: z.boolean()
});

export const zApiQueryResult = z.object({
	total: z.number().int().gte(0),
	nextSkip: z.number().int().gte(0),
	totalPages: z.number().int().gte(1),
	totalItems: z.number().int().gte(0)
});

export const zAllDatasourcesResponse = z.object({
	openstackData: z.object({
		username: z.string().min(1).max(255),
		endpoint: z.string().min(1).max(255),
		datasourceType: z.literal('openstack').optional().default('openstack'),
		id: z.number().int(),
		options: z.object({
			projectID: z.union([z.string(), z.null()]).optional(),
			projectName: z.union([z.string(), z.null()]).optional(),
			projectDomainName: z.string(),
			userDomainName: z.string(),
			regionName: z.string(),
			identityApiVersion: z.string()
		}),
		enabled: z.boolean(),
		data: z.array(
			z.object({
				username: z.string().min(1).max(255),
				endpoint: z.string().min(1).max(255),
				datasourceType: z.literal('openstack').optional().default('openstack'),
				id: z.number().int(),
				options: z.object({
					projectID: z.union([z.string(), z.null()]).optional(),
					projectName: z.union([z.string(), z.null()]).optional(),
					projectDomainName: z.string(),
					userDomainName: z.string(),
					regionName: z.string(),
					identityApiVersion: z.string()
				}),
				enabled: z.boolean()
			})
		)
	}),
	guacamoleData: z.object({
		total: z.number().int(),
		data: z.unknown(),
		empty: z.boolean(),
		anyEnabled: z.boolean().optional().default(false),
		datasourceType: z.literal('guacamole').optional().default('guacamole'),
		list: z.array(
			z.object({
				username: z.string().min(1).max(255),
				endpoint: z.string().min(1).max(255),
				datasourceType: z.literal('guacamole').optional().default('guacamole'),
				id: z.number().int(),
				options: z.object({
					datasource: z.string()
				}),
				enabled: z.boolean()
			})
		)
	}),
	saltstackData: z.object({
		total: z.number().int(),
		data: z.unknown(),
		empty: z.boolean(),
		anyEnabled: z.boolean().optional().default(false),
		datasourceType: z.literal('saltstack').optional().default('saltstack'),
		list: z.array(
			z.object({
				username: z.string().min(1).max(255),
				endpoint: z.string().min(1).max(255),
				datasourceType: z.literal('saltstack').optional().default('saltstack'),
				id: z.number().int(),
				options: z.object({
					hostname: z.string()
				}),
				enabled: z.boolean()
			})
		)
	})
});

export const zAuthContext = z.object({
	user: z.object({
		id: z.number().int(),
		username: z.string(),
		role: z.enum(['admin', 'user', 'read_only'])
	}),
	auth: z.object({
		maxAgeAt: z.string().datetime(),
		expiresNext: z.string().datetime(),
		issuedAt: z.string().datetime(),
		apiKey: z.string()
	})
});

export const zAuthForm = z.object({
	username: z.string(),
	password: z.string()
});

export const zConnectionTestResults = z.object({
	success: z.boolean(),
	message: z.string(),
	error: z.union([z.string(), z.null()])
});

export const zCreateUserForm = z.object({
	username: z.string(),
	password: z.string(),
	role: z.enum(['admin', 'user', 'read_only'])
});

export const zDatasourceDeleteData = z.object({
	datasourceType: z.string(),
	username: z.string(),
	wasEnabled: z.boolean()
});

export const zDatasourceDeleteResponse = z.object({
	success: z.boolean(),
	message: z.string(),
	data: zDatasourceDeleteData
});

export const zDatasourceStatus = z.object({
	isEnabled: z.boolean(),
	enabledDatasource: z
		.union([
			z.object({
				username: z.string().min(1).max(255),
				endpoint: z.string().min(1).max(255),
				datasourceType: z.literal('openstack').optional().default('openstack'),
				id: z.number().int(),
				options: z.object({
					projectID: z.union([z.string(), z.null()]).optional(),
					projectName: z.union([z.string(), z.null()]).optional(),
					projectDomainName: z.string(),
					userDomainName: z.string(),
					regionName: z.string(),
					identityApiVersion: z.string()
				}),
				enabled: z.boolean()
			}),
			z.object({
				username: z.string().min(1).max(255),
				endpoint: z.string().min(1).max(255),
				datasourceType: z.literal('guacamole').optional().default('guacamole'),
				id: z.number().int(),
				options: z.object({
					datasource: z.string()
				}),
				enabled: z.boolean()
			}),
			z.object({
				username: z.string().min(1).max(255),
				endpoint: z.string().min(1).max(255),
				datasourceType: z.literal('saltstack').optional().default('saltstack'),
				id: z.number().int(),
				options: z.object({
					hostname: z.string()
				}),
				enabled: z.boolean()
			}),
			z.null()
		])
		.optional(),
	isAlive: z.boolean(),
	errorMessage: z.union([z.string(), z.null()]).optional()
});

export const zEventLogLevel = z.enum(['INFO', 'WARNING', 'ERROR', 'CRITICAL']);

export const zEventLogLevelTotals = z.object({
	info: z.number().int(),
	warning: z.number().int(),
	error: z.number().int(),
	critical: z.number().int()
});

export const zEventLogRead = z.object({
	logLevel: zEventLogLevel,
	message: z.string(),
	timestamp: z.string().datetime()
});

export const zGenericApiResponse = z.object({
	data: z.object({}),
	message: z.string()
});

export const zGuacamoleCreate = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('guacamole'),
	password: z.string().min(1).max(255),
	options: z.object({
		datasource: z.string()
	})
});

export const zGuacamoleListResponse = z.object({
	total: z.number().int(),
	data: z.unknown(),
	empty: z.boolean(),
	anyEnabled: z.boolean().optional().default(false),
	datasourceType: z.literal('guacamole').optional().default('guacamole'),
	list: z.array(
		z.object({
			username: z.string().min(1).max(255),
			endpoint: z.string().min(1).max(255),
			datasourceType: z.literal('guacamole').optional().default('guacamole'),
			id: z.number().int(),
			options: z.object({
				datasource: z.string()
			}),
			enabled: z.boolean()
		})
	)
});

export const zGuacamoleOptions = z.object({
	datasource: z.string()
});

export const zGuacamoleOptionsUpdate = z.object({
	datasource: z.union([z.string(), z.null()]).optional()
});

export const zGuacamoleResponse = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('guacamole').optional().default('guacamole'),
	id: z.number().int(),
	options: zGuacamoleOptions,
	enabled: z.boolean()
});

export const zGuacamoleUpdate = z.object({
	username: z.union([z.string(), z.null()]).optional(),
	endpoint: z.union([z.string(), z.null()]).optional(),
	datasourceType: z.literal('guacamole'),
	password: z.union([z.string(), z.null()]).optional(),
	options: z.union([zGuacamoleOptionsUpdate, z.null()]).optional()
});

export const zHttpValidationErrorDetails = z.object({
	message: z.string().optional().default('Invalid data.'),
	success: z.boolean().optional().default(false),
	error_label: z.union([z.string(), z.null()]).optional(),
	errors: z.array(
		z.object({
			field: z.string(),
			message: z.string(),
			type: z.string()
		})
	)
});

export const zKeyBearerIdentity = z.object({
	username: z.string(),
	role: z.string()
});

export const zKeyContext = z.object({
	maxAgeAt: z.string().datetime(),
	expiresNext: z.string().datetime(),
	issuedAt: z.string().datetime(),
	apiKey: z.string()
});

export const zKeyInfo = z.object({
	owner: z.union([zKeyBearerIdentity, z.null()]),
	health: zApiKeyHealth
});

export const zLastLogs = z.object({
	lastCritical: z.union([zEventLogRead, z.null()]),
	lastError: z.union([zEventLogRead, z.null()])
});

export const zLogMetaData = z.object({
	totals: zEventLogLevelTotals,
	previousLogs: zLastLogs
});

export const zLogQueryResponse = z.object({
	results: z.array(zEventLogRead),
	pageContext: zApiQueryResult
});

export const zLogoutResponse = z.object({
	message: z.string().optional().default('You have been logged out successfully'),
	success: z.boolean().optional().default(true)
});

export const zOpenstackCreate = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('openstack'),
	password: z.string().min(1).max(255),
	options: z.object({
		projectID: z.union([z.string(), z.null()]).optional(),
		projectName: z.union([z.string(), z.null()]).optional(),
		projectDomainName: z.string(),
		userDomainName: z.string(),
		regionName: z.string(),
		identityApiVersion: z.string()
	})
});

export const zOpenstackListResponse = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('openstack').optional().default('openstack'),
	id: z.number().int(),
	options: z.object({
		projectID: z.union([z.string(), z.null()]).optional(),
		projectName: z.union([z.string(), z.null()]).optional(),
		projectDomainName: z.string(),
		userDomainName: z.string(),
		regionName: z.string(),
		identityApiVersion: z.string()
	}),
	enabled: z.boolean(),
	data: z.array(
		z.object({
			username: z.string().min(1).max(255),
			endpoint: z.string().min(1).max(255),
			datasourceType: z.literal('openstack').optional().default('openstack'),
			id: z.number().int(),
			options: z.object({
				projectID: z.union([z.string(), z.null()]).optional(),
				projectName: z.union([z.string(), z.null()]).optional(),
				projectDomainName: z.string(),
				userDomainName: z.string(),
				regionName: z.string(),
				identityApiVersion: z.string()
			}),
			enabled: z.boolean()
		})
	)
});

export const zOpenstackOptions = z.object({
	projectID: z.union([z.string(), z.null()]).optional(),
	projectName: z.union([z.string(), z.null()]).optional(),
	projectDomainName: z.string(),
	userDomainName: z.string(),
	regionName: z.string(),
	identityApiVersion: z.string()
});

export const zOpenstackResponse = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('openstack').optional().default('openstack'),
	id: z.number().int(),
	options: zOpenstackOptions,
	enabled: z.boolean()
});

export const zOpenstackUpdate = z.object({
	username: z.union([z.string(), z.null()]).optional(),
	endpoint: z.union([z.string(), z.null()]).optional(),
	datasourceType: z.literal('openstack'),
	password: z.union([z.string(), z.null()]).optional(),
	options: z
		.union([
			z.object({
				projectID: z.union([z.string(), z.null()]).optional(),
				projectName: z.union([z.string(), z.null()]).optional(),
				projectDomainName: z.union([z.string(), z.null()]).optional(),
				userDomainName: z.union([z.string(), z.null()]).optional(),
				regionName: z.union([z.string(), z.null()]).optional(),
				identityApiVersion: z.union([z.string(), z.null()]).optional()
			}),
			z.null()
		])
		.optional()
});

export const zOpenstackUpdateOptions = z.object({
	projectID: z.union([z.string(), z.null()]).optional(),
	projectName: z.union([z.string(), z.null()]).optional(),
	projectDomainName: z.union([z.string(), z.null()]).optional(),
	userDomainName: z.union([z.string(), z.null()]).optional(),
	regionName: z.union([z.string(), z.null()]).optional(),
	identityApiVersion: z.union([z.string(), z.null()]).optional()
});

export const zPluginHealthCheck = z.object({
	openstack: zDatasourceStatus,
	guacamole: zDatasourceStatus,
	saltstack: z.union([
		z.object({
			username: z.string().min(1).max(255),
			endpoint: z.string().min(1).max(255),
			datasourceType: z.literal('saltstack').optional().default('saltstack'),
			id: z.number().int(),
			options: z.object({
				hostname: z.string()
			}),
			enabled: z.boolean()
		}),
		z.null()
	])
});

export const zPydanticError = z.object({
	field: z.string(),
	message: z.string(),
	type: z.string()
});

export const zRateLimitErrorResponse = z.object({
	message: z
		.string()
		.optional()
		.default(
			'You have exceeded the usage rates for this resource and have been timed out. Try again later'
		),
	success: z.boolean().optional().default(false),
	error_label: z.string().optional().default('RATE_LIMIT'),
	status: z.object({
		isLimited: z.boolean(),
		remaining: z.number().int(),
		retryAfter: z.number().int().optional().default(0),
		limit: z.number().int(),
		windowSeconds: z.number().int(),
		resetAt: z.number().int()
	})
});

export const zRateLimitStatus = z.object({
	isLimited: z.boolean(),
	remaining: z.number().int(),
	retryAfter: z.number().int().optional().default(0),
	limit: z.number().int(),
	windowSeconds: z.number().int(),
	resetAt: z.number().int()
});

export const zRole = z.enum(['admin', 'user', 'read_only']);

export const zSaltstackCreate = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('saltstack'),
	password: z.string().min(1).max(255),
	options: z.object({
		hostname: z.string()
	})
});

export const zSaltstackListResponse = z.object({
	total: z.number().int(),
	data: z.unknown(),
	empty: z.boolean(),
	anyEnabled: z.boolean().optional().default(false),
	datasourceType: z.literal('saltstack').optional().default('saltstack'),
	list: z.array(
		z.object({
			username: z.string().min(1).max(255),
			endpoint: z.string().min(1).max(255),
			datasourceType: z.literal('saltstack').optional().default('saltstack'),
			id: z.number().int(),
			options: z.object({
				hostname: z.string()
			}),
			enabled: z.boolean()
		})
	)
});

export const zSaltstackOptions = z.object({
	hostname: z.string()
});

export const zSaltstackResponse = z.object({
	username: z.string().min(1).max(255),
	endpoint: z.string().min(1).max(255),
	datasourceType: z.literal('saltstack').optional().default('saltstack'),
	id: z.number().int(),
	options: zSaltstackOptions,
	enabled: z.boolean()
});

export const zSaltstackUpdate = z.object({
	username: z.union([z.string(), z.null()]).optional(),
	endpoint: z.union([z.string(), z.null()]).optional(),
	datasourceType: z.literal('saltstack'),
	password: z.union([z.string(), z.null()]).optional(),
	options: z
		.union([
			z.object({
				hostname: z.union([z.string(), z.null()]).optional()
			}),
			z.null()
		])
		.optional()
});

export const zSaltstackUpdateOptions = z.object({
	hostname: z.union([z.string(), z.null()]).optional()
});

export const zUpdateUserForm = z.object({
	username: z.union([z.string(), z.null()]).optional(),
	password: z.union([z.string(), z.null()]).optional(),
	role: z.union([zRole, z.null()]).optional()
});

export const zUserDetailsResponse = z.object({
	id: z.number().int(),
	username: z.string(),
	role: zRole,
	createdAt: z.string().datetime(),
	updatedAt: z.string().datetime()
});

export const zUserResponse = z.object({
	id: z.number().int(),
	username: z.string(),
	role: zRole
});

export const zLoginResponse = zApiKeyResponse;

export const zLogoutResponse2 = zLogoutResponse;

export const zGetApiKeyStatusResponse = zKeyInfo;

export const zCheckPluginsHealthResponse = zPluginHealthCheck;

export const zGetAllPluginDatasourcesResponse = zAllDatasourcesResponse;

export const zReadAllDatasourcesResponse = z.union([
	z
		.object({
			datasourceType: z.literal('saltstack').optional()
		})
		.merge(zSaltstackListResponse),
	z
		.object({
			datasourceType: z.literal('guacamole').optional()
		})
		.merge(zGuacamoleListResponse),
	z
		.object({
			datasourceType: z.literal('openstack').optional()
		})
		.merge(zOpenstackListResponse)
]);

export const zCreateDatasourceResponse = z.union([
	z
		.object({
			datasourceType: z.literal('openstack').optional()
		})
		.merge(zOpenstackResponse),
	z
		.object({
			datasourceType: z.literal('guacamole').optional()
		})
		.merge(zGuacamoleResponse),
	z
		.object({
			datasourceType: z.literal('saltstack').optional()
		})
		.merge(zSaltstackResponse)
]);

export const zUpdateDatasourceIdResponse = z.union([
	z
		.object({
			datasourceType: z.literal('openstack').optional()
		})
		.merge(zOpenstackResponse),
	z
		.object({
			datasourceType: z.literal('guacamole').optional()
		})
		.merge(zGuacamoleResponse),
	z
		.object({
			datasourceType: z.literal('saltstack').optional()
		})
		.merge(zSaltstackResponse)
]);

export const zDeleteDatasourceIdResponse = zDatasourceDeleteResponse;

export const zReadDatasourceIdResponse = z.union([
	z
		.object({
			datasourceType: z.literal('openstack').optional()
		})
		.merge(zOpenstackResponse),
	z
		.object({
			datasourceType: z.literal('guacamole').optional()
		})
		.merge(zGuacamoleResponse),
	z
		.object({
			datasourceType: z.literal('saltstack').optional()
		})
		.merge(zSaltstackResponse)
]);

export const zTestConnectionIdResponse = zConnectionTestResults;

export const zToggleDatasourceIdResponse = z.union([
	z
		.object({
			datasourceType: z.literal('openstack').optional()
		})
		.merge(zOpenstackResponse),
	z
		.object({
			datasourceType: z.literal('guacamole').optional()
		})
		.merge(zGuacamoleResponse),
	z
		.object({
			datasourceType: z.literal('saltstack').optional()
		})
		.merge(zSaltstackResponse)
]);

export const zGetDatasourceStatusResponse = zDatasourceStatus;

export const zGetCurrentUserResponse = zAuthContext;

export const zGetAllUsersResponse = zApiListResponseUserResponse;

export const zCreateUserResponse = zUserResponse;

export const zGetAllDetailsResponse = zApiListResponseUserDetailsResponse;

export const zGetUserDetailsResponse = zUserDetailsResponse;

export const zDeleteUserResponse = zGenericApiResponse;

export const zReadUserResponse = zUserResponse;

export const zUpdateUserResponse = zUserResponse;

export const zSummaryResponse = zLogMetaData;

export const zSearchResponse = zLogQueryResponse;

export const zLogsFromTodayResponse = zLogQueryResponse;
