app:
    config_label: dev
    environment: local
    mode: dev
    env_file: .env
    debug: true
    testing: false
    console_enabled: true
    log_level: INFO
    event_log_level: INFO
    allow_documentation: true
cors:
    allow_orgins:
        - "*"
    allow_methods:
        - "*"
    allow_headers:
        - "*"
    allow_credentials: true
database:
    url: sqlite+aiosqlite:///instance/app.db
    journal_mode: WAL
    timeout: 30
    busy_timeout: 30
    sqlalchemy_echo: true
    db_log_level: WARNING
redis:
    host: localhostc
    port: 6379
    db: 0
logging:
  db_level: WARNING
  api_level: INFO
  service_level: INFO
  middleware_level: INFO
  allow_file_handler: true
