app:
  config_label: test
  environment: container
  mode: dev
  env_file: temp
  debug: true
  testing: true
  min_log_level: WARNING
  console_enabled: true
documentation:
  allowed: false
cors_policy:
  allow_orgins:
    - "*"
  allow_methods:
    - "*"
  allow_headers:
    - "*"
  allow_credentials: true
database:
  url: "sqlite+aiosqlite:///:memory:"
  journal_mode: MEMORY
  timeout: 30
  busy_timeout: 30
  sqlalchemy_echo: false
redis:
  host: redis
  port: 6379
  db: 0
api_key:
  cookie_secure: false
  cookie_http_only: true
  cookie_samesite: lax
  cookie_expr_hours: 1
  session_lifetime_days: 1
